/**
 * Generates the shipped puzzle set.
 *
 *   npx esbuild scripts/generatePuzzles.ts --bundle --platform=node \
 *     --format=esm --outfile=scripts/gen.mjs && node scripts/gen.mjs
 *
 * Writes src/games/kreuzwortraetsel/puzzles.ts. Run it again to reroll the set
 * (for instance after adding words); the output is deterministic per seed.
 */
import { writeFileSync } from 'fs'
import { searchFilledLayout } from '../src/games/kreuzwortraetsel/denseGenerator'
import { serialiseGrid } from '../src/games/kreuzwortraetsel/loadPuzzle'
import { buildPool } from '../src/games/kreuzwortraetsel/words'

const TARGET = Number(process.argv[2] ?? 150)
const pool = buildPool()

/** Seeded RNG so a rerun with the same target reproduces the same set. */
function mulberry32(seed: number) {
  return () => {
    seed |= 0
    seed = (seed + 0x6d2b79f5) | 0
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

const out: { grid: string; answers: string[] }[] = []
const t0 = Date.now()

/**
 * Each puzzle costs seconds of search, so `--append` keeps what is already in
 * puzzles.ts and only looks for the shortfall. The seed advances past the run
 * that produced them, otherwise the search would retrace its steps and find the
 * same layouts again.
 */
const append = process.argv.includes('--append')
let seed = 1

if (append) {
  const existing = (await import('../src/games/kreuzwortraetsel/puzzles')).PUZZLES
  out.push(...existing.map((p) => ({ grid: p.grid, answers: [...p.answers] })))
  seed = 1_000_000 + out.length * 7919
  console.log(`appending to ${out.length} existing puzzles`)
}

/**
 * How often each answer is already used. Passing this into the search pushes it
 * towards answers the set has not shown yet, which is what stops the same short
 * words appearing in puzzle after puzzle.
 */
const usage = new Map<string, number>()
for (const p of out) for (const a of p.answers) usage.set(a, (usage.get(a) ?? 0) + 1)

/** Each puzzle takes seconds to find, so save as we go rather than at the end. */
function save() {
  const body = out
    .map((p) => `  { grid: '${p.grid}', answers: ${JSON.stringify(p.answers)} },`)
    .join('\n')

  writeFileSync(
    'src/games/kreuzwortraetsel/puzzles.ts',
    `import type { StoredPuzzle } from './loadPuzzle'

/**
 * Pre-generated 12×12 layouts. Every one is completely filled: each cell is
 * either a clue cell with a question or an answer cell with a letter, so no
 * puzzle renders a blank.
 *
 * Generated by scripts/generatePuzzles.ts — do not edit by hand.
 */
export const PUZZLES: StoredPuzzle[] = [
${body}
]
`,
    'utf8'
  )
}

while (out.length < TARGET) {
  const found = searchFilledLayout(pool, mulberry32(seed++), { usage })
  if (!found) continue
  for (const a of found.answers) usage.set(a, (usage.get(a) ?? 0) + 1)
  out.push({ grid: serialiseGrid(found.isClue), answers: found.answers })
  const done = out.length
  if (done % 10 === 0 || done === TARGET) {
    save()
    const secs = (Date.now() - t0) / 1000
    console.log(`${done}/${TARGET} — ${secs.toFixed(0)}s (${(secs / done).toFixed(1)}s each)`)
  }
}

save()
console.log(`\nwrote ${out.length} puzzles in ${((Date.now() - t0) / 1000).toFixed(0)}s`)
