import type { Category } from './index'

export const alltag: Category = {
  id: 'alltag',
  label: 'Alltag & Essen',
  entries: [
    ['Brot', 'Grundnahrungsmittel vom Bäcker'],
    ['Broetchen', 'Kleines Frühstücksgebäck'],
    ['Butter', 'Streichfett aus Milch'],
    ['Kaese', 'Milchprodukt mit Löchern'],
    ['Wurst', 'Fleischerzeugnis im Darm'],
    ['Schinken', 'Geräuchertes Fleisch vom Schwein'],
    ['Salami', 'Harte luftgetrocknete Wurst'],
    ['Speck', 'Fettes Stück vom Schwein'],
    ['Ei', 'Frühstück aus dem Nest'],
    ['Milch', 'Weisses Getränk von der Kuh'],
    ['Sahne', 'Fettreicher Teil der Milch'],
    ['Joghurt', 'Gesäuertes Milchprodukt'],
    ['Quark', 'Frischkäse für Kuchen'],
    ['Honig', 'Süsses Erzeugnis der Bienen'],
    ['Marmelade', 'Süsser Fruchtaufstrich'],
    ['Zucker', 'Weisses Süssungsmittel'],
    ['Salz', 'Weisses Würzmittel'],
    ['Pfeffer', 'Scharfes Gewürz aus Körnern'],
    ['Paprika', 'Rotes Gewürzpulver, auch Gemüse'],
    ['Zimt', 'Weihnachtliches Gewürz aus Rinde'],
    ['Vanille', 'Gewürz aus der Schote'],
    ['Muskat', 'Gewürznuss'],
    ['Ingwer', 'Scharfe Wurzelknolle'],
    ['Curry', 'Indische Gewürzmischung'],
    ['Senf', 'Scharfe gelbe Paste'],
    ['Ketchup', 'Tomatensauce zur Pommes'],
    ['Mayonnaise', 'Kalte Sauce aus Ei und Öl'],
    ['Essig', 'Saure Würzflüssigkeit'],
    ['Oel', 'Flüssiges Fett zum Braten'],
    ['Mehl', 'Gemahlenes Getreide'],
    ['Hefe', 'Treibmittel für Teig'],
    ['Teig', 'Rohmasse für Brot und Kuchen'],
    ['Nudeln', 'Teigware aus Italien'],
    ['Spaghetti', 'Lange dünne Nudeln'],
    ['Reis', 'Grundnahrungsmittel Asiens'],
    ['Kartoffel', 'Knolle aus der Erde'],
    ['Pommes', 'Frittierte Kartoffelstäbchen'],
    ['Knoedel', 'Runde Beilage aus Kartoffeln'],
    ['Suppe', 'Flüssige warme Speise'],
    ['Eintopf', 'Deftiges Gericht aus einem Topf'],
    ['Salat', 'Kalte Speise aus Blattgemüse'],
    ['Gemuese', 'Pflanzliche Beilage'],
    ['Obst', 'Süsse Früchte'],
    ['Apfel', 'Frucht mit Kerngehäuse'],
    ['Birne', 'Frucht mit dickem Ende'],
    ['Kirsche', 'Kleine rote Steinfrucht'],
    ['Pflaume', 'Blaue Steinfrucht'],
    ['Pfirsich', 'Frucht mit samtiger Haut'],
    ['Aprikose', 'Kleine orange Steinfrucht'],
    ['Traube', 'Frucht für Wein'],
    ['Erdbeere', 'Rote Frucht des Sommers'],
    ['Himbeere', 'Rote Sammelfrucht'],
    ['Brombeere', 'Schwarze Sammelfrucht'],
    ['Heidelbeere', 'Blaue Waldbeere'],
    ['Johannisbeere', 'Rote Beere in Rispen'],
    ['Banane', 'Krumme gelbe Frucht'],
    ['Orange', 'Runde Zitrusfrucht'],
    ['Zitrone', 'Saure gelbe Frucht'],
    ['Limette', 'Kleine grüne Zitrusfrucht'],
    ['Mandarine', 'Kleine leicht schälbare Zitrusfrucht'],
    ['Ananas', 'Tropenfrucht mit Schopf'],
    ['Mango', 'Süsse Tropenfrucht'],
    ['Kiwi', 'Grüne Frucht mit pelziger Schale'],
    ['Melone', 'Grosse saftige Frucht'],
    ['Feige', 'Süsse Mittelmeerfrucht'],
    ['Dattel', 'Süsse Frucht der Palme'],
    ['Kokosnuss', 'Grosse Nuss der Palme'],
    ['Walnuss', 'Nuss mit gefurchtem Kern'],
    ['Haselnuss', 'Nuss für Nougat'],
    ['Mandel', 'Nuss für Marzipan'],
    ['Erdnuss', 'Hülsenfrucht als Knabberei'],
    ['Tomate', 'Rotes Fruchtgemüse'],
    ['Gurke', 'Grünes langes Gemüse'],
    ['Zwiebel', 'Knolle, die zum Weinen bringt'],
    ['Knoblauch', 'Würzige Zehe gegen Vampire'],
    ['Lauch', 'Stangengemüse, auch Porree'],
    ['Moehre', 'Orange Wurzel, auch Karotte'],
    ['Sellerie', 'Knolle für die Suppe'],
    ['Radieschen', 'Kleine scharfe rote Knolle'],
    ['Rettich', 'Grosser scharfer Rettichwurzel'],
    ['Kohl', 'Blattgemüse als Kopf'],
    ['Blumenkohl', 'Weisser Kohl mit Röschen'],
    ['Brokkoli', 'Grüner Kohl mit Röschen'],
    ['Rosenkohl', 'Kleine Kohlröschen'],
    ['Spinat', 'Grünes Blattgemüse mit Eisen'],
    ['Spargel', 'Edles Frühlingsgemüse'],
    ['Erbse', 'Grüne Hülsenfrucht'],
    ['Bohne', 'Hülsenfrucht, grün oder weiss'],
    ['Linse', 'Kleine flache Hülsenfrucht'],
    ['Mais', 'Getreide mit Kolben'],
    ['Weizen', 'Getreide für Weissbrot'],
    ['Roggen', 'Getreide für dunkles Brot'],
    ['Hafer', 'Getreide für Müsli'],
    ['Gerste', 'Getreide für Bier'],
    ['Kuerbis', 'Grosse Frucht für Halloween'],
    ['Zucchini', 'Längliches Sommergemüse'],
    ['Aubergine', 'Violettes Gemüse'],
    ['Avocado', 'Grüne Frucht mit grossem Kern'],
    ['Olive', 'Frucht des Mittelmeerbaums'],
    ['Pilzpfanne', 'Gebratene Pilze als Gericht'],

    ['Kaffee', 'Schwarzes Wachmachergetränk'],
    ['Tee', 'Aufguss aus Blättern'],
    ['Kakao', 'Süsses Schokoladengetränk'],
    ['Wasser', 'Wichtigstes Getränk'],
    ['Saft', 'Getränk aus Früchten'],
    ['Limonade', 'Süsses Sprudelgetränk'],
    ['Bier', 'Gerstensaft'],
    ['Wein', 'Getränk aus Trauben'],
    ['Sekt', 'Prickelndes Festgetränk'],
    ['Champagner', 'Edler Schaumwein aus Frankreich'],
    ['Whisky', 'Schottische Spirituose'],
    ['Rum', 'Spirituose aus Zuckerrohr'],
    ['Wodka', 'Klare russische Spirituose'],
    ['Gin', 'Spirituose mit Wacholder'],
    ['Likoer', 'Süsse Spirituose'],
    ['Cocktail', 'Gemischtes Getränk mit Schirmchen'],
    ['Espresso', 'Starker kleiner Kaffee'],
    ['Cappuccino', 'Kaffee mit Milchschaum'],
    ['Smoothie', 'Püriertes Fruchtgetränk'],

    ['Kuchen', 'Süsses Gebäck zum Kaffee'],
    ['Torte', 'Mehrschichtiger Kuchen'],
    ['Keks', 'Kleines trockenes Gebäck'],
    ['Plaetzchen', 'Weihnachtliches Kleingebäck'],
    ['Schokolade', 'Süsse Tafel aus Kakao'],
    ['Praline', 'Gefüllte Schokoladenkugel'],
    ['Bonbon', 'Hartes Zuckerstück'],
    ['Marzipan', 'Süsse Mandelmasse'],
    ['Nougat', 'Süsse Nussmasse'],
    ['Pudding', 'Süsse gestockte Speise'],
    ['Eis', 'Kalte Süssspeise in der Waffel'],
    ['Waffel', 'Gebäck aus dem Eisen'],
    ['Krapfen', 'Frittiertes Faschingsgebäck'],
    ['Brezel', 'Laugengebäck mit Schlaufen'],
    ['Strudel', 'Gerollter Apfelkuchen'],
    ['Muesli', 'Frühstück aus Flocken und Obst'],
    ['Pfannkuchen', 'Flacher Teigfladen aus der Pfanne'],

    ['Pizza', 'Belegter Teigfladen aus Italien'],
    ['Lasagne', 'Geschichtetes Nudelgericht'],
    ['Risotto', 'Cremiges Reisgericht'],
    ['Sushi', 'Japanisches Reisgericht mit Fisch'],
    ['Burger', 'Hackfleisch im Brötchen'],
    ['Doener', 'Fleisch vom Drehspiess im Fladen'],
    ['Gulasch', 'Ungarisches Fleischgericht'],
    ['Schnitzel', 'Paniertes Fleisch aus Wien'],
    ['Braten', 'Grosses Stück Fleisch aus dem Ofen'],
    ['Steak', 'Kurzgebratenes Fleischstück'],
    ['Frikadelle', 'Gebratener Hackfleischkloss'],
    ['Auflauf', 'Überbackenes Ofengericht'],
    ['Omelett', 'Eierspeise aus der Pfanne'],
    ['Ruehrei', 'Zerrührte Eier aus der Pfanne'],
    ['Sauce', 'Flüssige Beigabe zum Essen'],
    ['Beilage', 'Was zum Hauptgericht kommt'],
    ['Vorspeise', 'Erster Gang des Menüs'],
    ['Nachtisch', 'Letzter Gang des Menüs'],
    ['Rezept', 'Anleitung zum Kochen'],
    ['Zutat', 'Bestandteil eines Gerichts'],
    ['Portion', 'Menge für eine Person'],

    ['Kueche', 'Raum zum Kochen'],
    ['Herd', 'Gerät zum Kochen'],
    ['Backofen', 'Gerät zum Backen'],
    ['Kuehlschrank', 'Gerät hält Lebensmittel kalt'],
    ['Gefriertruhe', 'Gerät zum Einfrieren'],
    ['Mikrowelle', 'Gerät zum schnellen Erwärmen'],
    ['Spuelmaschine', 'Gerät wäscht das Geschirr'],
    ['Toaster', 'Gerät röstet Brot'],
    ['Wasserkocher', 'Gerät erhitzt Wasser'],
    ['Mixer', 'Gerät zum Pürieren'],
    ['Topf', 'Gefäss zum Kochen'],
    ['Pfanne', 'Flaches Gefäss zum Braten'],
    ['Teller', 'Geschirr zum Essen'],
    ['Tasse', 'Gefäss für Kaffee'],
    ['Glas', 'Durchsichtiges Trinkgefäss'],
    ['Becher', 'Grösseres Trinkgefäss'],
    ['Schuessel', 'Tiefe Schale'],
    ['Loeffel', 'Besteck für die Suppe'],
    ['Gabel', 'Besteck mit Zinken'],
    ['Messer', 'Besteck zum Schneiden'],
    ['Brett', 'Unterlage zum Schneiden'],
    ['Sieb', 'Gerät zum Abgiessen'],
    ['Kanne', 'Gefäss zum Ausgiessen'],
    ['Flasche', 'Gefäss mit engem Hals'],
    ['Dose', 'Verschlossener Blechbehälter'],
    ['Korken', 'Verschluss der Weinflasche'],
    ['Serviette', 'Tuch zum Mundabwischen'],
    ['Tischdecke', 'Tuch über dem Tisch'],
    ['Schuerze', 'Schutz beim Kochen'],

    ['Wohnung', 'Zuhause im Mehrfamilienhaus'],
    ['Haus', 'Gebäude zum Wohnen'],
    ['Zimmer', 'Raum in der Wohnung'],
    ['Flur', 'Gang in der Wohnung'],
    ['Keller', 'Raum unter dem Haus'],
    ['Dachboden', 'Raum unter dem Dach'],
    ['Balkon', 'Vorbau zum Draussensitzen'],
    ['Terrasse', 'Sitzplatz am Haus'],
    ['Garten', 'Grünfläche am Haus'],
    ['Garage', 'Unterstand für das Auto'],
    ['Treppe', 'Verbindung zwischen Stockwerken'],
    ['Aufzug', 'Fahrstuhl im Haus'],
    ['Tuer', 'Verschluss eines Raums'],
    ['Fenster', 'Öffnung für Licht'],
    ['Wand', 'Senkrechte Begrenzung des Raums'],
    ['Decke', 'Obere Begrenzung des Raums'],
    ['Boden', 'Untere Fläche des Raums'],
    ['Dach', 'Oberer Abschluss des Hauses'],
    ['Schornstein', 'Rauchabzug am Dach'],
    ['Kamin', 'Offene Feuerstelle im Wohnzimmer'],
    ['Heizung', 'Gerät für Wärme'],
    ['Klingel', 'Was an der Haustür läutet'],
    ['Schluessel', 'Womit man aufschliesst'],
    ['Schloss', 'Was der Schlüssel öffnet'],
    ['Briefkasten', 'Behälter für die Post'],

    ['Tisch', 'Möbel mit Platte und Beinen'],
    ['Stuhl', 'Sitzmöbel mit Lehne'],
    ['Sessel', 'Bequemer Einzelsitz'],
    ['Sofa', 'Sitzmöbel für mehrere'],
    ['Bett', 'Möbel zum Schlafen'],
    ['Schrank', 'Möbel zum Verstauen'],
    ['Regal', 'Möbel mit Fächern'],
    ['Kommode', 'Möbel mit Schubladen'],
    ['Spiegel', 'Glas, das das Bild zurückwirft'],
    ['Teppich', 'Bodenbelag aus Textil'],
    ['Vorhang', 'Stoff vor dem Fenster'],
    ['Lampe', 'Gerät für Licht'],
    ['Kissen', 'Weiche Unterlage für den Kopf'],
    ['Decke', 'Wärmende Auflage im Bett'],
    ['Matratze', 'Liegefläche im Bett'],
    ['Vase', 'Gefäss für Blumen'],
    ['Uhr', 'Gerät zur Zeitanzeige'],
    ['Wecker', 'Uhr, die morgens klingelt'],
    ['Kalender', 'Übersicht über die Tage'],

    ['Hemd', 'Oberteil mit Knöpfen'],
    ['Hose', 'Beinkleid'],
    ['Rock', 'Beinkleid ohne Beine'],
    ['Kleid', 'Einteiliges Damenkleidungsstück'],
    ['Jacke', 'Kleidung für draussen'],
    ['Mantel', 'Langer warmer Überzieher'],
    ['Pullover', 'Warmes Oberteil aus Wolle'],
    ['Weste', 'Ärmelloses Oberteil'],
    ['Anzug', 'Festliche Herrenkleidung'],
    ['Krawatte', 'Schlips zum Hemd'],
    ['Guertel', 'Band um die Hüfte'],
    ['Schal', 'Tuch um den Hals'],
    ['Muetze', 'Kopfbedeckung im Winter'],
    ['Hut', 'Kopfbedeckung mit Krempe'],
    ['Handschuh', 'Kleidung für die Hände'],
    ['Socke', 'Kleidung für den Fuss'],
    ['Schuh', 'Fussbekleidung'],
    ['Stiefel', 'Hoher Schuh'],
    ['Sandale', 'Offener Sommerschuh'],
    ['Turnschuh', 'Schuh für den Sport'],
    ['Knopf', 'Verschluss am Hemd'],
    ['Reissverschluss', 'Verschluss mit Zähnchen'],
    ['Tasche', 'Behältnis zum Tragen'],
    ['Rucksack', 'Tasche für den Rücken'],
    ['Koffer', 'Gepäckstück für die Reise'],
    ['Schirm', 'Schutz gegen Regen'],
    ['Brille', 'Sehhilfe auf der Nase'],
    ['Ring', 'Schmuck für den Finger'],
    ['Kette', 'Schmuck um den Hals'],
    ['Armband', 'Schmuck ums Handgelenk'],
    ['Ohrring', 'Schmuck am Ohr'],

    ['Seife', 'Mittel zum Waschen'],
    ['Shampoo', 'Mittel für die Haare'],
    ['Zahnbuerste', 'Gerät für die Zähne'],
    ['Zahnpasta', 'Paste für die Zähne'],
    ['Handtuch', 'Tuch zum Abtrocknen'],
    ['Dusche', 'Wo man sich abbraust'],
    ['Badewanne', 'Wanne zum Baden'],
    ['Kamm', 'Gerät für die Haare'],
    ['Rasierer', 'Gerät gegen den Bart'],
    ['Waschmaschine', 'Gerät für die Wäsche'],
    ['Buegeleisen', 'Gerät gegen Falten'],
    ['Staubsauger', 'Gerät gegen Schmutz'],
    ['Besen', 'Gerät zum Kehren'],
    ['Eimer', 'Gefäss zum Putzen'],
    ['Muelltonne', 'Behälter für Abfall'],

    ['Auto', 'Fahrzeug mit vier Rädern'],
    ['Fahrrad', 'Fahrzeug mit Pedalen'],
    ['Motorrad', 'Motorisiertes Zweirad'],
    ['Roller', 'Kleines Zweirad'],
    ['Bus', 'Öffentliches Strassenfahrzeug'],
    ['Zug', 'Fahrzeug auf Schienen'],
    ['Strassenbahn', 'Schienenfahrzeug in der Stadt'],
    ['Bahnhof', 'Haltestelle des Zuges'],
    ['Flugzeug', 'Fahrzeug in der Luft'],
    ['Hubschrauber', 'Fluggerät mit Rotor'],
    ['Schiff', 'Grosses Wasserfahrzeug'],
    ['Boot', 'Kleines Wasserfahrzeug'],
    ['Faehre', 'Schiff für die Überfahrt'],
    ['Anker', 'Was das Schiff hält'],
    ['Segel', 'Tuch für den Wind'],
    ['Ruder', 'Womit man ein Boot bewegt'],
    ['Motor', 'Antrieb eines Fahrzeugs'],
    ['Reifen', 'Gummi um das Rad'],
    ['Bremse', 'Was das Fahrzeug stoppt'],
    ['Lenkrad', 'Womit man das Auto steuert'],
    ['Tankstelle', 'Wo man Benzin bekommt'],
    ['Benzin', 'Kraftstoff für den Motor'],
    ['Ampel', 'Signal an der Kreuzung'],
    ['Kreuzung', 'Wo sich Strassen treffen'],
    ['Parkplatz', 'Abstellfläche für Autos'],
    ['Fahrplan', 'Übersicht der Abfahrtszeiten'],
    ['Fahrkarte', 'Ticket für den Bus'],
    ['Stau', 'Stockender Verkehr'],
    ['Umleitung', 'Ausweichstrecke'],

    ['Arbeit', 'Was man beruflich tut'],
    ['Beruf', 'Erlerntes Tätigkeitsfeld'],
    ['Buero', 'Arbeitsraum mit Schreibtisch'],
    ['Chef', 'Vorgesetzter im Betrieb'],
    ['Kollege', 'Mitarbeiter im Betrieb'],
    ['Lohn', 'Bezahlung für Arbeit'],
    ['Gehalt', 'Monatliche Bezahlung'],
    ['Urlaub', 'Freie Zeit vom Beruf'],
    ['Feierabend', 'Ende des Arbeitstags'],
    ['Termin', 'Verabredete Zeit'],
    ['Besprechung', 'Treffen zur Abstimmung'],
    ['Vertrag', 'Schriftliche Vereinbarung'],
    ['Rechnung', 'Aufforderung zu zahlen'],
    ['Quittung', 'Beleg über eine Zahlung'],
    ['Bank', 'Wo das Geld liegt'],
    ['Konto', 'Wo das Geld verbucht wird'],
    ['Muenze', 'Geld aus Metall'],
    ['Schein', 'Geld aus Papier'],
    ['Geldbeutel', 'Behältnis für das Bargeld'],
    ['Kasse', 'Wo man im Laden bezahlt'],
    ['Markt', 'Platz zum Handeln'],
    ['Laden', 'Geschäft zum Einkaufen'],
    ['Baeckerei', 'Laden für Brot'],
    ['Metzgerei', 'Laden für Fleisch'],
    ['Apotheke', 'Laden für Medikamente'],
    ['Post', 'Wo man Briefe aufgibt'],
    ['Brief', 'Nachricht im Umschlag'],
    ['Paket', 'Grössere Postsendung'],
    ['Marke', 'Was auf den Brief geklebt wird'],
    ['Werkzeug', 'Hilfsmittel zum Arbeiten'],
    ['Hammer', 'Werkzeug zum Schlagen'],
    ['Zange', 'Werkzeug zum Greifen'],
    ['Saege', 'Werkzeug zum Zerteilen'],
    ['Bohrer', 'Werkzeug für Löcher'],
    ['Schraube', 'Befestigung mit Gewinde'],
    ['Nagel', 'Befestigung zum Einschlagen'],
    ['Leiter', 'Hilfsmittel zum Hochsteigen'],
    ['Schaufel', 'Gerät zum Graben'],
    ['Harke', 'Gartengerät mit Zinken'],
    ['Giesskanne', 'Gefäss zum Blumengiessen'],
    ['Schlauch', 'Biegsames Rohr für Wasser']
  ]
}
