import type { Category } from './index'

export const kulturSport: Category = {
  id: 'kulturSport',
  label: 'Kultur & Sport',
  entries: [
    ['Fussball', 'Beliebteste Sportart der Welt'],
    ['Handball', 'Hallensport mit sieben Spielern'],
    ['Basketball', 'Sport mit Korb'],
    ['Volleyball', 'Sport über ein hohes Netz'],
    ['Tennis', 'Sport mit Schläger und Filzball'],
    ['Badminton', 'Sport mit Federball'],
    ['Tischtennis', 'Sport auf der grünen Platte'],
    ['Golf', 'Sport mit Loch und Schläger'],
    ['Hockey', 'Sport mit gebogenem Schläger'],
    ['Rugby', 'Sport mit eiförmigem Ball'],
    ['Baseball', 'Amerikanischer Schlagballsport'],
    ['Boxen', 'Kampfsport mit Handschuhen'],
    ['Judo', 'Japanischer Kampfsport'],
    ['Karate', 'Kampfsport mit Schlagtechniken'],
    ['Ringen', 'Zweikampf auf der Matte'],
    ['Fechten', 'Kampfsport mit dem Degen'],
    ['Turnen', 'Sport am Reck und Barren'],
    ['Leichtathletik', 'Laufen, Springen, Werfen'],
    ['Marathon', 'Lauf über 42 Kilometer'],
    ['Sprint', 'Kurzer schneller Lauf'],
    ['Staffel', 'Lauf mit Stabübergabe'],
    ['Hochsprung', 'Sprung über die Latte'],
    ['Weitsprung', 'Sprung in die Sandgrube'],
    ['Stabhochsprung', 'Sprung mit Stange'],
    ['Kugelstossen', 'Wurfdisziplin mit Metallkugel'],
    ['Speerwurf', 'Wurfdisziplin mit langem Gerät'],
    ['Diskus', 'Wurfscheibe der Leichtathletik'],
    ['Schwimmen', 'Sport im Wasser'],
    ['Tauchen', 'Sport unter Wasser'],
    ['Rudern', 'Sport im Boot mit Riemen'],
    ['Segeln', 'Sport mit Wind und Tuch'],
    ['Surfen', 'Sport auf der Welle'],
    ['Radfahren', 'Sport auf zwei Rädern'],
    ['Skifahren', 'Wintersport auf zwei Brettern'],
    ['Snowboard', 'Wintersport auf einem Brett'],
    ['Eislauf', 'Sport auf Kufen'],
    ['Eishockey', 'Schneller Sport auf dem Eis'],
    ['Rodeln', 'Sport mit dem Schlitten'],
    ['Biathlon', 'Langlauf mit Schiessen'],
    ['Klettern', 'Sport an der Wand'],
    ['Wandern', 'Längere Wanderung zu Fuss'],
    ['Reiten', 'Sport auf dem Pferd'],
    ['Bogenschiessen', 'Sport mit Pfeil und Bogen'],
    ['Kegeln', 'Sport mit neun Kegeln'],
    ['Bowling', 'Sport mit zehn Pins'],
    ['Dart', 'Wurfsport auf die Scheibe'],
    ['Billard', 'Spiel mit Queue und Kugeln'],
    ['Schach', 'Denkspiel mit König und Dame'],

    ['Tor', 'Treffer im Fussball'],
    ['Elfmeter', 'Strafstoss im Fussball'],
    ['Abseits', 'Regelverstoss im Fussball'],
    ['Eckball', 'Standard von der Fahne'],
    ['Freistoss', 'Ruhender Ball nach einem Foul'],
    ['Foul', 'Regelwidriges Spiel'],
    ['Schiedsrichter', 'Leiter des Spiels'],
    ['Torwart', 'Spieler im Kasten'],
    ['Stuermer', 'Angreifer im Fussball'],
    ['Verteidiger', 'Abwehrspieler'],
    ['Trainer', 'Leiter der Mannschaft'],
    ['Mannschaft', 'Gruppe von Sportlern'],
    ['Verein', 'Organisierter Zusammenschluss'],
    ['Liga', 'Spielklasse im Wettbewerb'],
    ['Pokal', 'Trophäe für den Sieger'],
    ['Medaille', 'Auszeichnung für Platzierte'],
    ['Olympia', 'Grösstes Sportfest der Welt'],
    ['Stadion', 'Grosse Sportstätte'],
    ['Halle', 'Überdachte Sportstätte'],
    ['Tribuene', 'Sitzreihen für Zuschauer'],
    ['Publikum', 'Die Zuschauer'],
    ['Rekord', 'Bestleistung'],
    ['Sieg', 'Erfolgreicher Ausgang'],
    ['Niederlage', 'Verlorenes Spiel'],
    ['Unentschieden', 'Spiel ohne Sieger'],
    ['Halbzeit', 'Pause im Fussballspiel'],
    ['Anpfiff', 'Beginn des Spiels'],
    ['Trikot', 'Sporthemd der Mannschaft'],
    ['Training', 'Übung für den Wettkampf'],
    ['Turnier', 'Wettbewerb mehrerer Teams'],
    ['Finale', 'Entscheidungsspiel'],
    ['Doping', 'Verbotene Leistungssteigerung'],

    ['Musik', 'Kunst der Töne'],
    ['Klavier', 'Tasteninstrument'],
    ['Fluegel', 'Grosses Klavier im Konzertsaal'],
    ['Geige', 'Streichinstrument mit vier Saiten'],
    ['Cello', 'Grosses Streichinstrument'],
    ['Kontrabass', 'Grösstes Streichinstrument'],
    ['Gitarre', 'Zupfinstrument mit sechs Saiten'],
    ['Harfe', 'Grosses Zupfinstrument'],
    ['Floete', 'Blasinstrument aus einem Rohr'],
    ['Klarinette', 'Holzblasinstrument'],
    ['Oboe', 'Holzblasinstrument mit Doppelrohr'],
    ['Fagott', 'Tiefes Holzblasinstrument'],
    ['Saxofon', 'Blasinstrument des Jazz'],
    ['Trompete', 'Helles Blechblasinstrument'],
    ['Posaune', 'Blechblasinstrument mit Zug'],
    ['Horn', 'Rundes Blechblasinstrument'],
    ['Tuba', 'Tiefstes Blechblasinstrument'],
    ['Schlagzeug', 'Instrument mit Trommeln'],
    ['Trommel', 'Schlaginstrument mit Fell'],
    ['Pauke', 'Grosse Kesseltrommel'],
    ['Becken', 'Metallteller im Schlagzeug'],
    ['Xylofon', 'Schlaginstrument mit Klanghölzern'],
    ['Orgel', 'Instrument mit Pfeifen in der Kirche'],
    ['Akkordeon', 'Handzuginstrument'],
    ['Mundharmonika', 'Kleines Blasinstrument'],
    ['Orchester', 'Grosses Musikensemble'],
    ['Chor', 'Gruppe von Sängern'],
    ['Dirigent', 'Leiter des Orchesters'],
    ['Solist', 'Einzelner Vortragender'],
    ['Melodie', 'Folge von Tönen'],
    ['Rhythmus', 'Zeitliche Gliederung der Musik'],
    ['Takt', 'Zeitmass der Musik'],
    ['Note', 'Zeichen für einen Ton'],
    ['Akkord', 'Mehrere Töne zugleich'],
    ['Tonleiter', 'Folge der Stufen'],
    ['Oktave', 'Abstand von acht Tönen'],
    ['Sinfonie', 'Grosses Orchesterwerk'],
    ['Sonate', 'Mehrsätziges Instrumentalwerk'],
    ['Konzert', 'Musikalische Aufführung'],
    ['Oper', 'Gesungenes Bühnenwerk'],
    ['Operette', 'Heitere Spielart der Oper'],
    ['Musical', 'Bühnenstück mit Songs und Tanz'],
    ['Ballett', 'Klassischer Bühnentanz'],
    ['Walzer', 'Tanz im Dreivierteltakt'],
    ['Tango', 'Leidenschaftlicher Tanz'],
    ['Samba', 'Brasilianischer Tanz'],
    ['Salsa', 'Lateinamerikanischer Tanz'],
    ['Jazz', 'Musikrichtung mit Improvisation'],
    ['Blues', 'Melancholische Musikrichtung'],
    ['Rock', 'Laute Gitarrenmusik'],
    ['Techno', 'Elektronische Tanzmusik'],
    ['Reggae', 'Musikrichtung aus Jamaika'],
    ['Schlager', 'Eingängige deutsche Popmusik'],
    ['Volkslied', 'Überliefertes Lied'],
    ['Refrain', 'Wiederkehrender Teil des Liedes'],
    ['Strophe', 'Abschnitt eines Liedes'],

    ['Theater', 'Bühne für Schauspiel'],
    ['Buehne', 'Wo gespielt wird'],
    ['Vorhang', 'Was sich zur Vorstellung hebt'],
    ['Kulisse', 'Bühnendekoration'],
    ['Applaus', 'Beifall des Publikums'],
    ['Premiere', 'Erste Aufführung'],
    ['Regisseur', 'Leiter der Inszenierung'],
    ['Schauspieler', 'Darsteller auf der Bühne'],
    ['Rolle', 'Figur, die gespielt wird'],
    ['Drama', 'Ernstes Bühnenstück'],
    ['Komoedie', 'Heiteres Bühnenstück'],
    ['Tragoedie', 'Stück mit unglücklichem Ausgang'],
    ['Kabarett', 'Politisch-satirische Kleinkunst'],
    ['Zirkus', 'Zelt mit Manege'],
    ['Clown', 'Spassmacher im Zirkus'],
    ['Akrobat', 'Künstler mit Körperbeherrschung'],
    ['Jongleur', 'Künstler, der Bälle wirft'],
    ['Zauberer', 'Künstler der Illusionen'],
    ['Marionette', 'Puppe an Fäden'],

    ['Kino', 'Ort für Filme'],
    ['Film', 'Bewegte Bilder'],
    ['Leinwand', 'Fläche für die Projektion'],
    ['Kamera', 'Gerät für Aufnahmen'],
    ['Szene', 'Abschnitt eines Films'],
    ['Drehbuch', 'Textvorlage des Films'],
    ['Trickfilm', 'Film aus gezeichneten Bildern'],
    ['Dokumentation', 'Sachlicher Film'],
    ['Krimi', 'Film oder Buch über ein Verbrechen'],
    ['Western', 'Film im wilden Westen'],
    ['Fernsehen', 'Bildschirmmedium im Wohnzimmer'],
    ['Sendung', 'Beitrag im Programm'],
    ['Nachrichten', 'Meldungen des Tages'],
    ['Werbung', 'Reklame im Programm'],
    ['Radio', 'Hörfunk'],
    ['Podcast', 'Hörbeitrag zum Abrufen'],

    ['Buch', 'Gebundene Blätter zum Lesen'],
    ['Roman', 'Längere erzählende Dichtung'],
    ['Erzaehlung', 'Kürzere Prosaform'],
    ['Maerchen', 'Erzählung mit Zauber'],
    ['Sage', 'Überlieferte Erzählung'],
    ['Fabel', 'Geschichte mit sprechenden Tieren'],
    ['Gedicht', 'Text in Versen'],
    ['Vers', 'Zeile eines Gedichts'],
    ['Reim', 'Gleichklang am Zeilenende'],
    ['Kapitel', 'Abschnitt eines Buches'],
    ['Seite', 'Blattseite im Buch'],
    ['Autor', 'Verfasser eines Textes'],
    ['Verlag', 'Betrieb, der Bücher herausgibt'],
    ['Bibliothek', 'Sammlung von Büchern'],
    ['Lexikon', 'Nachschlagewerk'],
    ['Zeitung', 'Tägliches Druckerzeugnis'],
    ['Zeitschrift', 'Regelmässig erscheinendes Heft'],
    ['Artikel', 'Beitrag in der Zeitung'],
    ['Schlagzeile', 'Grosse Überschrift'],
    ['Redaktion', 'Wo die Beiträge entstehen'],

    ['Museum', 'Haus für Sammlungen'],
    ['Galerie', 'Raum für Kunstausstellungen'],
    ['Gemaelde', 'Gemaltes Kunstwerk'],
    ['Skulptur', 'Plastisches Kunstwerk'],
    ['Statue', 'Standbild'],
    ['Pinsel', 'Werkzeug des Malers'],
    ['Palette', 'Brett für die Farben'],
    ['Staffelei', 'Gestell für die Leinwand'],
    ['Portraet', 'Bildnis eines Menschen'],
    ['Stillleben', 'Bild unbewegter Dinge'],
    ['Landschaft', 'Bildgattung der Natur'],
    ['Aquarell', 'Bild mit Wasserfarben'],
    ['Fresko', 'Wandmalerei auf feuchtem Putz'],
    ['Mosaik', 'Bild aus kleinen Steinchen'],
    ['Radierung', 'Druckgrafik von der Platte'],
    ['Karikatur', 'Übertreibende Zeichnung'],
    ['Comic', 'Bildergeschichte'],
    ['Fotografie', 'Lichtbild'],
    ['Architektur', 'Baukunst'],
    ['Kathedrale', 'Grosse Bischofskirche'],
    ['Dom', 'Grosse Hauptkirche'],
    ['Kirche', 'Christliches Gotteshaus'],
    ['Moschee', 'Islamisches Gotteshaus'],
    ['Synagoge', 'Jüdisches Gotteshaus'],
    ['Tempel', 'Heiliges Bauwerk'],
    ['Kloster', 'Wohnstätte von Mönchen'],
    ['Schloss', 'Prächtiger Herrschaftsbau'],
    ['Burg', 'Befestigter Wohnbau des Mittelalters'],
    ['Turm', 'Hohes schmales Bauwerk'],
    ['Saeule', 'Tragender runder Pfeiler'],
    ['Gewoelbe', 'Gebogene Decke'],
    ['Kuppel', 'Runde Dachform'],
    ['Fassade', 'Vorderseite eines Gebäudes'],
    ['Balkonbruestung', 'Geländer am Balkon'],
    ['Gotik', 'Baustil mit Spitzbogen'],
    ['Barock', 'Prunkvoller Baustil'],
    ['Renaissance', 'Stil der Wiedergeburt der Antike'],
    ['Romanik', 'Baustil mit Rundbogen'],

    ['Spiel', 'Zeitvertreib nach Regeln'],
    ['Karte', 'Blatt im Kartenspiel'],
    ['Wuerfel', 'Kubus mit Augen'],
    ['Puzzle', 'Bild aus vielen Teilen'],
    ['Raetsel', 'Aufgabe zum Knobeln'],
    ['Quiz', 'Spiel mit Wissensfragen'],
    ['Skat', 'Deutsches Kartenspiel zu dritt'],
    ['Poker', 'Kartenspiel mit Bluff'],
    ['Domino', 'Spiel mit Steinen'],
    ['Dame', 'Brettspiel auf 64 Feldern'],
    ['Mensch', 'Ärgere dich nicht'],
    ['Springer', 'Schachfigur, die im L zieht'],
    ['Laeufer', 'Schachfigur der Diagonalen'],
    ['Turm', 'Schachfigur der Geraden'],
    ['Bauer', 'Kleinste Schachfigur'],
    ['Koenig', 'Wichtigste Schachfigur'],
    ['Matt', 'Ende der Partie im Schach'],
    ['Patt', 'Unentschieden im Schach'],
    ['Trumpf', 'Höchste Farbe im Kartenspiel'],
    ['Joker', 'Karte mit freiem Wert'],
    ['Ass', 'Höchste Spielkarte'],
    ['Karo', 'Rote Kartenfarbe'],
    ['Pik', 'Schwarze Kartenfarbe'],
    ['Kreuz', 'Kartenfarbe, auch Treff'],
    ['Herz', 'Rote Kartenfarbe'],

    ['Fest', 'Feierlicher Anlass'],
    ['Feier', 'Gesellige Veranstaltung'],
    ['Geburtstag', 'Jährlicher Ehrentag'],
    ['Hochzeit', 'Fest der Eheschliessung'],
    ['Weihnachten', 'Fest der Geburt Christi'],
    ['Ostern', 'Fest der Auferstehung'],
    ['Pfingsten', 'Fest fünfzig Tage nach Ostern'],
    ['Silvester', 'Letzter Tag des Jahres'],
    ['Karneval', 'Fastnacht mit Umzügen'],
    ['Fasching', 'Andere Bezeichnung für Karneval'],
    ['Kostuem', 'Verkleidung zum Fasching'],
    ['Maske', 'Gesichtsverkleidung'],
    ['Konfetti', 'Bunte Papierschnipsel'],
    ['Feuerwerk', 'Buntes Leuchten am Nachthimmel'],
    ['Geschenk', 'Was man zum Fest bekommt'],
    ['Kerze', 'Wachslicht mit Docht'],
    ['Girlande', 'Schmuckband zum Fest'],
    ['Tanz', 'Bewegung zur Musik'],
    ['Ferien', 'Freie Zeit der Schüler'],
    ['Reise', 'Fahrt in die Fremde'],
    ['Hotel', 'Haus zum Übernachten'],
    ['Zelt', 'Unterkunft aus Stoff'],
    ['Camping', 'Urlaub im Zelt oder Wohnwagen'],
    ['Strand', 'Sandiger Uferbereich'],
    ['Souvenir', 'Andenken aus dem Urlaub'],
    ['Postkarte', 'Gruss aus dem Urlaub']
  ]
}
