import type { Category } from './index'

/**
 * Three-letter fillers. Dense German crosswords need a deep bench of these —
 * nearly every grid has a dozen 3-letter slots, and the six main categories
 * only supply about 40 between them.
 *
 * Every entry is exactly three letters after normaliseAnswer() expands umlauts,
 * so 'Öl' is spelled 'Oel' and 'Bö' is spelled 'Boe' here.
 */
export const kurz: Category = {
  id: 'kurz',
  label: 'Kurzwörter',
  entries: [
    ['Aal', 'Schlangenförmiger Fisch'],
    ['Aar', 'Alter Name für den Adler'],
    ['Aas', 'Verwesendes Fleisch'],
    ['Abt', 'Leiter eines Klosters'],
    ['Ach', 'Ausruf des Bedauerns'],
    ['Ade', 'Alter Abschiedsgruss'],
    ['Ahn', 'Vorfahre der Familie'],
    ['Air', 'Englisch für Luft'],
    ['Akt', 'Aufzug im Theaterstück'],
    ['Ale', 'Obergäriges englisches Bier'],
    ['All', 'Der Weltraum'],
    ['Alm', 'Bergweide in den Alpen'],
    ['Alp', 'Beklemmender Traum'],
    ['Alt', 'Tiefe Frauenstimme'],
    ['Amt', 'Behörde der Verwaltung'],
    ['Arm', 'Gliedmasse am Rumpf'],
    ['Art', 'Gattung, Sorte'],
    ['Ass', 'Höchste Spielkarte'],
    ['Ast', 'Zweig am Baumstamm'],
    ['Aue', 'Feuchte Wiese am Fluss'],
    ['Bad', 'Raum mit Wanne und Dusche'],
    ['Bai', 'Meeresbucht'],
    ['Bar', 'Lokal wo man was trinkt'],
    ['Bau', 'Wohnhöhle des Fuchses'],
    ['Bee', 'Englisch für Biene'],
    ['Beo', 'Sprechbegabter Singvogel'],
    ['Bet', 'Englisch für Wette'],
    ['Bio', 'Vorsilbe für ökologisch'],
    ['Bit', 'Kleinste Dateneinheit'],
    ['Boa', 'Grosse Würgeschlange'],
    ['Bob', 'Rennschlitten im Eiskanal'],
    ['Boe', 'Plötzlicher Windstoss'],
    ['Bub', 'Süddeutsch für Junge'],
    ['Bug', 'Vorderteil des Schiffes'],
    ['Bus', 'Öffentliches Strassenfahrzeug'],
    ['Che', 'Vorname des Revolutionärs Guevara'],
    ['Chi', 'Griechischer Buchstabe'],
    ['Cup', 'Englisch für Pokal'],
    ['Dax', 'Deutscher Aktienindex'],
    ['Dia', 'Lichtbild zum Projizieren'],
    ['Dip', 'Sauce zum Eintunken'],
    ['Dom', 'Grosse Bischofskirche'],
    ['Duo', 'Gruppe aus zwei Personen'],
    ['Dur', 'Fröhliche Tonart'],
    ['Eck', 'Kurzform für die Ecke'],
    ['Ehe', 'Rechtliche Verbindung zweier Menschen'],
    ['Eid', 'Feierliches Versprechen'],
    ['Eis', 'Kalte Süssspeise in der Waffel'],
    ['Elf', 'Zahl der Spieler einer Mannschaft'],
    ['Emu', 'Australischer Laufvogel'],
    ['Eng', 'Nicht weit'],
    ['Erz', 'Metallhaltiges Gestein'],
    ['Eta', 'Griechischer Buchstabe'],
    ['Eva', 'Erste Frau der Bibel'],
    ['Fad', 'Ohne rechten Geschmack'],
    ['Fee', 'Gute Zaubergestalt'],
    ['Fen', 'Englisch für Moor'],
    ['Fes', 'Rote Kopfbedeckung ohne Krempe'],
    ['Fis', 'Erhöhtes F in der Musik'],
    ['Fix', 'Feststehend, unveränderlich'],
    ['Fon', 'Einheit der Lautstärke'],
    ['Fun', 'Englisch für Spass'],
    ['Gag', 'Witziger Einfall im Film'],
    ['Gas', 'Luftförmiger Stoff'],
    ['Gau', 'Altes Verwaltungsgebiet'],
    ['Gel', 'Zähflüssiges Haarprodukt'],
    ['Gen', 'Träger der Erbanlage'],
    ['Gin', 'Wacholderschnaps'],
    ['Gnu', 'Afrikanische Antilope'],
    ['Gut', 'Landwirtschaftlicher Grossbetrieb'],
    ['Hai', 'Raubfisch im Meer'],
    ['Ham', 'Englisch für Schinken'],
    ['Hem', 'Englisch für Saum'],
    ['Heu', 'Getrocknetes Gras'],
    ['Hit', 'Erfolgreiches Musikstück'],
    ['Hof', 'Innenbereich eines Gebäudes'],
    ['Hut', 'Kopfbedeckung mit Krempe'],
    ['Ich', 'Erste Person Singular'],
    ['Ida', 'Weiblicher Vorname'],
    ['Ion', 'Elektrisch geladenes Teilchen'],
    ['Ire', 'Bewohner der grünen Insel'],
    ['Jab', 'Gerader Schlag beim Boxen'],
    ['Jet', 'Schnelles Düsenflugzeug'],
    ['Job', 'Bezahlte Arbeit'],
    ['Jod', 'Element im Speisesalz'],
    ['Jus', 'Bratensaft'],
    ['Kai', 'Uferbefestigung im Hafen'],
    ['Kap', 'Vorsprung an der Küste'],
    ['Kea', 'Neuseeländischer Bergpapagei'],
    ['Keg', 'Englisch für Fässchen'],
    ['Kfz', 'Abkürzung für Kraftfahrzeug'],
    ['Kir', 'Aperitif mit Johannisbeerlikör'],
    ['Kit', 'Bausatz, Zusammenstellung'],
    ['Koi', 'Bunter Zierkarpfen'],
    ['Kot', 'Ausscheidung des Darms'],
    ['Kuh', 'Weibliches Rind'],
    ['Kur', 'Heilaufenthalt im Bad'],
    ['Lad', 'Englisch für Bursche'],
    ['Lag', 'Verzögerung im Netz'],
    ['Lee', 'Windabgewandte Schiffsseite'],
    ['Leg', 'Abschnitt eines Dartspiels'],
    ['Lei', 'Hawaiianischer Blumenkranz'],
    ['Lid', 'Hautfalte über dem Auge'],
    ['Lob', 'Anerkennende Worte'],
    ['Los', 'Zettel bei der Ziehung'],
    ['Lot', 'Senkblei des Maurers'],
    ['Luv', 'Dem Wind zugewandte Seite'],
    ['Lux', 'Einheit der Beleuchtungsstärke'],
    ['Mac', 'Rechner von Apple'],
    ['Mai', 'Fünfter Monat des Jahres'],
    ['Mal', 'Zeitpunkt, Gelegenheit'],
    ['Man', 'Insel in der Irischen See'],
    ['Map', 'Englisch für Landkarte'],
    ['Met', 'Honigwein der Germanen'],
    ['Mob', 'Aufgebrachte Menschenmenge'],
    ['Mol', 'Einheit der Stoffmenge'],
    ['Mop', 'Gerät zum Bodenwischen'],
    ['Mud', 'Englisch für Schlamm'],
    ['Mus', 'Brei aus Obst'],
    ['Mut', 'Tapferkeit vor der Gefahr'],
    ['Nag', 'Englisch für Klepper'],
    ['Nap', 'Englisch für Nickerchen'],
    ['Neu', 'Noch nicht gebraucht'],
    ['Nil', 'Längster Fluss Afrikas'],
    ['Nix', 'Umgangssprachlich für nichts'],
    ['Nok', 'Norwegische Währung (Kürzel)'],
    ['Not', 'Grosse Bedrängnis'],
    ['Nut', 'Rille im Holz'],
    ['Ode', 'Feierliches Gedicht'],
    ['Oel', 'Schmierstoff im Motor'],
    ['Ohm', 'Einheit des Widerstands'],
    ['Ohr', 'Organ des Hörens'],
    ['Oma', 'Mutter der Mutter'],
    ['Opa', 'Vater des Vaters'],
    ['Ort', 'Bestimmte Stelle'],
    ['Ost', 'Richtung des Sonnenaufgangs'],
    ['Pad', 'Englisch für Polster'],
    ['Pan', 'Griechischer Hirtengott'],
    ['Pas', 'Schritt beim Ballett'],
    ['Pat', 'Unentschieden im Schach (Kurzform)'],
    ['Pik', 'Schwarze Kartenfarbe'],
    ['Pin', 'Geheimzahl der Bankkarte'],
    ['Pit', 'Boxengasse im Rennsport'],
    ['Pol', 'Ende der Erdachse'],
    ['Pop', 'Populäre Musikrichtung'],
    ['Pot', 'Einsatz beim Poker'],
    ['Pro', 'Für, dafür'],
    ['Pub', 'Englische Schankwirtschaft'],
    ['Pur', 'Unvermischt, rein'],
    ['Rad', 'Rundes Teil am Fahrzeug'],
    ['Rah', 'Querstange am Schiffsmast'],
    ['Ram', 'Arbeitsspeicher des Rechners'],
    ['Rap', 'Rhythmischer Sprechgesang'],
    ['Rat', 'Guter Hinweis'],
    ['Ray', 'Englisch für Strahl'],
    ['Reh', 'Scheues Waldtier'],
    ['Ren', 'Nordisches Hirschtier'],
    ['Rex', 'Latein für König'],
    ['Rho', 'Griechischer Buchstabe'],
    ['Rio', 'Stadt am Zuckerhut'],
    ['Rip', 'Englisch für Riss'],
    ['Rom', 'Hauptstadt von Italien'],
    ['Rot', 'Farbe des Blutes'],
    ['Ruf', 'Laut zum Herbeiholen'],
    ['Rum', 'Spirituose aus Zuckerrohr'],
    ['Run', 'Grosser Ansturm'],
    ['Sau', 'Weibliches Schwein'],
    ['Sax', 'Kurzform für Saxofon'],
    ['See', 'Stehendes Binnengewässer'],
    ['Set', 'Zusammengehörige Gruppe'],
    ['Sex', 'Geschlechtlicher Verkehr'],
    ['Sim', 'Karte im Mobiltelefon'],
    ['Ski', 'Brett für den Schnee'],
    ['Sog', 'Ziehende Strömung'],
    ['Sol', 'Römischer Sonnengott'],
    ['Sos', 'Internationaler Notruf'],
    ['Sud', 'Flüssigkeit vom Kochen'],
    ['Tag', 'Zeit von Sonnenaufgang bis Untergang'],
    ['Tal', 'Senke zwischen Bergen'],
    ['Tao', 'Chinesische Lehre vom Weg'],
    ['Tat', 'Ausgeführte Handlung'],
    ['Tau', 'Feuchtigkeit am Morgen'],
    ['Tee', 'Heissgetränk aus Blättern'],
    ['Ten', 'Englisch für zehn'],
    ['Tic', 'Nervöse Zuckung'],
    ['Tip', 'Nützlicher Hinweis'],
    ['Ton', 'Hörbarer Klang'],
    ['Top', 'Kurzes Oberteil'],
    ['Tor', 'Grosse Eingangsöffnung'],
    ['Tot', 'Nicht mehr lebendig'],
    ['Uhr', 'Gerät zur Zeitanzeige'],
    ['Uhu', 'Grosse Eule mit Federohren'],
    ['Ulm', 'Stadt mit dem höchsten Kirchturm'],
    ['Uni', 'Kurzform für Hochschule'],
    ['Van', 'Geräumiger Personenwagen'],
    ['Vet', 'Kurzform für Tierarzt'],
    ['Via', 'Über, auf dem Weg durch'],
    ['Wal', 'Grösstes Meeressäugetier'],
    ['Weg', 'Strecke zum Gehen'],
    ['Wut', 'Heftiger Zorn'],
    ['Yak', 'Rind im Hochland Tibets'],
    ['Yen', 'Währung in Japan'],
    ['Zar', 'Russischer Kaiser'],
    ['Zeh', 'Glied am Fuss'],
    ['Zen', 'Meditative Richtung des Buddhismus'],
    ['Zoo', 'Tierpark'],
    ['Zug', 'Fahrzeug auf Schienen'],
  ],
}
