import type { Category } from './index'

/**
 * Fills the buckets a dense grid actually drains.
 *
 * Measured over the shipped set: two-letter answers were needed 713 times from
 * only 89 words (8x each) and four-letter ones 962 times from 359 (3.2x each),
 * while five letters and up barely repeated. Long words do nothing for that —
 * this file targets 2, 3 and 4 letters.
 */
export const mehr: Category = {
  id: 'mehr',
  label: 'Weitere Kurzwörter',
  entries: [
    // ── 2 letters: chemical symbols ────────────────────────────────────────
    ['As', 'Chemisches Zeichen für Arsen'],
    ['At', 'Chemisches Zeichen für Astat'],
    ['Bi', 'Chemisches Zeichen für Bismut'],
    ['Cs', 'Chemisches Zeichen für Caesium'],
    ['Ga', 'Chemisches Zeichen für Gallium'],
    ['Gd', 'Chemisches Zeichen für Gadolinium'],
    ['Ge', 'Chemisches Zeichen für Germanium'],
    ['Hf', 'Chemisches Zeichen für Hafnium'],
    ['Ho', 'Chemisches Zeichen für Holmium'],
    ['Lu', 'Chemisches Zeichen für Lutetium'],
    ['Nd', 'Chemisches Zeichen für Neodym'],
    ['Np', 'Chemisches Zeichen für Neptunium'],
    ['Pr', 'Chemisches Zeichen für Praseodym'],
    ['Ra', 'Chemisches Zeichen für Radium'],
    ['Rb', 'Chemisches Zeichen für Rubidium'],
    ['Rn', 'Chemisches Zeichen für Radon'],
    ['Sb', 'Chemisches Zeichen für Antimon'],
    ['Sc', 'Chemisches Zeichen für Scandium'],
    ['Se', 'Chemisches Zeichen für Selen'],
    ['Sm', 'Chemisches Zeichen für Samarium'],
    ['Tb', 'Chemisches Zeichen für Terbium'],
    ['Tc', 'Chemisches Zeichen für Technetium'],
    ['Te', 'Chemisches Zeichen für Tellur'],
    ['Th', 'Chemisches Zeichen für Thorium'],
    ['Tl', 'Chemisches Zeichen für Thallium'],
    ['Tm', 'Chemisches Zeichen für Thulium'],
    ['Yb', 'Chemisches Zeichen für Ytterbium'],

    // ── 2 letters: Greek letters, units, everyday ─────────────────────────
    ['My', 'Griechischer Buchstabe'],
    ['Ny', 'Griechischer Buchstabe'],
    ['Xi', 'Griechischer Buchstabe'],
    ['Pi', 'Kreiszahl der Mathematik'],
    ['Ha', 'Kurzzeichen für Hektar'],
    ['Pa', 'Kurzzeichen für Pascal'],
    ['Eh', 'Umgangssprachlich für sowieso'],
    ['Ex', 'Früherer Partner'],
    ['Ai', 'Südamerikanisches Faultier'],
    ['Ut', 'Alter Name für den Ton C'],

    // ── 3 letters ─────────────────────────────────────────────────────────
    ['Aha', 'Ausruf der Einsicht'],
    ['Alb', 'Mittelgebirge in Baden-Württemberg'],
    ['App', 'Programm für das Handy'],
    ['Ara', 'Bunter Papagei Südamerikas'],
    ['Ave', 'Beginn eines Mariengebets'],
    ['Bon', 'Kassenzettel'],
    ['Cis', 'Halbton über dem C'],
    ['Des', 'Halbton unter dem D'],
    ['Ekg', 'Untersuchung des Herzens'],
    ['Ems', 'Fluss in Niedersachsen'],
    ['Eos', 'Griechische Göttin der Morgenröte'],
    ['Fan', 'Begeisterter Anhänger'],
    ['Fit', 'In guter körperlicher Form'],
    ['Goa', 'Küstenstaat in Indien'],
    ['Hag', 'Hecke als Einfriedung'],
    ['Hui', 'Ausruf bei Schwung'],
    ['Ill', 'Fluss in Vorarlberg'],
    ['Inn', 'Nebenfluss der Donau'],
    ['Jot', 'Der Buchstabe J'],
    ['Jux', 'Übermütiger Scherz'],
    ['Kat', 'Abgasreiniger im Auto (Kurzform)'],
    ['Lab', 'Enzym für die Käseherstellung'],
    ['Lan', 'Lokales Rechnernetz'],
    ['Lax', 'Nachlässig, lässig'],
    ['Lev', 'Währung in Bulgarien'],
    ['Log', 'Tagebuch des Schiffes'],
    ['Lok', 'Zugmaschine der Bahn'],
    ['Mix', 'Mischung'],
    ['Moa', 'Ausgestorbener Riesenvogel'],
    ['Obi', 'Gürtel des Kimonos'],
    ['Orf', 'Rundfunk in Österreich'],
    ['Pep', 'Schwung, Elan'],
    ['Phi', 'Griechischer Buchstabe'],
    ['Plz', 'Kennzahl der Post'],
    ['Psi', 'Griechischer Buchstabe'],
    ['Roh', 'Noch unbearbeitet'],
    ['Spa', 'Bad zur Erholung'],
    ['Tod', 'Ende des Lebens'],
    ['Typ', 'Art, Sorte'],
    ['Ufo', 'Unbekanntes Flugobjekt'],
    ['Uri', 'Kanton der Zentralschweiz'],
    ['Usa', 'Staat in Nordamerika (Kürzel)'],
    ['Vip', 'Besonders wichtige Person'],
    ['Wok', 'Asiatische Pfanne'],
    ['Yin', 'Weibliches Prinzip im Taoismus'],

    // ── 4 letters ─────────────────────────────────────────────────────────
    ['Acht', 'Zahl zwischen sieben und neun'],
    ['Agil', 'Beweglich, flink'],
    ['Akut', 'Dringlich, plötzlich auftretend'],
    ['Amen', 'Schlusswort des Gebets'],
    ['Amor', 'Römischer Liebesgott'],
    ['Anno', 'Im Jahre'],
    ['Arie', 'Gesangsstück in der Oper'],
    ['Aula', 'Festsaal der Schule'],
    ['Axel', 'Sprung im Eiskunstlauf'],
    ['Baby', 'Neugeborenes Kind'],
    ['Bake', 'Seezeichen zur Orientierung'],
    ['Balz', 'Werbeverhalten der Vögel'],
    ['Bann', 'Ausschluss aus der Kirche'],
    ['Base', 'Gegenspieler der Säure'],
    ['Bock', 'Männliche Ziege'],
    ['Boje', 'Schwimmendes Zeichen im Wasser'],
    ['Bonn', 'Frühere Hauptstadt am Rhein'],
    ['Brei', 'Dickflüssige Speise'],
    ['Bund', 'Zusammenschluss, Vereinigung'],
    ['Butt', 'Plattfisch der Nordsee'],
    ['Byte', 'Dateneinheit aus acht Bit'],
    ['Cent', 'Hundertstel Euro'],
    ['Chip', 'Bauteil im Rechner'],
    ['Clan', 'Sippe, Grossfamilie'],
    ['Code', 'Geheime Zeichenschrift'],
    ['Deck', 'Boden auf dem Schiff'],
    ['Dill', 'Kraut für den Gurkensalat'],
    ['Diva', 'Gefeierte Sängerin'],
    ['Dock', 'Anlage zur Schiffsreparatur'],
    ['Doge', 'Einstiger Herrscher Venedigs'],
    ['Eber', 'Männliches Schwein'],
    ['Edel', 'Vornehm, hochwertig'],
    ['Egel', 'Blutsaugender Wurm'],
    ['Esel', 'Graues Lasttier'],
    ['Etat', 'Haushaltsplan'],
    ['Fakt', 'Feststehende Tatsache'],
    ['Fall', 'Sturz nach unten'],
    ['Faun', 'Waldgeist der Antike'],
    ['Feld', 'Bestellter Acker'],
    ['Fett', 'Streichbares Speisefett'],
    ['Flug', 'Reise im Flugzeug'],
    ['Flut', 'Hoher Wasserstand am Meer'],
    ['Frau', 'Weibliche erwachsene Person'],
    ['Fuss', 'Körperteil unten am Bein'],
    ['Gala', 'Festliche Veranstaltung'],
    ['Gaul', 'Pferd, abwertend gesagt'],
    ['Geiz', 'Übertriebene Sparsamkeit'],
    ['Geld', 'Mittel zum Bezahlen'],
    ['Gier', 'Maßloses Verlangen'],
    ['Gift', 'Schädlicher Stoff'],
    ['Glut', 'Heiss glimmende Asche'],
    ['Gnom', 'Zwerg der Sage'],
    ['Gram', 'Tiefer Kummer'],
    ['Guss', 'Das Giessen von Metall'],
    ['Habe', 'Gesamter Besitz'],
    ['Hain', 'Kleines Waldstück'],
    ['Harn', 'Ausscheidung der Niere'],
    ['Heer', 'Landstreitkräfte'],
    ['Heil', 'Wohlergehen, Rettung'],
    ['Hort', 'Verborgener Schatz'],
    ['Ibis', 'Stelzvogel mit langem Schnabel'],
    ['Idol', 'Verehrtes Vorbild'],
    ['Iglu', 'Rundes Haus aus Schnee'],
    ['Imam', 'Islamischer Vorbeter'],
    ['Inka', 'Altes Volk in Peru'],
    ['Irak', 'Staat am Persischen Golf'],
    ['Iran', 'Staat in Vorderasien'],
    ['Jade', 'Grüner Schmuckstein'],
    ['Jagd', 'Verfolgung von Wild'],
    ['Jute', 'Faserpflanze für Säcke'],
    ['Kadi', 'Richter, umgangssprachlich'],
    ['Kaki', 'Orangefarbene Südfrucht'],
    ['Keil', 'Werkzeug zum Spalten'],
    ['Kiez', 'Stadtviertel in Berlin'],
    ['Koma', 'Tiefe Bewusstlosigkeit'],
    ['Kopf', 'Oberster Teil des Körpers'],
    ['Kult', 'Verehrung mit festen Riten'],
    ['Kurs', 'Fahrtrichtung des Schiffes'],
    ['Laib', 'Runde Form des Brotes'],
    ['Leib', 'Körper des Menschen'],
    ['Lenz', 'Dichterisch für Frühling'],
    ['List', 'Schlauer Kunstgriff'],
    ['Loge', 'Abgetrennter Platz im Theater'],
    ['Lord', 'Englischer Adelstitel'],
    ['Luke', 'Öffnung im Schiffsdeck'],
    ['Lust', 'Starkes Verlangen'],
    ['Maat', 'Unteroffizier zur See'],
    ['Mahl', 'Festliches Essen'],
    ['Malz', 'Braustoff aus Getreide'],
    ['Mass', 'Einheit zum Messen'],
    ['Maul', 'Mund des Tieres'],
    ['Mist', 'Dung auf dem Acker'],
    ['Napf', 'Schale für das Tierfutter'],
    ['Narr', 'Spassmacher am Hof'],
    ['Neon', 'Gas in Leuchtröhren'],
    ['Nerz', 'Pelztier am Wasser'],
    ['Neun', 'Zahl vor der Zehn'],
    ['Nord', 'Richtung zum Polarstern'],
    ['Norm', 'Verbindliche Regel'],
    ['Nuss', 'Frucht mit harter Schale'],
    ['Omen', 'Vorzeichen kommender Dinge'],
    ['Onyx', 'Dunkler Halbedelstein'],
    ['Opal', 'Schillernder Schmuckstein'],
    ['Opus', 'Werk eines Künstlers'],
    ['Pakt', 'Bündnis zwischen Staaten'],
    ['Part', 'Anteil, Rolle im Stück'],
    ['Pfad', 'Schmaler Weg'],
    ['Pier', 'Landungsbrücke im Hafen'],
    ['Plan', 'Durchdachtes Vorhaben'],
    ['Polo', 'Ballspiel auf Pferden'],
    ['Pore', 'Winzige Öffnung der Haut'],
    ['Putz', 'Bewurf auf der Wand'],
    ['Qual', 'Grosses körperliches Leid'],
    ['Rahm', 'Fetter Teil der Milch'],
    ['Rate', 'Teilbetrag einer Zahlung'],
    ['Ried', 'Schilfgras am Ufer'],
    ['Rind', 'Nutztier auf der Weide'],
    ['Ruhm', 'Hohes Ansehen'],
    ['Russ', 'Schwarzer Rückstand im Kamin'],
    ['Saat', 'Ausgestreute Körner'],
    ['Samt', 'Weicher glänzender Stoff'],
    ['Saum', 'Umgenähter Rand'],
    ['Silo', 'Speicher für Getreide'],
    ['Soll', 'Gegenstück zum Haben'],
    ['Span', 'Splitter vom Holz'],
    ['Spur', 'Fährte im Schnee'],
    ['Steg', 'Schmaler Übergang'],
    ['Stil', 'Art der Gestaltung'],
    ['Tabu', 'Verbotenes Gesprächsthema'],
    ['Teer', 'Schwarze Masse für Strassen'],
    ['Toga', 'Gewand der alten Römer'],
    ['Trab', 'Mittlere Gangart des Pferdes'],
    ['Tram', 'Strassenbahn'],
    ['Trio', 'Gruppe aus drei Personen'],
    ['Trog', 'Behälter für das Futter'],
    ['Tube', 'Behälter für Zahnpasta'],
    ['Urin', 'Harn'],
    ['Urne', 'Behälter für die Asche'],
    ['Veto', 'Förmlicher Einspruch'],
    ['Vier', 'Zahl zwischen drei und fünf'],
    ['Vogt', 'Verwalter im Mittelalter'],
    ['Volk', 'Bevölkerung eines Landes'],
    ['Volt', 'Einheit der Spannung'],
    ['Wabe', 'Zelle im Bienenstock'],
    ['Wade', 'Muskel am Unterschenkel'],
    ['Wahn', 'Krankhafte Vorstellung'],
    ['Wehr', 'Staustufe im Fluss'],
    ['Wild', 'Jagdbare Tiere im Wald'],
    ['Wirt', 'Gastgeber im Lokal'],
    ['Woge', 'Grosse Welle'],
    ['Wurf', 'Das Werfen des Balls'],
    ['Zehn', 'Zahl nach der Neun'],
    ['Zopf', 'Geflochtenes Haar'],
    ['Zwei', 'Zahl zwischen eins und drei'],
  ],
}
