import type { Category } from './index'

export const natur: Category = {
  id: 'natur',
  label: 'Natur & Tiere',
  entries: [
    ['Loewe', 'König der Tiere'],
    ['Tiger', 'Grösste Raubkatze'],
    ['Leopard', 'Gefleckte Raubkatze'],
    ['Gepard', 'Schnellstes Landtier'],
    ['Luchs', 'Wildkatze mit Pinselohren'],
    ['Puma', 'Amerikanische Raubkatze'],
    ['Jaguar', 'Raubkatze Südamerikas'],
    ['Elefant', 'Grösstes Landtier'],
    ['Nashorn', 'Dickhäuter mit Horn'],
    ['Nilpferd', 'Schwerer Fluss-Dickhäuter'],
    ['Giraffe', 'Tier mit dem längsten Hals'],
    ['Zebra', 'Gestreiftes Steppenpferd'],
    ['Gnu', 'Afrikanische Antilope'],
    ['Antilope', 'Flinker Huftier der Savanne'],
    ['Gazelle', 'Zierliche Antilope'],
    ['Bueffel', 'Wildes Rind'],
    ['Kamel', 'Wüstenschiff mit zwei Höckern'],
    ['Dromedar', 'Kamel mit einem Höcker'],
    ['Lama', 'Südamerikanisches Kamelartiges'],
    ['Alpaka', 'Wolliges Tier aus den Anden'],
    ['Baer', 'Grosses Raubtier mit Winterruhe'],
    ['Eisbaer', 'Weisser Bär der Arktis'],
    ['Panda', 'Bambus fressender Bär'],
    ['Wolf', 'Vorfahre des Hundes'],
    ['Fuchs', 'Schlaues rotes Raubtier'],
    ['Dachs', 'Nachtaktives Tier mit gestreiftem Kopf'],
    ['Marder', 'Flinkes Raubtier auf dem Dachboden'],
    ['Otter', 'Schwimmendes Raubtier am Fluss'],
    ['Biber', 'Nagetier, das Dämme baut'],
    ['Igel', 'Stacheliges Gartentier'],
    ['Maulwurf', 'Grabendes Tier mit Erdhaufen'],
    ['Eichhoernchen', 'Nager mit buschigem Schwanz'],
    ['Hamster', 'Nager mit Backentaschen'],
    ['Maus', 'Kleiner grauer Nager'],
    ['Ratte', 'Grösserer Nager der Kanalisation'],
    ['Hase', 'Tier mit langen Löffeln'],
    ['Kaninchen', 'Kleiner Verwandter des Hasen'],
    ['Reh', 'Zierliches Waldtier'],
    ['Hirsch', 'Waldtier mit Geweih'],
    ['Elch', 'Grösster Hirsch'],
    ['Rentier', 'Zugtier des Weihnachtsmanns'],
    ['Wildschwein', 'Borstentier des Waldes'],
    ['Fledermaus', 'Fliegendes Säugetier'],
    ['Affe', 'Kletternder Primat'],
    ['Gorilla', 'Grösster Menschenaffe'],
    ['Schimpanse', 'Naher Verwandter des Menschen'],
    ['Orangutan', 'Roter Menschenaffe aus Borneo'],
    ['Faultier', 'Sehr langsames Baumtier'],
    ['Kaenguru', 'Springendes Beuteltier'],
    ['Koala', 'Eukalyptus fressendes Beuteltier'],
    ['Wal', 'Grösstes Tier der Erde'],
    ['Delfin', 'Kluges Meeressäugetier'],
    ['Robbe', 'Meeressäuger am Strand'],
    ['Seehund', 'Robbe der Nordsee'],
    ['Walross', 'Robbe mit langen Stosszähnen'],
    ['Pinguin', 'Flugunfähiger Vogel der Antarktis'],

    ['Adler', 'Grosser Greifvogel im Wappen'],
    ['Falke', 'Schneller Greifvogel'],
    ['Bussard', 'Häufiger Greifvogel über Feldern'],
    ['Habicht', 'Greifvogel des Waldes'],
    ['Eule', 'Nachtaktiver Vogel'],
    ['Uhu', 'Grösste Eule'],
    ['Kauz', 'Kleine Eule'],
    ['Storch', 'Vogel, der angeblich Kinder bringt'],
    ['Reiher', 'Langbeiniger Vogel am Wasser'],
    ['Kranich', 'Grosser Zugvogel mit Trompetenruf'],
    ['Schwan', 'Weisser Wasservogel'],
    ['Ente', 'Watschelnder Wasservogel'],
    ['Gans', 'Grösserer Wasservogel'],
    ['Moewe', 'Vogel der Küste'],
    ['Spatz', 'Häufiger kleiner Stadtvogel'],
    ['Amsel', 'Schwarzer Singvogel mit gelbem Schnabel'],
    ['Meise', 'Kleiner Vogel am Futterhaus'],
    ['Fink', 'Singvogel mit kräftigem Schnabel'],
    ['Drossel', 'Singvogel mit gefleckter Brust'],
    ['Star', 'Schwarm bildender Singvogel'],
    ['Schwalbe', 'Vogel, der den Sommer bringt'],
    ['Specht', 'Vogel, der ans Holz klopft'],
    ['Kuckuck', 'Vogel, der fremde Nester nutzt'],
    ['Rabe', 'Kluger schwarzer Vogel'],
    ['Kraehe', 'Schwarzer Vogel auf dem Feld'],
    ['Elster', 'Schwarzweisser Vogel, gilt als diebisch'],
    ['Taube', 'Vogel des Friedens'],
    ['Papagei', 'Bunter Vogel, der spricht'],
    ['Strauss', 'Grösster Vogel der Welt'],
    ['Pfau', 'Vogel mit prächtigem Rad'],
    ['Flamingo', 'Rosa Vogel auf einem Bein'],
    ['Kolibri', 'Kleinster Vogel, schwirrt vor Blüten'],
    ['Huhn', 'Vogel, der Eier legt'],
    ['Hahn', 'Männliches Huhn'],
    ['Truthahn', 'Vogel des Erntedankfests'],

    ['Hai', 'Gefürchteter Raubfisch'],
    ['Rochen', 'Flacher Meeresfisch'],
    ['Lachs', 'Fisch, der flussaufwärts wandert'],
    ['Forelle', 'Fisch klarer Bäche'],
    ['Karpfen', 'Teichfisch, oft an Weihnachten'],
    ['Hecht', 'Raubfisch der Seen'],
    ['Barsch', 'Gestreifter Raubfisch'],
    ['Aal', 'Schlangenförmiger Fisch'],
    ['Hering', 'Häufiger Schwarmfisch der Nordsee'],
    ['Thunfisch', 'Grosser Speisefisch aus der Dose'],
    ['Dorsch', 'Ostseefisch, auch Kabeljau'],
    ['Scholle', 'Platter Speisefisch'],
    ['Krebs', 'Panzertier mit Scheren'],
    ['Hummer', 'Edler Meereskrebs'],
    ['Garnele', 'Kleines Krustentier'],
    ['Krabbe', 'Seitwärts laufendes Krustentier'],
    ['Muschel', 'Weichtier mit zwei Schalen'],
    ['Auster', 'Delikate Muschel'],
    ['Tintenfisch', 'Weichtier mit acht Armen'],
    ['Krake', 'Achtarmiger Meeresbewohner'],
    ['Qualle', 'Glibberiges Nesseltier'],
    ['Seestern', 'Fünfarmiger Meeresbewohner'],
    ['Koralle', 'Aufbauer tropischer Riffe'],
    ['Seeigel', 'Stacheliges Meerestier'],

    ['Schlange', 'Beinloses Kriechtier'],
    ['Kobra', 'Giftschlange mit Nackenschild'],
    ['Viper', 'Europäische Giftschlange'],
    ['Python', 'Riesenschlange, die erdrückt'],
    ['Krokodil', 'Gepanzertes Reptil im Fluss'],
    ['Alligator', 'Krokodilart Amerikas'],
    ['Eidechse', 'Flinkes kleines Reptil'],
    ['Gecko', 'Kletterreptil mit Haftzehen'],
    ['Chamaeleon', 'Reptil, das die Farbe wechselt'],
    ['Leguan', 'Grosse Echse mit Kamm'],
    ['Schildkroete', 'Reptil mit Panzer'],
    ['Frosch', 'Quakender Lurch'],
    ['Kroete', 'Warziger Lurch'],
    ['Molch', 'Wasserlurch mit Schwanz'],
    ['Salamander', 'Schwarzgelber Lurch'],
    ['Kaulquappe', 'Larve des Frosches'],

    ['Biene', 'Insekt, das Honig macht'],
    ['Wespe', 'Gelbschwarzes stechendes Insekt'],
    ['Hummel', 'Dick behaartes Blüteninsekt'],
    ['Hornisse', 'Grösste heimische Wespe'],
    ['Ameise', 'Fleissiges staatenbildendes Insekt'],
    ['Termite', 'Insekt, das Hügel baut'],
    ['Schmetterling', 'Buntes Insekt aus der Raupe'],
    ['Raupe', 'Larve des Schmetterlings'],
    ['Motte', 'Nachtfalter am Licht'],
    ['Libelle', 'Insekt mit Glasflügeln am Teich'],
    ['Kaefer', 'Insekt mit harten Deckflügeln'],
    ['Marienkaefer', 'Roter Glückskäfer mit Punkten'],
    ['Grille', 'Zirpendes Insekt'],
    ['Heuschrecke', 'Springendes Insekt der Wiese'],
    ['Fliege', 'Lästiges Insekt am Fenster'],
    ['Muecke', 'Stechendes Insekt im Sommer'],
    ['Floh', 'Springender Parasit'],
    ['Laus', 'Kleiner Parasit im Haar'],
    ['Zecke', 'Blutsaugender Spinnentier'],
    ['Spinne', 'Achtbeiniger Netzbauer'],
    ['Skorpion', 'Spinnentier mit Giftstachel'],
    ['Tausendfuessler', 'Vielbeiniges Bodentier'],
    ['Regenwurm', 'Nützliches Bodentier'],
    ['Schnecke', 'Langsames Tier mit Haus'],

    ['Eiche', 'Baum mit Eicheln'],
    ['Buche', 'Laubbaum mit glatter Rinde'],
    ['Birke', 'Baum mit weisser Rinde'],
    ['Linde', 'Baum mit herzförmigen Blättern'],
    ['Ahorn', 'Baum mit Propellerfrüchten'],
    ['Ulme', 'Laubbaum, oft vom Sterben bedroht'],
    ['Esche', 'Laubbaum mit gefiederten Blättern'],
    ['Erle', 'Baum an feuchten Standorten'],
    ['Weide', 'Baum mit Kätzchen am Bach'],
    ['Pappel', 'Schlanker schnellwüchsiger Baum'],
    ['Kastanie', 'Baum mit stacheligen Früchten'],
    ['Tanne', 'Nadelbaum mit stehenden Zapfen'],
    ['Fichte', 'Häufigster Nadelbaum Deutschlands'],
    ['Kiefer', 'Nadelbaum mit langen Nadeln'],
    ['Laerche', 'Nadelbaum, der die Nadeln verliert'],
    ['Zeder', 'Nadelbaum des Libanon'],
    ['Palme', 'Baum der Tropen'],
    ['Olivenbaum', 'Mittelmeerbaum mit Ölfrüchten'],
    ['Bambus', 'Schnell wachsendes Riesengras'],
    ['Efeu', 'Immergrüne Kletterpflanze'],
    ['Farn', 'Blütenlose Waldpflanze'],
    ['Moos', 'Weicher grüner Bodenbewuchs'],
    ['Flechte', 'Symbiose aus Pilz und Alge'],
    ['Alge', 'Einfache Wasserpflanze'],
    ['Pilz', 'Organismus mit Hut und Stiel'],
    ['Steinpilz', 'Begehrter Speisepilz'],
    ['Pfifferling', 'Gelber Speisepilz'],
    ['Champignon', 'Häufigster Zuchtpilz'],
    ['Fliegenpilz', 'Roter Pilz mit weissen Punkten'],
    ['Trueffel', 'Teurer unterirdischer Pilz'],

    ['Rose', 'Blume mit Dornen'],
    ['Tulpe', 'Frühlingsblume aus Holland'],
    ['Narzisse', 'Gelbe Osterblume'],
    ['Nelke', 'Blume mit gefransten Blüten'],
    ['Lilie', 'Elegante Blume im Wappen'],
    ['Orchidee', 'Edle exotische Blume'],
    ['Veilchen', 'Kleine violette Frühlingsblume'],
    ['Gaensebluemchen', 'Kleine weisse Wiesenblume'],
    ['Loewenzahn', 'Gelbe Wiesenblume mit Pusteblume'],
    ['Sonnenblume', 'Hohe Blume, die sich zur Sonne dreht'],
    ['Mohn', 'Rote Feldblume'],
    ['Kornblume', 'Blaue Blume im Getreide'],
    ['Klee', 'Wiesenpflanze, vierblättrig ein Glücksbringer'],
    ['Distel', 'Stachelige Pflanze, Wappen Schottlands'],
    ['Brennnessel', 'Pflanze, die auf der Haut brennt'],
    ['Lavendel', 'Duftende violette Pflanze'],
    ['Kaktus', 'Stachelige Wüstenpflanze'],
    ['Efeutute', 'Beliebte Zimmerpflanze'],
    ['Bonsai', 'Kunstvoll klein gehaltener Baum'],

    ['Wurzel', 'Unterirdischer Teil der Pflanze'],
    ['Stamm', 'Tragender Teil des Baumes'],
    ['Ast', 'Abzweigung am Baum'],
    ['Zweig', 'Dünner Ast'],
    ['Blatt', 'Grünes Organ der Pflanze'],
    ['Bluete', 'Fortpflanzungsorgan der Pflanze'],
    ['Knospe', 'Noch geschlossene Blüte'],
    ['Samen', 'Keim einer neuen Pflanze'],
    ['Frucht', 'Was aus der Blüte entsteht'],
    ['Rinde', 'Äussere Schicht des Stammes'],
    ['Harz', 'Klebriger Saft des Nadelbaums'],
    ['Nektar', 'Süsser Saft der Blüte'],
    ['Pollen', 'Blütenstaub'],
    ['Dorn', 'Spitze an der Rose'],
    ['Stachel', 'Spitze Wehr am Kaktus'],
    ['Laub', 'Blätterwerk im Herbst'],
    ['Nadel', 'Blatt des Tannenbaums'],
    ['Zapfen', 'Frucht des Nadelbaums'],

    ['Regen', 'Wasser von oben'],
    ['Schnee', 'Weisser Niederschlag'],
    ['Hagel', 'Eiskörner vom Himmel'],
    ['Nebel', 'Wolke am Boden'],
    ['Tau', 'Feuchtigkeit am Morgen'],
    ['Reif', 'Weisser Frost am Morgen'],
    ['Frost', 'Temperatur unter null'],
    ['Sturm', 'Sehr starker Wind'],
    ['Orkan', 'Stärkster Sturm'],
    ['Brise', 'Leichter Wind'],
    ['Blitz', 'Grelle Entladung im Gewitter'],
    ['Donner', 'Geräusch nach dem Blitz'],
    ['Gewitter', 'Unwetter mit Blitz und Donner'],
    ['Regenbogen', 'Farbiger Bogen nach dem Regen'],
    ['Wolke', 'Weisses Gebilde am Himmel'],
    ['Sonne', 'Unser Stern'],
    ['Mond', 'Erdtrabant'],
    ['Stern', 'Leuchtender Himmelskörper'],
    ['Komet', 'Himmelskörper mit Schweif'],
    ['Meteor', 'Sternschnuppe'],
    ['Planet', 'Himmelskörper um einen Stern'],
    ['Galaxie', 'Riesiges Sternsystem'],
    ['Mars', 'Der rote Planet'],
    ['Venus', 'Der Morgenstern'],
    ['Jupiter', 'Grösster Planet'],
    ['Saturn', 'Planet mit den Ringen'],
    ['Merkur', 'Sonnennächster Planet'],
    ['Neptun', 'Äusserster Planet'],
    ['Uranus', 'Planet, der auf der Seite liegt'],
    ['Pluto', 'Ehemaliger neunter Planet'],
    ['Sonnensystem', 'Sonne mit ihren Planeten'],
    ['Umlaufbahn', 'Weg eines Himmelskörpers'],
    ['Finsternis', 'Verdunkelung von Sonne oder Mond'],
    ['Polarlicht', 'Leuchten am Nordhimmel'],

    ['Fruehling', 'Jahreszeit des Erwachens'],
    ['Sommer', 'Wärmste Jahreszeit'],
    ['Herbst', 'Jahreszeit des Laubfalls'],
    ['Winter', 'Kälteste Jahreszeit'],
    ['Klima', 'Langjähriges Wettergeschehen'],
    ['Wetter', 'Zustand der Atmosphäre'],
    ['Temperatur', 'Mass für die Wärme'],
    ['Ozonschicht', 'Schützende Hülle der Erde'],
    ['Umwelt', 'Was uns natürlich umgibt'],
    ['Naturschutz', 'Bewahrung von Landschaft und Arten'],
    ['Artenschutz', 'Erhalt bedrohter Tiere'],
    ['Nationalpark', 'Grosses Schutzgebiet'],
    ['Biotop', 'Lebensraum einer Gemeinschaft'],
    ['Oekosystem', 'Zusammenspiel von Lebewesen und Umwelt'],
    ['Fotosynthese', 'Zuckerbildung im Blatt durch Licht'],
    ['Chlorophyll', 'Grüner Farbstoff der Pflanzen'],
    ['Sauerstoff', 'Gas zum Atmen'],
    ['Kohlendioxid', 'Treibhausgas aus der Verbrennung'],
    ['Nahrungskette', 'Wer wen frisst'],
    ['Winterschlaf', 'Lange Ruhe des Igels'],
    ['Zugvogel', 'Vogel, der im Herbst wegfliegt'],
    ['Herde', 'Gruppe weidender Tiere'],
    ['Schwarm', 'Gruppe von Fischen oder Vögeln'],
    ['Rudel', 'Gruppe von Wölfen'],
    ['Nest', 'Brutstätte eines Vogels'],
    ['Hoehle', 'Unterschlupf im Fels'],
    ['Bau', 'Unterirdische Wohnung des Fuchses'],
    ['Revier', 'Verteidigtes Gebiet eines Tieres'],
    ['Beute', 'Erlegtes Tier des Räubers'],
    ['Raubtier', 'Fleischfressendes Tier'],
    ['Pflanzenfresser', 'Tier, das nur Grünes frisst'],
    ['Saeugetier', 'Tier, das seine Jungen säugt'],
    ['Reptil', 'Kriechtier mit Schuppen'],
    ['Amphibie', 'Lurch zwischen Wasser und Land'],
    ['Insekt', 'Tier mit sechs Beinen'],
    ['Fell', 'Behaarung eines Tieres'],
    ['Feder', 'Was den Vogel bedeckt'],
    ['Schuppe', 'Plättchen auf der Fischhaut'],
    ['Kralle', 'Scharfe Zehe des Raubtiers'],
    ['Huf', 'Fussende des Pferdes'],
    ['Geweih', 'Kopfschmuck des Hirsches'],
    ['Stosszahn', 'Langer Zahn des Elefanten'],
    ['Ruessel', 'Nase des Elefanten'],
    ['Fluegel', 'Organ zum Fliegen'],
    ['Flosse', 'Organ zum Schwimmen'],
    ['Kieme', 'Atemorgan des Fisches'],
    ['Panzer', 'Harte Hülle der Schildkröte'],
    ['Kokon', 'Hülle der Puppe'],
    ['Ei', 'Woraus das Küken schlüpft'],
    ['Brut', 'Nachwuchs im Nest'],
    ['Welpe', 'Junger Hund'],
    ['Kalb', 'Junges Rind'],
    ['Fohlen', 'Junges Pferd'],
    ['Ferkel', 'Junges Schwein'],
    ['Lamm', 'Junges Schaf'],
    ['Kitz', 'Junges Reh'],
    ['Kueken', 'Junges Huhn']
  ]
}
