import type { Category } from './index'

/**
 * Bulk filler vocabulary, 2 letters upward.
 *
 * A dense 11×11 grid has ~40 slots, most of them crossed in both directions, so
 * the generator needs many alternatives per letter pattern. The six themed
 * categories are too thin for that on their own — this file widens every bucket,
 * especially the 4- to 6-letter ones that carry most of the grid.
 *
 * Umlauts expand in normaliseAnswer (ä→AE, ß→SS), so entries are spelled here
 * the way they land in the grid.
 */
export const weitere: Category = {
  id: 'weitere',
  label: 'Weitere Wörter',
  entries: [
    // ── 2 letters ──────────────────────────────────────────────────────────
    ['Ab', 'Vorsilbe für weg'],
    ['An', 'Gegenteil von aus'],
    ['Au', 'Ruf bei Schmerz'],
    ['Da', 'An diesem Ort'],
    ['Du', 'Persönliche Anrede'],
    ['Ei', 'Legt das Huhn'],
    ['Er', 'Dritte Person männlich'],
    ['Es', 'Sächliches Fürwort'],
    ['Eu', 'Kürzel der Europäischen Union'],
    ['He', 'Ruf zum Anhalten'],
    ['In', 'Gegenteil von aus'],
    ['Ja', 'Zustimmende Antwort'],
    ['Je', 'Pro, für jeweils'],
    ['Kg', 'Kurzzeichen für Kilogramm'],
    ['Km', 'Kurzzeichen für Kilometer'],
    ['Nu', 'Im Nu, sehr schnell'],
    ['Ob', 'Einleitung eines Nebensatzes'],
    ['Oh', 'Ausruf des Staunens'],
    ['Ok', 'Kurz für einverstanden'],
    ['Ps', 'Nachtrag im Brief'],
    ['So', 'Auf diese Weise'],
    ['Tu', 'Aufforderung zu handeln'],
    ['Um', 'Rundherum'],
    ['Wc', 'Kurzzeichen für die Toilette'],
    ['Zu', 'Geschlossen'],

    // ── 4 letters ──────────────────────────────────────────────────────────
    ['Adel', 'Bevorrechtigter Stand'],
    ['Ader', 'Blutgefäss im Körper'],
    ['Affe', 'Kletternder Primat'],
    ['Akte', 'Sammlung von Schriftstücken'],
    ['Alge', 'Einfache Wasserpflanze'],
    ['Anis', 'Gewürz mit Lakritzgeschmack'],
    ['Arzt', 'Heilkundiger in der Praxis'],
    ['Asyl', 'Zuflucht für Verfolgte'],
    ['Atem', 'Luft in der Lunge'],
    ['Atom', 'Kleinster Baustein des Stoffes'],
    ['Auge', 'Organ des Sehens'],
    ['Auto', 'Wagen mit vier Rädern'],
    ['Bach', 'Kleines fliessendes Gewässer'],
    ['Bahn', 'Zug auf Schienen'],
    ['Ball', 'Runder Spielkörper'],
    ['Band', 'Schmaler Streifen Stoff'],
    ['Bank', 'Sitzgelegenheit im Park'],
    ['Bart', 'Haare im Gesicht'],
    ['Bass', 'Tiefe Männerstimme'],
    ['Baum', 'Holzgewächs mit Krone'],
    ['Beet', 'Bepflanzte Fläche im Garten'],
    ['Beil', 'Werkzeug zum Spalten'],
    ['Bein', 'Gliedmasse zum Gehen'],
    ['Berg', 'Grosse Erhebung im Gelände'],
    ['Bett', 'Möbel zum Schlafen'],
    ['Bier', 'Getränk aus Hopfen und Malz'],
    ['Bild', 'Gemälde an der Wand'],
    ['Blei', 'Schweres weiches Metall'],
    ['Blut', 'Rote Körperflüssigkeit'],
    ['Boot', 'Kleines Wasserfahrzeug'],
    ['Bord', 'Seite des Schiffes'],
    ['Brot', 'Gebackenes Grundnahrungsmittel'],
    ['Buch', 'Gebundene Seiten zum Lesen'],
    ['Burg', 'Befestigter Wohnsitz im Mittelalter'],
    ['Chef', 'Vorgesetzter im Betrieb'],
    ['Chor', 'Gruppe von Sängern'],
    ['Dach', 'Oberer Abschluss des Hauses'],
    ['Dame', 'Höfliche Anrede für eine Frau'],
    ['Damm', 'Aufschüttung gegen das Wasser'],
    ['Dank', 'Ausdruck der Erkenntlichkeit'],
    ['Darm', 'Teil des Verdauungstrakts'],
    ['Dieb', 'Wer fremdes Eigentum nimmt'],
    ['Ding', 'Gegenstand, Sache'],
    ['Dorf', 'Kleine ländliche Siedlung'],
    ['Dorn', 'Spitze an der Rose'],
    ['Dose', 'Behälter aus Blech'],
    ['Duft', 'Angenehmer Geruch'],
    ['Ebbe', 'Niedriger Wasserstand am Meer'],
    ['Ecke', 'Wo zwei Wände zusammenstossen'],
    ['Ehre', 'Ansehen einer Person'],
    ['Eile', 'Grosse Hast'],
    ['Elan', 'Schwung, Begeisterung'],
    ['Elch', 'Grosses Geweihtier des Nordens'],
    ['Elle', 'Knochen im Unterarm'],
    ['Epos', 'Langes Heldengedicht'],
    ['Erbe', 'Nachlass eines Verstorbenen'],
    ['Erde', 'Dritter Planet der Sonne'],
    ['Erle', 'Laubbaum am feuchten Ufer'],
    ['Etui', 'Kleines Behältnis für Stifte'],
    ['Eule', 'Nachtaktiver Greifvogel'],
    ['Fach', 'Abteilung im Regal'],
    ['Fass', 'Rundes Holzgefäss'],
    ['Fels', 'Grosser harter Stein'],
    ['Filz', 'Verdichtetes Wollmaterial'],
    ['Flur', 'Gang in der Wohnung'],
    ['Form', 'Äussere Gestalt'],
    ['Foto', 'Aufnahme mit der Kamera'],
    ['Fuge', 'Spalt zwischen Fliesen'],
    ['Gans', 'Grosser Wasservogel'],
    ['Garn', 'Faden zum Nähen'],
    ['Gast', 'Besucher im Haus'],
    ['Gips', 'Weisses Bindemittel am Bau'],
    ['Glas', 'Durchsichtiger Werkstoff'],
    ['Gold', 'Edles gelbes Metall'],
    ['Golf', 'Sport mit Schläger und Loch'],
    ['Grab', 'Ruhestätte des Toten'],
    ['Grad', 'Einheit der Temperatur'],
    ['Graf', 'Adelstitel unter dem Fürsten'],
    ['Gras', 'Grüner Bewuchs der Wiese'],
    ['Grat', 'Scharfe Kante am Berg'],
    ['Gurt', 'Band zum Sichern'],
    ['Haft', 'Freiheitsentzug im Gefängnis'],
    ['Hahn', 'Männliches Huhn'],
    ['Halm', 'Stängel des Getreides'],
    ['Hals', 'Verbindung von Kopf und Rumpf'],
    ['Hand', 'Greiforgan am Arm'],
    ['Hang', 'Geneigtes Gelände'],
    ['Harz', 'Klebriger Saft der Nadelbäume'],
    ['Hase', 'Langohriges Feldtier'],
    ['Haus', 'Gebäude zum Wohnen'],
    ['Haut', 'Äussere Hülle des Körpers'],
    ['Heft', 'Gebundene Blätter zum Schreiben'],
    ['Heim', 'Eigenes Zuhause'],
    ['Held', 'Mutiger Hauptdarsteller'],
    ['Helm', 'Schutz für den Kopf'],
    ['Hemd', 'Kleidungsstück mit Kragen'],
    ['Herr', 'Höfliche Anrede für einen Mann'],
    ['Herz', 'Motor des Blutkreislaufs'],
    ['Hexe', 'Zauberkundige im Märchen'],
    ['Hieb', 'Kräftiger Schlag'],
    ['Hirn', 'Denkorgan im Kopf'],
    ['Hirt', 'Hüter der Schafherde'],
    ['Hohn', 'Beissender Spott'],
    ['Holz', 'Material aus dem Baum'],
    ['Horn', 'Blasinstrument aus Messing'],
    ['Hose', 'Beinkleid'],
    ['Huhn', 'Eierlegendes Hausgeflügel'],
    ['Hund', 'Treuer Vierbeiner'],
    ['Hupe', 'Signalgeber im Auto'],
    ['Idee', 'Plötzlicher guter Einfall'],
    ['Igel', 'Stacheliges Gartentier'],
    ['Iris', 'Farbiger Ring im Auge'],
    ['Jahr', 'Zeitraum von zwölf Monaten'],
    ['Jazz', 'Musik mit Improvisation'],
    ['Joch', 'Geschirr für Zugtiere'],
    ['Kahn', 'Flaches Ruderboot'],
    ['Kalk', 'Weisses Gestein zum Mörtel'],
    ['Kamm', 'Gerät für die Haare'],
    ['Kanu', 'Boot mit Stechpaddel'],
    ['Kern', 'Inneres der Frucht'],
    ['Kiel', 'Unterster Balken des Schiffs'],
    ['Kies', 'Grober Sand'],
    ['Kind', 'Junger Mensch'],
    ['Kinn', 'Unterster Teil des Gesichts'],
    ['Kino', 'Ort für Filmvorführungen'],
    ['Klee', 'Pflanze mit drei Blättern'],
    ['Klub', 'Verein mit Mitgliedern'],
    ['Knie', 'Gelenk in der Beinmitte'],
    ['Koch', 'Fachmann am Herd'],
    ['Kohl', 'Gemüse mit festem Kopf'],
    ['Korb', 'Geflochtener Behälter'],
    ['Korn', 'Einzelnes Samenkorn'],
    ['Kran', 'Hebegerät auf der Baustelle'],
    ['Krug', 'Gefäss mit Henkel'],
    ['Lack', 'Glänzender Anstrich'],
    ['Lage', 'Örtliche Situation'],
    ['Lamm', 'Junges Schaf'],
    ['Land', 'Staat mit Grenzen'],
    ['Last', 'Schwere Bürde'],
    ['Laub', 'Blätter der Bäume'],
    ['Lauf', 'Sportliche Strecke'],
    ['Laut', 'Hörbarer Ton der Sprache'],
    ['Lehm', 'Formbare Tonerde'],
    ['Leid', 'Tiefer Kummer'],
    ['Leim', 'Klebstoff für Holz'],
    ['Lied', 'Gesungenes Musikstück'],
    ['Lift', 'Aufzug im Gebäude'],
    ['Loch', 'Öffnung im Material'],
    ['Lohn', 'Bezahlung für Arbeit'],
    ['Luft', 'Gasgemisch zum Atmen'],
    ['Lupe', 'Glas zum Vergrössern'],
    ['Mais', 'Getreide mit gelben Körnern'],
    ['Mann', 'Erwachsene männliche Person'],
    ['Mark', 'Weiches Inneres im Knochen'],
    ['Mast', 'Hoher Träger am Schiff'],
    ['Maus', 'Kleiner Nager im Haus'],
    ['Meer', 'Grosses Salzgewässer'],
    ['Mehl', 'Gemahlenes Getreide'],
    ['Mine', 'Stift im Kugelschreiber'],
    ['Mode', 'Aktuelle Kleidung'],
    ['Mond', 'Trabant der Erde'],
    ['Moos', 'Weicher grüner Bewuchs'],
    ['Mord', 'Vorsätzliche Tötung'],
    ['Most', 'Frisch gepresster Fruchtsaft'],
    ['Mund', 'Öffnung zum Essen'],
    ['Nadel', 'Werkzeug zum Nähen'],
    ['Naht', 'Verbindung zweier Stoffteile'],
    ['Nase', 'Organ des Riechens'],
    ['Neid', 'Missgunst gegenüber anderen'],
    ['Nerv', 'Leitung des Reizes'],
    ['Nest', 'Brutstätte der Vögel'],
    ['Netz', 'Geknüpftes Fanggerät'],
    ['Nixe', 'Wasserwesen der Sage'],
    ['Note', 'Zeichen in der Musik'],
    ['Oase', 'Wasserstelle in der Wüste'],
    ['Ofen', 'Heizgerät im Raum'],
    ['Oper', 'Gesungenes Bühnenwerk'],
    ['Paar', 'Zwei zusammengehörige'],
    ['Park', 'Grünanlage in der Stadt'],
    ['Pass', 'Ausweis für die Reise'],
    ['Pelz', 'Fell als Kleidung'],
    ['Pilz', 'Sammelgut im Herbstwald'],
    ['Pony', 'Kleines Pferd'],
    ['Post', 'Briefe und Pakete'],
    ['Pult', 'Schrägtisch zum Schreiben'],
    ['Rabe', 'Schwarzer klugerVogel'],
    ['Rand', 'Äussere Begrenzung'],
    ['Rang', 'Stellung in der Ordnung'],
    ['Rast', 'Pause auf der Wanderung'],
    ['Raum', 'Zimmer im Haus'],
    ['Rebe', 'Ranke des Weinstocks'],
    ['Reis', 'Körnerfrucht aus Asien'],
    ['Rest', 'Was übrig bleibt'],
    ['Ring', 'Schmuck am Finger'],
    ['Rock', 'Kleidungsstück der Frau'],
    ['Rohr', 'Hohler Leitungsstrang'],
    ['Rose', 'Blume mit Dornen'],
    ['Rost', 'Roter Belag auf Eisen'],
    ['Ruhe', 'Zustand ohne Lärm'],
    ['Saal', 'Grosser Versammlungsraum'],
    ['Sack', 'Beutel aus grobem Stoff'],
    ['Saft', 'Getränk aus Früchten'],
    ['Sage', 'Überlieferte Erzählung'],
    ['Salz', 'Würze aus dem Meer'],
    ['Same', 'Keim der Pflanze'],
    ['Sand', 'Feines Korn am Strand'],
    ['Satz', 'Folge von Wörtern'],
    ['Seil', 'Starkes gedrehtes Tau'],
    ['Sieb', 'Gerät zum Trennen'],
    ['Sinn', 'Bedeutung einer Sache'],
    ['Sitz', 'Platz zum Setzen'],
    ['Sofa', 'Gepolstertes Sitzmöbel'],
    ['Sohn', 'Männliches Kind'],
    ['Stab', 'Länglicher dünner Stock'],
    ['Takt', 'Rhythmische Einheit'],
    ['Tanz', 'Bewegung zur Musik'],
    ['Teig', 'Masse aus Mehl und Wasser'],
    ['Teil', 'Stück eines Ganzen'],
    ['Text', 'Geschriebene Worte'],
    ['Tier', 'Lebewesen mit Sinnen'],
    ['Topf', 'Gefäss zum Kochen'],
    ['Tuch', 'Stück Stoff'],
    ['Turm', 'Hohes schmales Bauwerk'],
    ['Ufer', 'Rand des Gewässers'],
    ['Vase', 'Gefäss für Blumen'],
    ['Vieh', 'Nutztiere des Bauern'],
    ['Wald', 'Grosse Ansammlung von Bäumen'],
    ['Wand', 'Senkrechte Begrenzung im Raum'],
    ['Ware', 'Handelsgut im Laden'],
    ['Wein', 'Getränk aus Trauben'],
    ['Welt', 'Die ganze Erde'],
    ['Werk', 'Geschaffenes Arbeitsergebnis'],
    ['Wert', 'Bedeutung in Zahlen'],
    ['Wind', 'Bewegte Luft'],
    ['Wolf', 'Wilder Vorfahr des Hundes'],
    ['Wort', 'Kleinste Spracheinheit'],
    ['Wurm', 'Kriechendes Ringeltier'],
    ['Zahl', 'Ziffer zum Rechnen'],
    ['Zahn', 'Beisswerkzeug im Mund'],
    ['Zaun', 'Umfriedung des Grundstücks'],
    ['Zeit', 'Ablauf der Stunden'],
    ['Zelt', 'Unterkunft aus Stoff'],
    ['Ziel', 'Angestrebter Endpunkt'],
    ['Zorn', 'Heftiger Ärger'],

    // ── 5 letters ──────────────────────────────────────────────────────────
    ['Abend', 'Zeit nach dem Nachmittag'],
    ['Ahorn', 'Baum mit gezacktem Blatt'],
    ['Ampel', 'Signal an der Kreuzung'],
    ['Amsel', 'Schwarzer Singvogel'],
    ['Birne', 'Frucht mit dickem Ende'],
    ['Blatt', 'Grünes Organ der Pflanze'],
    ['Bogen', 'Gekrümmte Linie'],
    ['Bohne', 'Hülsenfrucht im Beet'],
    ['Creme', 'Salbe für die Haut'],
    ['Dauer', 'Länge eines Zeitraums'],
    ['Diele', 'Vorraum der Wohnung'],
    ['Draht', 'Dünner Metallfaden'],
    ['Drama', 'Ernstes Bühnenstück'],
    ['Druck', 'Kraft auf eine Fläche'],
    ['Eiche', 'Baum mit Eicheln'],
    ['Ernte', 'Einbringen der Feldfrüchte'],
    ['Essig', 'Saure Würze im Salat'],
    ['Fahne', 'Tuch am Mast'],
    ['Falke', 'Schneller Greifvogel'],
    ['Faust', 'Geballte Hand'],
    ['Feder', 'Teil des Vogelkleids'],
    ['Ferse', 'Hinterer Teil des Fusses'],
    ['Fjord', 'Enge Meeresbucht im Norden'],
    ['Forst', 'Bewirtschafteter Wald'],
    ['Frost', 'Kälte unter null Grad'],
    ['Fuchs', 'Rotes schlaues Waldtier'],
    ['Funke', 'Kleiner glühender Splitter'],
    ['Gabel', 'Besteck mit Zinken'],
    ['Galle', 'Bittere Verdauungsflüssigkeit'],
    ['Gasse', 'Enge Strasse'],
    ['Gebet', 'Zwiesprache mit Gott'],
    ['Geige', 'Streichinstrument'],
    ['Geist', 'Übersinnliche Erscheinung'],
    ['Gramm', 'Kleine Gewichtseinheit'],
    ['Grube', 'Ausgehobenes Loch'],
    ['Gurke', 'Längliches grünes Gemüse'],
    ['Hafen', 'Anlegestelle für Schiffe'],
    ['Hafer', 'Getreide für das Müsli'],
    ['Hagel', 'Niederschlag aus Eiskörnern'],
    ['Haken', 'Gebogenes Metallteil'],
    ['Halle', 'Grosser überdachter Raum'],
    ['Harfe', 'Zupfinstrument mit Saiten'],
    ['Hecht', 'Räuberischer Süsswasserfisch'],
    ['Hecke', 'Lebende Grenze im Garten'],
    ['Heide', 'Landschaft mit Erika'],
    ['Henne', 'Weibliches Huhn'],
    ['Herde', 'Gruppe von Weidetieren'],
    ['Hitze', 'Sehr hohe Wärme'],
    ['Hobel', 'Werkzeug des Schreiners'],
    ['Honig', 'Süsses Erzeugnis der Bienen'],
    ['Hotel', 'Haus für Übernachtungen'],
    ['Kabel', 'Umhüllte Stromleitung'],
    ['Karte', 'Blatt mit Aufdruck'],
    ['Kegel', 'Figur beim Bahnspiel'],
    ['Kerze', 'Wachslicht mit Docht'],
    ['Kiste', 'Behälter aus Brettern'],
    ['Klang', 'Angenehmer Ton'],
    ['Kleid', 'Einteiliges Frauengewand'],
    ['Knopf', 'Verschluss am Hemd'],
    ['Kraft', 'Körperliche Stärke'],
    ['Kreuz', 'Symbol aus zwei Balken'],
    ['Krone', 'Kopfschmuck des Königs'],
    ['Kugel', 'Runder Körper'],
    ['Kunst', 'Schöpferisches Schaffen'],
    ['Lampe', 'Gerät für Licht'],
    ['Latte', 'Schmales langes Brett'],
    ['Leber', 'Grösste Drüse im Körper'],
    ['Leine', 'Führband für den Hund'],
    ['Licht', 'Sichtbare Strahlung'],
    ['Linie', 'Gerade Verbindung'],
    ['Liter', 'Mass für Flüssigkeit'],
    ['Luchs', 'Wildkatze mit Pinselohren'],
    ['Magen', 'Organ der Verdauung'],
    ['Meile', 'Angelsächsisches Längenmass'],
    ['Meter', 'Einheit der Länge'],
    ['Miete', 'Zahlung für die Wohnung'],
    ['Milch', 'Weisses Getränk der Kuh'],
    ['Mitte', 'Zentraler Punkt'],
    ['Motor', 'Antrieb des Fahrzeugs'],
    ['Nacht', 'Zeit der Dunkelheit'],
    ['Nagel', 'Stift zum Einschlagen'],
    ['Narbe', 'Spur einer verheilten Wunde'],
    ['Natur', 'Ungestaltete Umwelt'],
    ['Nebel', 'Trübung durch feine Tropfen'],
    ['Niere', 'Filterorgan im Körper'],
    ['Nonne', 'Frau im Kloster'],
    ['Nudel', 'Teigware im Topf'],
    ['Ochse', 'Kastriertes Rind'],
    ['Orden', 'Auszeichnung an der Brust'],
    ['Organ', 'Teil des Körpers'],
    ['Osten', 'Himmelsrichtung des Aufgangs'],
    ['Palme', 'Baum am Südstrand'],
    ['Panik', 'Plötzliche grosse Angst'],
    ['Pause', 'Unterbrechung der Arbeit'],
    ['Perle', 'Kugel aus der Muschel'],
    ['Pfeil', 'Geschoss für den Bogen'],
    ['Pfote', 'Fuss des Hundes'],
    ['Pille', 'Kleines rundes Medikament'],
    ['Pokal', 'Siegestrophäe im Sport'],
    ['Preis', 'Kosten einer Ware'],
    ['Probe', 'Vorheriger Versuch'],
    ['Punkt', 'Zeichen am Satzende'],
    ['Puppe', 'Kinderspielzeug in Menschenform'],
    ['Rasen', 'Kurz geschnittenes Gras'],
    ['Ratte', 'Grosser grauer Nager'],
    ['Raupe', 'Larve des Schmetterlings'],
    ['Recht', 'Ordnung der Gesetze'],
    ['Regal', 'Möbel mit Fächern'],
    ['Regen', 'Wasser aus den Wolken'],
    ['Reihe', 'Anordnung hintereinander'],
    ['Reise', 'Fahrt in die Ferne'],
    ['Riese', 'Sehr grosser Mensch'],
    ['Rinde', 'Äussere Schicht des Stamms'],
    ['Rippe', 'Knochen im Brustkorb'],
    ['Robbe', 'Schwimmendes Säugetier mit Flossen'],
    ['Roman', 'Langes erzählendes Buch'],
    ['Ruder', 'Gerät zum Boot bewegen'],
    ['Ruine', 'Rest eines Bauwerks'],
    ['Sahne', 'Fettes Oberteil der Milch'],
    ['Saite', 'Gespannter Klangfaden'],
    ['Salbe', 'Streichbare Heilmasse'],
    ['Sauna', 'Raum zum Schwitzen'],
    ['Schal', 'Tuch um den Hals'],
    ['Schuh', 'Bekleidung für den Fuss'],
    ['Segel', 'Tuch für den Wind'],
    ['Seite', 'Blatt im Buch'],
    ['Skala', 'Einteilung am Messgerät'],
    ['Sonne', 'Stern am Taghimmel'],
    ['Spatz', 'Kleiner grauer Stadtvogel'],
    ['Speer', 'Wurfwaffe mit Spitze'],
    ['Spiel', 'Zeitvertreib nach Regeln'],
    ['Staat', 'Politisches Gemeinwesen'],
    ['Stadt', 'Grosse Siedlung'],
    ['Stall', 'Unterkunft für Vieh'],
    ['Start', 'Beginn des Rennens'],
    ['Staub', 'Feine Schmutzteilchen'],
    ['Stein', 'Hartes Stück Fels'],
    ['Stern', 'Leuchtpunkt am Nachthimmel'],
    ['Stiel', 'Griff am Werkzeug'],
    ['Stier', 'Männliches Rind'],
    ['Stirn', 'Teil über den Augen'],
    ['Stock', 'Gehhilfe aus Holz'],
    ['Stoff', 'Gewebe für Kleidung'],
    ['Stroh', 'Trockene Halme nach der Ernte'],
    ['Strom', 'Elektrische Energie'],
    ['Stufe', 'Tritt an der Treppe'],
    ['Stuhl', 'Sitzmöbel mit Lehne'],
    ['Sturm', 'Sehr starker Wind'],
    ['Sturz', 'Fall zu Boden'],
    ['Summe', 'Ergebnis der Addition'],
    ['Sumpf', 'Nasser weicher Boden'],
    ['Tadel', 'Ausdruck des Missfallens'],
    ['Tafel', 'Fläche zum Beschreiben'],
    ['Tanne', 'Immergrüner Nadelbaum'],
    ['Tante', 'Schwester der Mutter'],
    ['Tasse', 'Gefäss für den Kaffee'],
    ['Taste', 'Knopf am Klavier'],
    ['Taube', 'Vogel des Friedens'],
    ['Teich', 'Kleines stehendes Gewässer'],
    ['Tempo', 'Geschwindigkeit'],
    ['Tenor', 'Hohe Männerstimme'],
    ['Thema', 'Gegenstand des Gesprächs'],
    ['Thron', 'Sitz des Herrschers'],
    ['Tiger', 'Gestreifte Grosskatze'],
    ['Tinte', 'Farbe im Füller'],
    ['Titel', 'Name des Werkes'],
    ['Tonne', 'Grosses Fass'],
    ['Torte', 'Feiner Kuchen mit Sahne'],
    ['Traum', 'Bild im Schlaf'],
    ['Truhe', 'Grosser Behälter mit Deckel'],
    ['Tulpe', 'Frühlingsblume aus Holland'],
    ['Vogel', 'Tier mit Federn'],
    ['Waage', 'Gerät zum Wiegen'],
    ['Wange', 'Seite des Gesichts'],
    ['Wiese', 'Fläche mit Gras'],
    ['Wolke', 'Gebilde am Himmel'],
    ['Wurst', 'Erzeugnis des Metzgers'],
    ['Zange', 'Greifwerkzeug'],
    ['Zebra', 'Gestreiftes Steppenpferd'],
    ['Ziege', 'Meckerndes Nutztier'],
    ['Zitat', 'Wörtlich angeführte Stelle'],
    ['Zwerg', 'Kleine Märchengestalt'],

    // ── 6 letters ──────────────────────────────────────────────────────────
    ['Ameise', 'Fleissiges Krabbeltier'],
    ['Anfang', 'Beginn einer Sache'],
    ['Antwort', 'Erwiderung auf die Frage'],
    ['Balkon', 'Vorbau an der Wohnung'],
    ['Becher', 'Trinkgefäss ohne Henkel'],
    ['Besen', 'Gerät zum Kehren'],
    ['Bibel', 'Heilige Schrift der Christen'],
    ['Blume', 'Blühende Pflanze'],
    ['Bremse', 'Vorrichtung zum Anhalten'],
    ['Brille', 'Sehhilfe auf der Nase'],
    ['Bruder', 'Männliches Geschwister'],
    ['Buchse', 'Fassung für den Stecker'],
    ['Butter', 'Streichfett aus Rahm'],
    ['Dackel', 'Hunderasse mit kurzen Beinen'],
    ['Daumen', 'Kürzester Finger'],
    ['Decke', 'Obere Begrenzung des Raums'],
    ['Diesel', 'Kraftstoff für den Motor'],
    ['Distel', 'Stachelige Wiesenpflanze'],
    ['Donner', 'Krachen nach dem Blitz'],
    ['Fabrik', 'Gebäude der Produktion'],
    ['Fenster', 'Öffnung mit Glas'],
    ['Ferien', 'Freie Zeit vom Unterricht'],
    ['Fieber', 'Erhöhte Körpertemperatur'],
    ['Finger', 'Glied an der Hand'],
    ['Flasche', 'Gefäss mit engem Hals'],
    ['Fliege', 'Summendes Insekt'],
    ['Forelle', 'Fisch im klaren Bach'],
    ['Fracht', 'Ladung des Schiffes'],
    ['Freund', 'Vertrauter Mensch'],
    ['Garten', 'Bepflanztes Grundstück'],
    ['Gehalt', 'Monatliche Bezahlung'],
    ['Gipfel', 'Höchster Punkt des Berges'],
    ['Glocke', 'Läutkörper im Turm'],
    ['Hammer', 'Werkzeug zum Schlagen'],
    ['Handel', 'Kauf und Verkauf'],
    ['Hering', 'Fisch aus der Nordsee'],
    ['Herbst', 'Jahreszeit des Laubfalls'],
    ['Himmel', 'Gewölbe über uns'],
    ['Hunger', 'Verlangen nach Essen'],
    ['Insekt', 'Tier mit sechs Beinen'],
    ['Jacke', 'Kurzes Oberbekleidungsstück'],
    ['Kabine', 'Kleiner Raum im Schiff'],
    ['Kaffee', 'Braunes Muntermachergetränk'],
    ['Kamera', 'Gerät für Aufnahmen'],
    ['Kanone', 'Grosses Geschütz'],
    ['Kaninchen', 'Langohriger Stallbewohner'],
    ['Kapitel', 'Abschnitt im Buch'],
    ['Karten', 'Blätter zum Spielen'],
    ['Kartoffel', 'Knolle aus der Erde'],
    ['Kasten', 'Rechteckiger Behälter'],
    ['Kirche', 'Gotteshaus mit Turm'],
    ['Kissen', 'Weiche Stütze für den Kopf'],
    ['Kleber', 'Mittel zum Verbinden'],
    ['Knochen', 'Harter Teil des Skeletts'],
    ['Kompass', 'Gerät für die Richtung'],
    ['Konzert', 'Musikalische Aufführung'],
    ['Kupfer', 'Rötliches Leitmetall'],
    ['Leiter', 'Gerät zum Hinaufsteigen'],
    ['Lippen', 'Ränder des Mundes'],
    ['Loeffel', 'Besteck für die Suppe'],
    ['Mantel', 'Warmes Überkleid'],
    ['Marmor', 'Edler polierter Kalkstein'],
    ['Mauer', 'Wand aus Steinen'],
    ['Messer', 'Werkzeug zum Schneiden'],
    ['Minute', 'Sechzig Sekunden'],
    ['Muschel', 'Schalentier am Strand'],
    ['Nadeln', 'Blätter der Tanne'],
    ['Nebenfluss', 'Zufluss zum Strom'],
    ['Norden', 'Himmelsrichtung zum Pol'],
    ['Obstbaum', 'Träger von Früchten'],
    ['Onkel', 'Bruder des Vaters'],
    ['Papier', 'Beschreibbares Blatt'],
    ['Pfeffer', 'Scharfes schwarzes Gewürz'],
    ['Pflanze', 'Grünes Lebewesen'],
    ['Pinsel', 'Gerät zum Malen'],
    ['Planet', 'Himmelskörper um die Sonne'],
    ['Quelle', 'Ursprung des Baches'],
    ['Rahmen', 'Einfassung des Bildes'],
    ['Rakete', 'Flugkörper ins All'],
    ['Reifen', 'Gummi auf der Felge'],
    ['Ritter', 'Gepanzerter Kämpfer'],
    ['Sattel', 'Sitz auf dem Pferd'],
    ['Schere', 'Werkzeug mit zwei Klingen'],
    ['Schiff', 'Grosses Wasserfahrzeug'],
    ['Schnee', 'Weisser Winterniederschlag'],
    ['Schule', 'Ort des Lernens'],
    ['Schwan', 'Weisser Wasservogel'],
    ['Sessel', 'Bequemer Einzelsitz'],
    ['Sichel', 'Gebogenes Schneidwerkzeug'],
    ['Silber', 'Weisses Edelmetall'],
    ['Spatel', 'Flaches Rührwerkzeug'],
    ['Spiegel', 'Glas mit Rückbelag'],
    ['Spinne', 'Achtbeiniger Netzbauer'],
    ['Sprache', 'Mittel der Verständigung'],
    ['Stange', 'Langer runder Stab'],
    ['Statue', 'Standbild aus Stein'],
    ['Stempel', 'Gerät für den Abdruck'],
    ['Stimme', 'Klang beim Sprechen'],
    ['Strand', 'Sandufer am Meer'],
    ['Stunde', 'Sechzig Minuten'],
    ['Tasche', 'Behälter zum Tragen'],
    ['Teller', 'Flaches Essgeschirr'],
    ['Tempel', 'Heiliges Bauwerk'],
    ['Teppich', 'Bodenbelag aus Gewebe'],
    ['Teufel', 'Böse Gestalt der Sage'],
    ['Tochter', 'Weibliches Kind'],
    ['Treppe', 'Aufgang mit Stufen'],
    ['Trikot', 'Sporthemd der Mannschaft'],
    ['Tunnel', 'Weg durch den Berg'],
    ['Turban', 'Kopftuch des Orients'],
    ['Wagen', 'Fahrzeug mit Rädern'],
    ['Wasser', 'Farblose Flüssigkeit'],
    ['Wetter', 'Zustand der Atmosphäre'],
    ['Wiesel', 'Flinkes kleines Raubtier'],
    ['Winter', 'Kälteste Jahreszeit'],
    ['Wolle', 'Haarkleid des Schafes'],
    ['Wunder', 'Unerklärliches Ereignis'],
    ['Zeitung', 'Blatt mit Nachrichten'],
    ['Zimmer', 'Raum in der Wohnung'],
    ['Zucker', 'Süssungsmittel'],
    ['Zwiebel', 'Scharfe Knolle in der Küche'],
  ],
}
