import type { Category } from './index'

export const wissenGeschichte: Category = {
  id: 'wissenGeschichte',
  label: 'Wissen & Geschichte',
  entries: [
    ['Atom', 'Kleinster Baustein eines Elements'],
    ['Molekuel', 'Verbund mehrerer Atome'],
    ['Elektron', 'Negativ geladenes Teilchen'],
    ['Proton', 'Positiv geladenes Kernteilchen'],
    ['Neutron', 'Ungeladenes Kernteilchen'],
    ['Element', 'Grundstoff im Periodensystem'],
    ['Wasserstoff', 'Leichtestes Element'],
    ['Helium', 'Gas für Ballons'],
    ['Stickstoff', 'Hauptbestandteil der Luft'],
    ['Kohlenstoff', 'Element des Lebens'],
    ['Eisen', 'Metall, das rostet'],
    ['Kupfer', 'Rotbraunes Metall für Kabel'],
    ['Silber', 'Edelmetall des zweiten Platzes'],
    ['Gold', 'Edelmetall des ersten Platzes'],
    ['Platin', 'Sehr wertvolles Edelmetall'],
    ['Blei', 'Sehr schweres weiches Metall'],
    ['Zinn', 'Metall für Lötzinn'],
    ['Zink', 'Metall zum Verzinken'],
    ['Nickel', 'Metall in Münzen'],
    ['Aluminium', 'Leichtes Metall für Folie'],
    ['Quecksilber', 'Flüssiges Metall im Thermometer'],
    ['Uran', 'Radioaktives Schwermetall'],
    ['Chlor', 'Gas im Schwimmbadwasser'],
    ['Jod', 'Element im Speisesalz'],
    ['Kalzium', 'Mineral für die Knochen'],
    ['Magnesium', 'Mineral gegen Krämpfe'],
    ['Legierung', 'Mischung von Metallen'],
    ['Bronze', 'Legierung aus Kupfer und Zinn'],
    ['Messing', 'Legierung aus Kupfer und Zink'],
    ['Stahl', 'Veredeltes Eisen'],
    ['Diamant', 'Härtester natürlicher Stoff'],
    ['Kristall', 'Regelmässig gebauter Festkörper'],
    ['Saeure', 'Chemischer Gegenspieler der Lauge'],
    ['Lauge', 'Basische Lösung'],
    ['Katalysator', 'Beschleuniger einer Reaktion'],
    ['Reaktion', 'Chemische Umwandlung'],
    ['Loesung', 'Stoff gelöst in Flüssigkeit'],
    ['Destillation', 'Trennung durch Verdampfen'],
    ['Verdunstung', 'Übergang von flüssig zu gasförmig'],
    ['Kondensation', 'Übergang von gasförmig zu flüssig'],

    ['Energie', 'Fähigkeit, Arbeit zu verrichten'],
    ['Kraft', 'Ursache von Bewegungsänderung'],
    ['Masse', 'Mass für die Trägheit'],
    ['Gewicht', 'Kraft der Schwere'],
    ['Schwerkraft', 'Anziehung der Erde'],
    ['Reibung', 'Widerstand zwischen Flächen'],
    ['Druck', 'Kraft pro Fläche'],
    ['Hebel', 'Einfache Maschine zum Kraftsparen'],
    ['Rolle', 'Einfache Maschine mit Seil'],
    ['Magnet', 'Zieht Eisen an'],
    ['Strom', 'Fluss von Ladungen'],
    ['Spannung', 'Antrieb des elektrischen Stroms'],
    ['Widerstand', 'Hemmnis für den Strom'],
    ['Batterie', 'Speicher für Strom'],
    ['Generator', 'Erzeugt Strom aus Bewegung'],
    ['Turbine', 'Rad im Kraftwerk'],
    ['Kraftwerk', 'Anlage zur Stromerzeugung'],
    ['Solarzelle', 'Wandelt Licht in Strom'],
    ['Windrad', 'Nutzt den Wind für Strom'],
    ['Licht', 'Sichtbare Strahlung'],
    ['Schatten', 'Dunkler Bereich hinter einem Körper'],
    ['Linse', 'Gebogenes Glas, das bündelt'],
    ['Prisma', 'Glaskörper, der Licht zerlegt'],
    ['Spektrum', 'Farbband des zerlegten Lichts'],
    ['Laser', 'Gebündeltes kohärentes Licht'],
    ['Schall', 'Was das Ohr hört'],
    ['Echo', 'Zurückgeworfener Schall'],
    ['Welle', 'Sich ausbreitende Schwingung'],
    ['Frequenz', 'Schwingungen pro Sekunde'],
    ['Vakuum', 'Raum ohne Materie'],
    ['Teleskop', 'Gerät für den Blick zu den Sternen'],
    ['Mikroskop', 'Gerät für sehr kleine Dinge'],
    ['Thermometer', 'Gerät für die Temperatur'],
    ['Barometer', 'Gerät für den Luftdruck'],
    ['Waage', 'Gerät zum Wiegen'],
    ['Rakete', 'Fahrzeug für den Weltraum'],
    ['Satellit', 'Künstlicher Erdtrabant'],
    ['Astronaut', 'Raumfahrer'],
    ['Schwerelosigkeit', 'Zustand im Orbit'],

    ['Zelle', 'Kleinste Einheit des Lebens'],
    ['Gen', 'Erbanlage'],
    ['Erbgut', 'Gesamtheit der Gene'],
    ['Evolution', 'Entwicklung der Arten'],
    ['Vererbung', 'Weitergabe von Merkmalen'],
    ['Bakterie', 'Einzelliger Krankheitserreger'],
    ['Virus', 'Erreger, der Zellen befällt'],
    ['Impfung', 'Schutz vor Krankheit'],
    ['Antibiotikum', 'Mittel gegen Bakterien'],
    ['Medikament', 'Arznei gegen Krankheit'],
    ['Tablette', 'Feste Arzneiform'],
    ['Salbe', 'Streichbares Heilmittel'],
    ['Verband', 'Schutz über der Wunde'],
    ['Pflaster', 'Kleiner Wundschutz'],
    ['Spritze', 'Gerät zum Injizieren'],
    ['Operation', 'Chirurgischer Eingriff'],
    ['Narkose', 'Betäubung bei der Operation'],
    ['Diagnose', 'Feststellung der Krankheit'],
    ['Therapie', 'Behandlung einer Krankheit'],
    ['Roentgen', 'Durchleuchtung des Körpers'],
    ['Krankenhaus', 'Klinik für Kranke'],
    ['Arzt', 'Heilkundiger'],
    ['Chirurg', 'Operierender Arzt'],
    ['Zahnarzt', 'Arzt für die Zähne'],
    ['Krankenschwester', 'Pflegekraft in der Klinik'],
    ['Apotheker', 'Fachmann für Arzneien'],

    ['Herz', 'Motor des Blutkreislaufs'],
    ['Lunge', 'Organ zum Atmen'],
    ['Leber', 'Entgiftungsorgan'],
    ['Niere', 'Organ, das den Harn bildet'],
    ['Magen', 'Organ zur Verdauung'],
    ['Darm', 'Langes Verdauungsorgan'],
    ['Gehirn', 'Zentrale des Nervensystems'],
    ['Nerv', 'Leitungsbahn im Körper'],
    ['Muskel', 'Bewegt die Knochen'],
    ['Knochen', 'Fester Teil des Skeletts'],
    ['Skelett', 'Gerüst des Körpers'],
    ['Schaedel', 'Knochen des Kopfes'],
    ['Rippe', 'Knochen des Brustkorbs'],
    ['Wirbel', 'Knochen der Wirbelsäule'],
    ['Gelenk', 'Bewegliche Knochenverbindung'],
    ['Sehne', 'Verbindet Muskel und Knochen'],
    ['Blut', 'Rote Körperflüssigkeit'],
    ['Ader', 'Blutgefäss'],
    ['Puls', 'Schlag des Herzens am Handgelenk'],
    ['Haut', 'Grösstes Organ des Menschen'],
    ['Auge', 'Organ des Sehens'],
    ['Ohr', 'Organ des Hörens'],
    ['Nase', 'Organ des Riechens'],
    ['Zunge', 'Organ des Schmeckens'],
    ['Zahn', 'Werkzeug im Mund'],
    ['Haar', 'Wächst auf dem Kopf'],
    ['Finger', 'Glied der Hand'],
    ['Daumen', 'Kürzester Finger'],
    ['Ferse', 'Hinterer Teil des Fusses'],
    ['Knie', 'Gelenk im Bein'],
    ['Ellbogen', 'Gelenk im Arm'],
    ['Schulter', 'Verbindung von Arm und Rumpf'],
    ['Vitamin', 'Lebenswichtiger Nährstoff'],
    ['Eiweiss', 'Baustoff des Körpers'],
    ['Kalorie', 'Einheit des Brennwerts'],

    ['Antike', 'Epoche von Griechen und Römern'],
    ['Mittelalter', 'Epoche der Burgen und Ritter'],
    ['Neuzeit', 'Epoche nach dem Mittelalter'],
    ['Steinzeit', 'Früheste Epoche der Menschheit'],
    ['Bronzezeit', 'Epoche nach der Steinzeit'],
    ['Pharao', 'Herrscher im alten Ägypten'],
    ['Pyramide', 'Grabmal der Pharaonen'],
    ['Sphinx', 'Fabelwesen mit Löwenkörper'],
    ['Hieroglyphe', 'Ägyptisches Schriftzeichen'],
    ['Mumie', 'Einbalsamierter Leichnam'],
    ['Papyrus', 'Beschreibstoff der Ägypter'],
    ['Kaiser', 'Höchster Herrscher'],
    ['Koenigin', 'Weibliche Herrscherin'],
    ['Ritter', 'Gepanzerter Reiter'],
    ['Ruestung', 'Schutz des Ritters'],
    ['Schwert', 'Waffe mit Klinge'],
    ['Schild', 'Schutzwaffe am Arm'],
    ['Lanze', 'Stichwaffe des Reiters'],
    ['Armbrust', 'Schusswaffe des Mittelalters'],
    ['Katapult', 'Wurfmaschine der Belagerung'],
    ['Belagerung', 'Einschliessung einer Burg'],
    ['Zugbruecke', 'Bewegliche Brücke der Burg'],
    ['Burggraben', 'Wassergraben um die Burg'],
    ['Zunft', 'Vereinigung der Handwerker'],
    ['Hanse', 'Bund norddeutscher Handelsstädte'],
    ['Kreuzzug', 'Kriegszug ins Heilige Land'],
    ['Reformation', 'Kirchenerneuerung durch Luther'],
    ['Ablass', 'Sündenerlass gegen Geld'],
    ['Pest', 'Der Schwarze Tod'],
    ['Inquisition', 'Kirchliches Ketzergericht'],
    ['Hexenverfolgung', 'Prozesse gegen angebliche Zauberinnen'],
    ['Renaissance', 'Wiedergeburt der Antike'],
    ['Buchdruck', 'Erfindung Gutenbergs'],
    ['Entdeckung', 'Auffinden von Unbekanntem'],
    ['Kolumbus', 'Entdecker Amerikas'],
    ['Karavelle', 'Segelschiff der Entdecker'],
    ['Konquistador', 'Spanischer Eroberer'],
    ['Aufklaerung', 'Epoche der Vernunft'],
    ['Revolution', 'Umsturz der Verhältnisse'],
    ['Guillotine', 'Fallbeil der Französischen Revolution'],
    ['Napoleon', 'Französischer Kaiser und Feldherr'],
    ['Industrialisierung', 'Zeitalter der Fabriken'],
    ['Dampfmaschine', 'Antrieb der Industrialisierung'],
    ['Eisenbahn', 'Verkehrsmittel auf Schienen'],
    ['Auswanderung', 'Verlassen der Heimat'],
    ['Kolonialismus', 'Herrschaft über fremde Gebiete'],
    ['Weltkrieg', 'Globaler bewaffneter Konflikt'],
    ['Schuetzengraben', 'Stellung im Ersten Weltkrieg'],
    ['Republik', 'Staat ohne Monarchen'],
    ['Diktatur', 'Herrschaft eines Einzelnen'],
    ['Demokratie', 'Herrschaft des Volkes'],
    ['Widerstand', 'Auflehnung gegen Unrecht'],
    ['Mauerfall', 'Ende der deutschen Teilung'],
    ['Wiedervereinigung', 'Zusammenschluss der beiden deutschen Staaten'],
    ['Kalterkrieg', 'Spannung zwischen Ost und West'],
    ['Vereinte', 'Nationen als Weltorganisation'],

    ['Zeus', 'Höchster Gott der Griechen'],
    ['Hera', 'Gattin des Zeus'],
    ['Apollon', 'Griechischer Gott des Lichts'],
    ['Athene', 'Göttin der Weisheit'],
    ['Poseidon', 'Griechischer Gott des Meeres'],
    ['Hades', 'Gott der Unterwelt'],
    ['Hermes', 'Bote der Götter'],
    ['Aphrodite', 'Göttin der Liebe'],
    ['Jupiter', 'Höchster Gott der Römer'],
    ['Merkur', 'Römischer Götterbote'],
    ['Odin', 'Höchster Gott der Germanen'],
    ['Thor', 'Germanischer Donnergott'],
    ['Walhalla', 'Halle der gefallenen Helden'],
    ['Olymp', 'Sitz der griechischen Götter'],
    ['Titan', 'Riese der griechischen Sage'],
    ['Zyklop', 'Riese mit einem Auge'],
    ['Zentaur', 'Wesen halb Mensch halb Pferd'],
    ['Sirene', 'Verführerisches Meerwesen'],
    ['Drache', 'Feuerspeiendes Fabeltier'],
    ['Einhorn', 'Pferd mit einem Horn'],
    ['Phoenix', 'Vogel, der aus der Asche steigt'],
    ['Greif', 'Wesen aus Adler und Löwe'],
    ['Troll', 'Wesen der nordischen Sage'],
    ['Elf', 'Zartes Fabelwesen'],
    ['Zwerg', 'Kleines Wesen im Berg'],
    ['Riese', 'Sehr grosses Fabelwesen'],
    ['Hexe', 'Zauberin im Märchen'],
    ['Fee', 'Gute Zaubergestalt'],
    ['Kobold', 'Neckischer Hausgeist'],
    ['Vampir', 'Blutsauger der Sage'],
    ['Labyrinth', 'Irrgarten des Minotaurus'],
    ['Odyssee', 'Lange Irrfahrt'],
    ['Ikarus', 'Flieger, der der Sonne zu nah kam'],
    ['Achilles', 'Held mit verwundbarer Ferse'],
    ['Herkules', 'Held der zwölf Aufgaben'],
    ['Orakel', 'Weissagende Stätte'],

    ['Mathematik', 'Wissenschaft der Zahlen'],
    ['Physik', 'Wissenschaft der Naturgesetze'],
    ['Chemie', 'Wissenschaft der Stoffe'],
    ['Biologie', 'Wissenschaft vom Leben'],
    ['Geologie', 'Wissenschaft von der Erde'],
    ['Astronomie', 'Wissenschaft der Gestirne'],
    ['Philosophie', 'Wissenschaft vom Denken'],
    ['Psychologie', 'Wissenschaft der Seele'],
    ['Archaeologie', 'Wissenschaft der Ausgrabungen'],
    ['Medizin', 'Wissenschaft der Heilkunde'],
    ['Summe', 'Ergebnis der Addition'],
    ['Differenz', 'Ergebnis der Subtraktion'],
    ['Produkt', 'Ergebnis der Multiplikation'],
    ['Quotient', 'Ergebnis der Division'],
    ['Bruch', 'Zahl mit Zähler und Nenner'],
    ['Prozent', 'Hundertstel'],
    ['Gleichung', 'Ausdruck mit Gleichheitszeichen'],
    ['Formel', 'Kurzschreibweise einer Regel'],
    ['Wurzel', 'Umkehrung des Quadrierens'],
    ['Quadrat', 'Viereck mit gleichen Seiten'],
    ['Rechteck', 'Viereck mit rechten Winkeln'],
    ['Dreieck', 'Figur mit drei Ecken'],
    ['Kreis', 'Runde Figur'],
    ['Kugel', 'Runder Körper'],
    ['Wuerfelform', 'Körper aus sechs Quadraten'],
    ['Zylinder', 'Körper wie eine Dose'],
    ['Kegel', 'Körper mit runder Grundfläche und Spitze'],
    ['Winkel', 'Von zwei Strahlen eingeschlossen'],
    ['Radius', 'Abstand vom Kreismittelpunkt'],
    ['Durchmesser', 'Strecke durch den Kreismittelpunkt'],
    ['Umfang', 'Länge der Randlinie'],
    ['Flaeche', 'Zweidimensionale Ausdehnung'],
    ['Volumen', 'Rauminhalt'],
    ['Statistik', 'Lehre von den Daten'],
    ['Diagramm', 'Grafische Darstellung von Zahlen'],

    ['Schule', 'Ort des Lernens'],
    ['Klasse', 'Gruppe von Schülern'],
    ['Lehrer', 'Wer unterrichtet'],
    ['Schueler', 'Wer lernt'],
    ['Tafel', 'Schreibfläche im Klassenzimmer'],
    ['Kreide', 'Womit man an die Tafel schreibt'],
    ['Heft', 'Gebundene Blätter zum Schreiben'],
    ['Stift', 'Gerät zum Schreiben'],
    ['Bleistift', 'Stift mit Graphitmine'],
    ['Radiergummi', 'Womit man Geschriebenes tilgt'],
    ['Lineal', 'Gerät für gerade Linien'],
    ['Zirkel', 'Gerät für Kreise'],
    ['Taschenrechner', 'Gerät zum Rechnen'],
    ['Hausaufgabe', 'Arbeit für zu Hause'],
    ['Zeugnis', 'Bescheinigung der Leistungen'],
    ['Note', 'Bewertung der Leistung'],
    ['Pruefung', 'Test des Wissens'],
    ['Diplom', 'Akademischer Abschluss'],
    ['Universitaet', 'Hochschule'],
    ['Vorlesung', 'Vortrag an der Hochschule'],
    ['Studium', 'Ausbildung an der Hochschule'],
    ['Professor', 'Hochschullehrer'],
    ['Forschung', 'Suche nach neuen Erkenntnissen'],
    ['Experiment', 'Wissenschaftlicher Versuch'],
    ['Theorie', 'Erklärendes Gedankengebäude'],
    ['Beweis', 'Zwingende Begründung'],
    ['Erfindung', 'Neu geschaffene Lösung'],
    ['Patent', 'Schutzrecht für eine Erfindung'],

    ['Computer', 'Elektronische Rechenmaschine'],
    ['Bildschirm', 'Anzeigegerät'],
    ['Tastatur', 'Gerät mit Tasten'],
    ['Drucker', 'Gerät für Papierausgabe'],
    ['Festplatte', 'Speicher im Computer'],
    ['Programm', 'Anweisungsfolge für den Rechner'],
    ['Software', 'Programme eines Rechners'],
    ['Hardware', 'Geräteteile eines Rechners'],
    ['Internet', 'Weltweites Datennetz'],
    ['Netzwerk', 'Verbundene Rechner'],
    ['Server', 'Rechner, der Dienste bereitstellt'],
    ['Datei', 'Gespeicherte Einheit von Daten'],
    ['Ordner', 'Behälter für Dateien'],
    ['Passwort', 'Geheimes Kennwort'],
    ['Virusprogramm', 'Schädliches Computerprogramm'],
    ['Roboter', 'Programmierbare Maschine'],
    ['Algorithmus', 'Rechenvorschrift'],
    ['Daten', 'Gespeicherte Angaben'],
    ['Handy', 'Mobiltelefon'],
    ['Telefon', 'Gerät zum Fernsprechen'],
    ['Kabel', 'Leitung für Strom oder Daten'],
    ['Akku', 'Wiederaufladbare Batterie'],
    ['Bildpunkt', 'Kleinstes Element des Bildes']
  ]
}
