import type { Category } from './index'

export const geografie: Category = {
  id: 'geografie',
  label: 'Geografie',
  entries: [
    ['Paris', 'Hauptstadt von Frankreich'],
    ['Rom', 'Hauptstadt von Italien'],
    ['Madrid', 'Hauptstadt von Spanien'],
    ['Lissabon', 'Hauptstadt von Portugal'],
    ['Berlin', 'Hauptstadt von Deutschland'],
    ['Wien', 'Hauptstadt von Österreich'],
    ['Bern', 'Hauptstadt der Schweiz'],
    ['Prag', 'Hauptstadt von Tschechien'],
    ['Warschau', 'Hauptstadt von Polen'],
    ['Budapest', 'Hauptstadt von Ungarn'],
    ['Athen', 'Hauptstadt von Griechenland'],
    ['Ankara', 'Hauptstadt der Türkei'],
    ['Moskau', 'Hauptstadt von Russland'],
    ['Kiew', 'Hauptstadt der Ukraine'],
    ['Oslo', 'Hauptstadt von Norwegen'],
    ['Stockholm', 'Hauptstadt von Schweden'],
    ['Helsinki', 'Hauptstadt von Finnland'],
    ['Kopenhagen', 'Hauptstadt von Dänemark'],
    ['Dublin', 'Hauptstadt von Irland'],
    ['London', 'Hauptstadt von England'],
    ['Amsterdam', 'Hauptstadt der Niederlande'],
    ['Bruessel', 'Hauptstadt von Belgien'],
    ['Luxemburg', 'Kleinstaat zwischen Deutschland und Frankreich'],
    ['Zagreb', 'Hauptstadt von Kroatien'],
    ['Belgrad', 'Hauptstadt von Serbien'],
    ['Sofia', 'Hauptstadt von Bulgarien'],
    ['Bukarest', 'Hauptstadt von Rumänien'],
    ['Riga', 'Hauptstadt von Lettland'],
    ['Tallinn', 'Hauptstadt von Estland'],
    ['Vilnius', 'Hauptstadt von Litauen'],
    ['Minsk', 'Hauptstadt von Belarus'],
    ['Reykjavik', 'Hauptstadt von Island'],
    ['Valletta', 'Hauptstadt von Malta'],
    ['Nikosia', 'Hauptstadt von Zypern'],
    ['Tirana', 'Hauptstadt von Albanien'],
    ['Sarajevo', 'Hauptstadt von Bosnien'],
    ['Ljubljana', 'Hauptstadt von Slowenien'],
    ['Bratislava', 'Hauptstadt der Slowakei'],
    ['Monaco', 'Zwergstaat an der Côte d Azur'],
    ['Andorra', 'Zwergstaat in den Pyrenäen'],
    ['Vatikan', 'Kleinster Staat der Welt'],
    ['Kairo', 'Hauptstadt von Ägypten'],
    ['Rabat', 'Hauptstadt von Marokko'],
    ['Tunis', 'Hauptstadt von Tunesien'],
    ['Algier', 'Hauptstadt von Algerien'],
    ['Nairobi', 'Hauptstadt von Kenia'],
    ['Pretoria', 'Regierungssitz Südafrikas'],
    ['Lagos', 'Grösste Stadt Nigerias'],
    ['Accra', 'Hauptstadt von Ghana'],
    ['Dakar', 'Hauptstadt des Senegal'],
    ['Tokio', 'Hauptstadt von Japan'],
    ['Peking', 'Hauptstadt von China'],
    ['Seoul', 'Hauptstadt von Südkorea'],
    ['Bangkok', 'Hauptstadt von Thailand'],
    ['Hanoi', 'Hauptstadt von Vietnam'],
    ['Manila', 'Hauptstadt der Philippinen'],
    ['Jakarta', 'Hauptstadt von Indonesien'],
    ['Delhi', 'Hauptstadt von Indien'],
    ['Teheran', 'Hauptstadt des Iran'],
    ['Bagdad', 'Hauptstadt des Irak'],
    ['Damaskus', 'Hauptstadt von Syrien'],
    ['Beirut', 'Hauptstadt des Libanon'],
    ['Kabul', 'Hauptstadt von Afghanistan'],
    ['Islamabad', 'Hauptstadt von Pakistan'],
    ['Ottawa', 'Hauptstadt von Kanada'],
    ['Havanna', 'Hauptstadt von Kuba'],
    ['Lima', 'Hauptstadt von Peru'],
    ['Santiago', 'Hauptstadt von Chile'],
    ['Bogota', 'Hauptstadt von Kolumbien'],
    ['Caracas', 'Hauptstadt von Venezuela'],
    ['Quito', 'Hauptstadt von Ecuador'],
    ['Brasilia', 'Hauptstadt von Brasilien'],
    ['Montevideo', 'Hauptstadt von Uruguay'],
    ['Canberra', 'Hauptstadt Australiens'],
    ['Wellington', 'Hauptstadt Neuseelands'],

    ['Frankreich', 'Land des Eiffelturms'],
    ['Italien', 'Land in Stiefelform'],
    ['Spanien', 'Land des Flamenco'],
    ['Portugal', 'Westlichstes Land Europas'],
    ['Griechenland', 'Wiege der Demokratie'],
    ['Norwegen', 'Land der Fjorde'],
    ['Island', 'Insel der Geysire'],
    ['Irland', 'Die grüne Insel'],
    ['Schottland', 'Land der Dudelsäcke'],
    ['Wales', 'Landesteil Grossbritanniens mit dem Drachen im Wappen'],
    ['Polen', 'Nachbarland im Osten Deutschlands'],
    ['Tschechien', 'Heimat des Pilsener Biers'],
    ['Ungarn', 'Land des Gulasch'],
    ['Kroatien', 'Land an der Adria'],
    ['Schweden', 'Heimat von Astrid Lindgren'],
    ['Finnland', 'Land der tausend Seen'],
    ['Daenemark', 'Nördlicher Nachbar Deutschlands'],
    ['Niederlande', 'Land der Tulpen und Windmühlen'],
    ['Belgien', 'Land der Pommes und Pralinen'],
    ['Schweiz', 'Alpenland mit vier Amtssprachen'],
    ['Oesterreich', 'Alpenrepublik mit Wien als Hauptstadt'],
    ['Tuerkei', 'Land auf zwei Kontinenten'],
    ['Aegypten', 'Land der Pyramiden'],
    ['Marokko', 'Land im Nordwesten Afrikas'],
    ['Kenia', 'Land der Safaris'],
    ['Japan', 'Land der aufgehenden Sonne'],
    ['China', 'Land der Grossen Mauer'],
    ['Indien', 'Land des Taj Mahal'],
    ['Thailand', 'Land des Lächelns'],
    ['Vietnam', 'Land in Südostasien'],
    ['Australien', 'Kontinent und Land zugleich'],
    ['Brasilien', 'Grösstes Land Südamerikas'],
    ['Argentinien', 'Heimat des Tango'],
    ['Mexiko', 'Land der Sombreros'],
    ['Kanada', 'Land des Ahornblatts'],
    ['Peru', 'Land der Inka'],
    ['Chile', 'Schmales Land am Pazifik'],
    ['Kuba', 'Karibikinsel der Zigarren'],
    ['Jamaika', 'Heimat des Reggae'],
    ['Israel', 'Staat am Toten Meer'],

    ['Europa', 'Kontinent mit Deutschland'],
    ['Afrika', 'Kontinent mit der Sahara'],
    ['Asien', 'Grösster Kontinent'],
    ['Antarktis', 'Kontinent am Südpol'],
    ['Ozeanien', 'Inselwelt im Pazifik'],

    ['Rhein', 'Längster Fluss Deutschlands'],
    ['Donau', 'Fluss durch Wien und Budapest'],
    ['Elbe', 'Fluss durch Hamburg'],
    ['Main', 'Fluss durch Frankfurt'],
    ['Mosel', 'Nebenfluss des Rheins, bekannt für Wein'],
    ['Weser', 'Fluss durch Bremen'],
    ['Oder', 'Grenzfluss zu Polen'],
    ['Spree', 'Fluss durch Berlin'],
    ['Isar', 'Fluss durch München'],
    ['Neckar', 'Fluss durch Heidelberg'],
    ['Seine', 'Fluss durch Paris'],
    ['Themse', 'Fluss durch London'],
    ['Tiber', 'Fluss durch Rom'],
    ['Wolga', 'Längster Fluss Europas'],
    ['Nil', 'Längster Fluss Afrikas'],
    ['Amazonas', 'Wasserreichster Fluss der Erde'],
    ['Kongo', 'Grosser Fluss in Zentralafrika'],
    ['Ganges', 'Heiliger Fluss Indiens'],
    ['Jangtse', 'Längster Fluss Chinas'],
    ['Mississippi', 'Grosser Strom der USA'],
    ['Ebro', 'Fluss in Spanien'],
    ['Loire', 'Längster Fluss Frankreichs'],
    ['Po', 'Längster Fluss Italiens'],

    ['Alpen', 'Höchstes Gebirge Europas'],
    ['Anden', 'Längstes Gebirge der Welt'],
    ['Himalaya', 'Gebirge mit dem Mount Everest'],
    ['Pyrenaeen', 'Gebirge zwischen Frankreich und Spanien'],
    ['Karpaten', 'Gebirge in Osteuropa'],
    ['Ural', 'Gebirge zwischen Europa und Asien'],
    ['Kaukasus', 'Gebirge am Schwarzen Meer'],
    ['Harz', 'Mittelgebirge mit dem Brocken'],
    ['Eifel', 'Mittelgebirge westlich des Rheins'],
    ['Taunus', 'Mittelgebirge bei Frankfurt'],
    ['Rhoen', 'Mittelgebirge in Hessen und Bayern'],
    ['Schwarzwald', 'Mittelgebirge im Südwesten Deutschlands'],
    ['Zugspitze', 'Höchster Berg Deutschlands'],
    ['Brocken', 'Höchster Berg im Harz'],
    ['Matterhorn', 'Berühmter Berg im Wallis'],
    ['Montblanc', 'Höchster Berg der Alpen'],
    ['Everest', 'Höchster Berg der Erde'],
    ['Kilimandscharo', 'Höchster Berg Afrikas'],
    ['Fudschijama', 'Heiliger Berg Japans'],
    ['Aetna', 'Vulkan auf Sizilien'],
    ['Vesuv', 'Vulkan bei Neapel'],
    ['Stromboli', 'Ständig aktiver Vulkan in Italien'],
    ['Krater', 'Trichter am Vulkangipfel'],
    ['Lava', 'Glühender Auswurf eines Vulkans'],
    ['Gletscher', 'Langsam fliessendes Eis im Gebirge'],
    ['Fjord', 'Schmale Meeresbucht in Norwegen'],
    ['Delta', 'Verzweigte Flussmündung'],
    ['Oase', 'Wasserstelle in der Wüste'],
    ['Duene', 'Sandhügel am Strand'],
    ['Riff', 'Unterwasserfelsen vor der Küste'],
    ['Atoll', 'Ringförmige Koralleninsel'],
    ['Bucht', 'Einschnitt der Küste'],
    ['Kap', 'Vorspringende Landspitze'],
    ['Insel', 'Vom Wasser umschlossenes Land'],
    ['Halbinsel', 'Land, das ins Meer ragt'],
    ['Landenge', 'Schmale Landverbindung'],
    ['Steppe', 'Weite Grasebene'],
    ['Tundra', 'Kalte baumlose Landschaft'],
    ['Savanne', 'Grasland mit einzelnen Bäumen'],
    ['Wueste', 'Sehr trockene Landschaft'],
    ['Sahara', 'Grösste Trockenwüste der Erde'],
    ['Gobi', 'Wüste in der Mongolei'],
    ['Dschungel', 'Dichter tropischer Wald'],
    ['Urwald', 'Unberührter Wald'],
    ['Moor', 'Nasses Sumpfgebiet'],
    ['Sumpf', 'Feuchtes, morastiges Gelände'],
    ['Schlucht', 'Enges, tiefes Tal'],
    ['Canyon', 'Tiefe Felsschlucht'],
    ['Plateau', 'Hochebene'],
    ['Ebene', 'Flaches Land'],
    ['Tal', 'Senke zwischen Bergen'],
    ['Huegel', 'Kleine Erhebung'],
    ['Gipfel', 'Höchster Punkt eines Berges'],
    ['Pass', 'Übergang über ein Gebirge'],

    ['Atlantik', 'Ozean zwischen Europa und Amerika'],
    ['Pazifik', 'Grösster Ozean'],
    ['Nordsee', 'Meer vor Hamburg und Holland'],
    ['Ostsee', 'Meer zwischen Deutschland und Schweden'],
    ['Mittelmeer', 'Meer zwischen Europa und Afrika'],
    ['Karibik', 'Meer der Antillen'],
    ['Adria', 'Meer zwischen Italien und Kroatien'],
    ['Aegaeis', 'Meer zwischen Griechenland und der Türkei'],
    ['Bodensee', 'Grösster See Deutschlands'],
    ['Chiemsee', 'Bayerisches Meer'],
    ['Baikalsee', 'Tiefster See der Erde'],
    ['Genfersee', 'See zwischen Schweiz und Frankreich'],

    ['Muenchen', 'Stadt des Oktoberfests'],
    ['Hamburg', 'Stadt mit dem grössten deutschen Hafen'],
    ['Koeln', 'Stadt mit dem berühmten Dom am Rhein'],
    ['Dresden', 'Elbflorenz'],
    ['Leipzig', 'Stadt der Buchmesse'],
    ['Bremen', 'Stadt der Stadtmusikanten'],
    ['Stuttgart', 'Landeshauptstadt Baden-Württembergs'],
    ['Hannover', 'Landeshauptstadt Niedersachsens'],
    ['Duesseldorf', 'Landeshauptstadt Nordrhein-Westfalens'],
    ['Mainz', 'Landeshauptstadt von Rheinland-Pfalz'],
    ['Erfurt', 'Landeshauptstadt Thüringens'],
    ['Magdeburg', 'Landeshauptstadt Sachsen-Anhalts'],
    ['Kiel', 'Landeshauptstadt Schleswig-Holsteins'],
    ['Schwerin', 'Landeshauptstadt Mecklenburg-Vorpommerns'],
    ['Potsdam', 'Landeshauptstadt Brandenburgs'],
    ['Nuernberg', 'Frankenstadt mit Christkindlesmarkt'],
    ['Heidelberg', 'Stadt mit berühmter Schlossruine am Neckar'],
    ['Rostock', 'Hansestadt an der Ostsee'],
    ['Freiburg', 'Stadt am Rand des Schwarzwalds'],
    ['Aachen', 'Kaiserstadt im Dreiländereck'],
    ['Trier', 'Älteste Stadt Deutschlands'],
    ['Regensburg', 'Stadt mit der Steinernen Brücke'],
    ['Salzburg', 'Geburtsstadt Mozarts'],
    ['Innsbruck', 'Tiroler Landeshauptstadt'],
    ['Zuerich', 'Grösste Stadt der Schweiz'],
    ['Genf', 'Schweizer Stadt der UNO'],
    ['Basel', 'Schweizer Stadt am Rheinknie'],
    ['Venedig', 'Stadt der Kanäle und Gondeln'],
    ['Florenz', 'Stadt der Renaissance'],
    ['Neapel', 'Stadt der Pizza'],
    ['Mailand', 'Italienische Modemetropole'],
    ['Barcelona', 'Stadt der Sagrada Familia'],
    ['Sevilla', 'Andalusische Stadt'],
    ['Porto', 'Portugiesische Hafenstadt'],
    ['Marseille', 'Französische Hafenstadt'],
    ['Nizza', 'Stadt an der Côte d Azur'],
    ['Lyon', 'Französische Stadt der Gastronomie'],
    ['Istanbul', 'Stadt am Bosporus'],
    ['Jerusalem', 'Heilige Stadt dreier Religionen'],
    ['Dubai', 'Emirat mit dem Burj Khalifa'],
    ['Shanghai', 'Grösste Stadt Chinas'],
    ['Sydney', 'Stadt mit dem berühmten Opernhaus'],
    ['Chicago', 'Windy City'],
    ['Boston', 'Stadt in Neuengland'],
    ['Toronto', 'Grösste Stadt Kanadas'],
    ['Montreal', 'Französischsprachige Stadt Kanadas'],

    ['Sizilien', 'Grösste Insel im Mittelmeer'],
    ['Sardinien', 'Italienische Mittelmeerinsel'],
    ['Korsika', 'Geburtsinsel Napoleons'],
    ['Kreta', 'Grösste griechische Insel'],
    ['Mallorca', 'Grösste Baleareninsel'],
    ['Ibiza', 'Baleareninsel der Clubs'],
    ['Teneriffa', 'Grösste Kanareninsel'],
    ['Ruegen', 'Grösste deutsche Insel'],
    ['Sylt', 'Nordfriesische Ferieninsel'],
    ['Borkum', 'Ostfriesische Insel'],
    ['Helgoland', 'Rote Felseninsel in der Nordsee'],
    ['Madagaskar', 'Grosse Insel vor Afrika'],
    ['Grönland', 'Grösste Insel der Welt'],
    ['Hawaii', 'Inselstaat der USA im Pazifik'],
    ['Bali', 'Indonesische Ferieninsel'],
    ['Zypern', 'Geteilte Mittelmeerinsel'],

    ['Bayern', 'Grösstes deutsches Bundesland'],
    ['Hessen', 'Bundesland mit Wiesbaden als Hauptstadt'],
    ['Saarland', 'Kleinstes Flächenbundesland'],
    ['Thueringen', 'Das grüne Herz Deutschlands'],
    ['Sachsen', 'Bundesland mit Dresden als Hauptstadt'],
    ['Brandenburg', 'Bundesland rund um Berlin'],
    ['Westfalen', 'Landesteil im Nordwesten'],
    ['Franken', 'Region im Norden Bayerns'],
    ['Schwaben', 'Region im Südwesten'],
    ['Allgaeu', 'Voralpenregion im Süden'],
    ['Ruhrgebiet', 'Grosser Ballungsraum an der Ruhr'],
    ['Toskana', 'Italienische Region um Florenz'],
    ['Sizilianer', 'Bewohner der grössten Mittelmeerinsel'],
    ['Bretagne', 'Region im Nordwesten Frankreichs'],
    ['Normandie', 'Französische Küstenregion'],
    ['Provence', 'Südfranzösische Region'],
    ['Andalusien', 'Südspanische Region'],
    ['Katalonien', 'Region um Barcelona'],
    ['Bayreuth', 'Fränkische Festspielstadt'],
    ['Tirol', 'Österreichisches Bundesland'],
    ['Wallis', 'Schweizer Kanton mit dem Matterhorn'],
    ['Sibirien', 'Weite Region im Norden Asiens'],
    ['Patagonien', 'Region im Süden Südamerikas'],
    ['Skandinavien', 'Nordeuropäische Region'],
    ['Balkan', 'Südosteuropäische Halbinsel'],
    ['Iberien', 'Halbinsel mit Spanien und Portugal'],

    ['Aequator', 'Nulllinie der Breitengrade'],
    ['Nordpol', 'Nördlichster Punkt der Erde'],
    ['Suedpol', 'Südlichster Punkt der Erde'],
    ['Tropen', 'Heisse Zone um den Äquator'],
    ['Atlas', 'Buch mit Landkarten'],
    ['Globus', 'Kugelmodell der Erde'],
    ['Kompass', 'Gerät zur Richtungsbestimmung'],
    ['Norden', 'Himmelsrichtung zum Polarstern'],
    ['Sueden', 'Himmelsrichtung gegenüber dem Norden'],
    ['Osten', 'Himmelsrichtung des Sonnenaufgangs'],
    ['Westen', 'Himmelsrichtung des Sonnenuntergangs'],
    ['Meridian', 'Längenkreis auf der Erde'],
    ['Breitengrad', 'Waagerechte Linie auf dem Globus'],
    ['Zeitzone', 'Gebiet mit gleicher Uhrzeit'],
    ['Grenze', 'Trennlinie zwischen Staaten'],
    ['Hauptstadt', 'Regierungssitz eines Landes'],
    ['Metropole', 'Sehr grosse Stadt'],
    ['Provinz', 'Verwaltungsgebiet, auch: ländliche Gegend'],
    ['Kanton', 'Gliedstaat der Schweiz'],
    ['Bundesland', 'Gliedstaat Deutschlands'],
    ['Kolonie', 'Von einem anderen Staat beherrschtes Gebiet'],
    ['Archipel', 'Inselgruppe'],
    ['Kontinent', 'Erdteil'],
    ['Ozean', 'Weltmeer'],
    ['Kueste', 'Grenze zwischen Land und Meer'],
    ['Ufer', 'Rand eines Gewässers'],
    ['Quelle', 'Ursprung eines Flusses'],
    ['Muendung', 'Ende eines Flusses'],
    ['Wasserfall', 'Stürzendes Wasser über eine Felskante'],
    ['Stausee', 'Künstlich angestautes Gewässer'],
    ['Kanal', 'Künstliche Wasserstrasse'],
    ['Hafen', 'Anlegestelle für Schiffe'],
    ['Leuchtturm', 'Turm mit Signalfeuer an der Küste'],
    ['Bruecke', 'Bauwerk über ein Hindernis'],
    ['Tunnel', 'Unterirdischer Durchgang'],
    ['Autobahn', 'Kreuzungsfreie Schnellstrasse'],
    ['Ortsschild', 'Tafel am Ortseingang'],
    ['Landkarte', 'Zeichnerische Darstellung eines Gebiets'],
    ['Massstab', 'Verhältnis von Karte zu Wirklichkeit'],
    ['Route', 'Geplanter Weg'],
    ['Polarkreis', 'Grenze des Polartags'],
    ['Wendekreis', 'Nördlichster Stand der Sonne'],
    ['Erdbeben', 'Erschütterung des Bodens'],
    ['Tsunami', 'Riesige Flutwelle'],
    ['Lawine', 'Abgehende Schneemasse'],
    ['Duerre', 'Lange Trockenheit'],
    ['Monsun', 'Jahreszeitlicher Regenwind'],
    ['Passat', 'Beständiger Wind der Tropen'],
    ['Taifun', 'Wirbelsturm in Asien'],
    ['Hurrikan', 'Wirbelsturm in der Karibik'],
    ['Tornado', 'Kleinräumiger Wirbelsturm'],
    ['Geysir', 'Heisse Springquelle'],
    ['Therme', 'Warme Heilquelle'],
    ['Bernstein', 'Fossiles Harz von der Ostsee'],
    ['Granit', 'Hartes Tiefengestein'],
    ['Basalt', 'Dunkles Vulkangestein'],
    ['Marmor', 'Edler Kalkstein für Skulpturen'],
    ['Kalkstein', 'Gestein aus Kalk'],
    ['Sandstein', 'Verfestigter Sand'],
    ['Schiefer', 'Spaltbares Gestein für Dächer'],
    ['Kies', 'Grober Untergrund aus Steinchen'],
    ['Lehm', 'Bindiger Boden für Ziegel'],
    ['Torf', 'Brennstoff aus dem Moor'],
    ['Erz', 'Metallhaltiges Gestein'],
    ['Kohle', 'Schwarzer fossiler Brennstoff'],
    ['Erdoel', 'Schwarzes Gold'],
    ['Erdgas', 'Gasförmiger Energieträger'],
    ['Salzstock', 'Unterirdische Salzlagerstätte'],
    ['Bergwerk', 'Anlage zum Abbau von Rohstoffen'],
    ['Stollen', 'Waagerechter Gang im Bergwerk'],
    ['Steinbruch', 'Ort der Gesteinsgewinnung']
  ]
}
