import type { Category } from './index'

/**
 * The filling words.
 *
 * A Schwedenrätsel grid has no holes, so every letter sits in a word running
 * across *and* — wherever two words cross — down. That only works if the pool
 * holds many short, common words: the themed categories are written for
 * interesting questions, this one is written for the three, four and five
 * letter words the grid needs to close up.
 *
 * It is always part of the pool, whatever themes are picked, so that turning
 * themes off can never starve the generator.
 */
export const grundwortschatz: Category = {
  id: 'grundwortschatz',
  label: 'Grundwortschatz',
  always: true,
  entries: [
    // --- drei Buchstaben ---
    ['Aal', 'Schlangenförmiger Fisch'],
    ['Aas', 'Kadaver als Tierfrass'],
    ['Abc', 'Reihe der Buchstaben'],
    ['Abt', 'Vorsteher eines Klosters'],
    ['Ahn', 'Vorfahre der Familie'],
    ['Akt', 'Aufzug im Theater'],
    ['Alm', 'Weide in den Bergen'],
    ['Amt', 'Behörde mit Schalter'],
    ['Arm', 'Glied mit Ellbogen'],
    ['Art', 'Gattung im Tierreich'],
    ['Ass', 'Höchste Spielkarte'],
    ['Ast', 'Zweig am Stamm'],
    ['Aue', 'Wiese am Fluss'],
    ['Axt', 'Werkzeug zum Holzspalten'],
    ['Bad', 'Raum mit Wanne'],
    ['Bar', 'Theke für Getränke'],
    ['Bau', 'Errichtung eines Hauses'],
    ['Boa', 'Würgeschlange'],
    ['Bob', 'Schlitten im Eiskanal'],
    ['Dom', 'Grosse Bischofskirche'],
    ['Duo', 'Gruppe aus zweien'],
    ['Ehe', 'Bund fürs Leben'],
    ['Eis', 'Gefrorenes Wasser'],
    ['Elf', 'Zahl nach der zehn'],
    ['Emu', 'Australischer Laufvogel'],
    ['Erz', 'Metallhaltiges Gestein'],
    ['Fan', 'Begeisterter Anhänger'],
    ['Fee', 'Zauberwesen im Märchen'],
    ['Gas', 'Brennstoff aus der Leitung'],
    ['Gel', 'Mittel für die Frisur'],
    ['Hai', 'Räuber im Meer'],
    ['Heu', 'Getrocknetes Gras'],
    ['Hof', 'Anwesen des Bauern'],
    ['Huf', 'Fuss des Pferdes'],
    ['Jod', 'Stoff für die Schilddrüse'],
    ['Kap', 'Landspitze am Meer'],
    ['Kuh', 'Rind, das Milch gibt'],
    ['Kur', 'Aufenthalt zur Heilung'],
    ['Lid', 'Deckel über dem Auge'],
    ['Los', 'Zettel der Lotterie'],
    ['Mai', 'Fünfter Monat'],
    ['Mut', 'Gegenteil von Angst'],
    ['Not', 'Grosse Bedrängnis'],
    ['Öl', 'Fett zum Braten'],
    ['Ohr', 'Organ zum Hören'],
    ['Oma', 'Mutter der Mutter'],
    ['Opa', 'Vater des Vaters'],
    ['Ort', 'Platz auf der Karte'],
    ['Ost', 'Richtung der Sonnenaufgangs'],
    ['Pol', 'Punkt der Erdachse'],
    ['Rad', 'Rundes Teil am Wagen'],
    ['Rat', 'Guter Hinweis'],
    ['Reh', 'Scheues Waldtier'],
    ['Rum', 'Schnaps aus Zuckerrohr'],
    ['See', 'Stehendes Gewässer'],
    ['Tal', 'Senke zwischen Bergen'],
    ['Tat', 'Ausgeführte Handlung'],
    ['Tau', 'Feuchte am Morgen'],
    ['Ton', 'Klang oder Lehm'],
    ['Tor', 'Ziel beim Fussball'],
    ['Uhr', 'Zeigt die Zeit'],
    ['Uhu', 'Grosse Eule'],
    ['Wal', 'Riese im Meer'],
    ['Weg', 'Pfad durch den Wald'],
    ['Zeh', 'Teil des Fusses'],
    ['Zoo', 'Park mit Tieren'],
    ['Zug', 'Bahn auf Schienen'],
    ['Ass', 'Trumpf im Kartenspiel'],
    ['Bug', 'Vorderteil des Schiffs'],
    ['Chor', 'Gruppe von Sängern'],
    ['Eck', 'Winkel im Raum'],
    ['Fee', 'Gute Zauberin'],
    ['Flur', 'Gang in der Wohnung'],
    ['Gau', 'Alter Landbezirk'],
    ['Hut', 'Kopfschutz mit Krempe'],
    ['Job', 'Bezahlte Arbeit'],
    ['Kai', 'Ufermauer im Hafen'],
    ['Lob', 'Anerkennende Worte'],
    ['Möwe', 'Vogel an der Küste'],
    ['Nil', 'Fluss durch Ägypten'],
    ['Pass', 'Ausweis für die Reise'],
    ['Ruf', 'Lauter Zuruf'],
    ['Set', 'Zusammengehörender Satz'],
    ['Sog', 'Ziehende Strömung'],
    ['Tag', 'Zeit zwischen zwei Nächten'],
    ['Tee', 'Aufguss aus Kräutern'],
    ['Tip', 'Guter Rat beim Wetten'],
    ['Tod', 'Ende des Lebens'],
    ['Typ', 'Bestimmte Bauart'],
    ['Wut', 'Heftiger Zorn'],
    ['Zar', 'Herrscher in Russland'],
    ['Zoll', 'Abgabe an der Grenze'],

    // --- vier Buchstaben ---
    ['Abend', 'Zeit vor der Nacht'],
    ['Amsel', 'Schwarzer Singvogel'],
    ['Bach', 'Kleines fliessendes Wasser'],
    ['Bank', 'Sitz im Park'],
    ['Bart', 'Haar im Gesicht'],
    ['Baum', 'Pflanze mit Stamm'],
    ['Beil', 'Kleine Axt'],
    ['Bein', 'Glied zum Gehen'],
    ['Berg', 'Hohe Erhebung'],
    ['Bett', 'Möbel zum Schlafen'],
    ['Bier', 'Getränk mit Hopfen'],
    ['Bild', 'Werk an der Wand'],
    ['Blatt', 'Grünes am Zweig'],
    ['Blei', 'Schweres weiches Metall'],
    ['Boot', 'Kleines Wasserfahrzeug'],
    ['Buch', 'Werk mit Seiten'],
    ['Burg', 'Wehrbau des Ritters'],
    ['Dach', 'Deckel des Hauses'],
    ['Dorf', 'Kleine Ortschaft'],
    ['Dose', 'Behälter aus Blech'],
    ['Duft', 'Angenehmer Geruch'],
    ['Ebbe', 'Niedriger Wasserstand'],
    ['Efeu', 'Kletternde Grünpflanze'],
    ['Egel', 'Blutsaugender Wurm'],
    ['Ekel', 'Starker Abscheu'],
    ['Erde', 'Boden im Garten'],
    ['Esel', 'Grauer Lastträger'],
    ['Etui', 'Hülle für Brillen'],
    ['Eule', 'Vogel der Nacht'],
    ['Faden', 'Garn für die Nadel'],
    ['Fass', 'Behälter für Wein'],
    ['Feld', 'Acker des Bauern'],
    ['Fell', 'Haarkleid des Tiers'],
    ['Fest', 'Fröhliche Feier'],
    ['Film', 'Werk fürs Kino'],
    ['Fisch', 'Tier mit Kiemen'],
    ['Fluss', 'Grosses fliessendes Wasser'],
    ['Frau', 'Weiblicher Mensch'],
    ['Fuchs', 'Roter Waldräuber'],
    ['Fuss', 'Ende des Beins'],
    ['Gans', 'Grosser Wasservogel'],
    ['Garn', 'Faden zum Nähen'],
    ['Gast', 'Besucher im Haus'],
    ['Geld', 'Münzen und Scheine'],
    ['Glas', 'Durchsichtiger Werkstoff'],
    ['Gold', 'Edelmetall, gelb glänzend'],
    ['Grab', 'Ruhestätte auf dem Friedhof'],
    ['Gras', 'Grün auf der Wiese'],
    ['Halm', 'Stängel des Grases'],
    ['Hand', 'Glied mit fünf Fingern'],
    ['Hase', 'Tier mit langen Ohren'],
    ['Haus', 'Gebäude zum Wohnen'],
    ['Haut', 'Hülle des Körpers'],
    ['Heft', 'Buch zum Schreiben'],
    ['Held', 'Mutiger Retter'],
    ['Hemd', 'Kleidung mit Kragen'],
    ['Herd', 'Gerät zum Kochen'],
    ['Herz', 'Motor des Blutes'],
    ['Holz', 'Stoff aus dem Baum'],
    ['Horn', 'Waffe des Stiers'],
    ['Hund', 'Treuer Begleiter'],
    ['Igel', 'Tier mit Stacheln'],
    ['Insel', 'Land ringsum im Wasser'],
    ['Jahr', 'Zwölf Monate'],
    ['Kalb', 'Junges der Kuh'],
    ['Karte', 'Blatt für die Post'],
    ['Kern', 'Innerstes der Frucht'],
    ['Kiel', 'Unterster Teil des Schiffs'],
    ['Kies', 'Grober Sand'],
    ['Kind', 'Junger Mensch'],
    ['Kino', 'Saal für Filme'],
    ['Kleid', 'Gewand der Frau'],
    ['Koch', 'Mann am Herd'],
    ['Korb', 'Geflochtener Behälter'],
    ['Korn', 'Frucht des Getreides'],
    ['Kran', 'Hebt Lasten auf dem Bau'],
    ['Kreis', 'Runde Linie'],
    ['Kreuz', 'Zeichen des Christentums'],
    ['Krug', 'Gefäss mit Henkel'],
    ['Kunst', 'Werk des Malers'],
    ['Lack', 'Glänzender Anstrich'],
    ['Land', 'Staat auf der Karte'],
    ['Laub', 'Blätter im Herbst'],
    ['Leid', 'Grosser Kummer'],
    ['Licht', 'Helligkeit der Lampe'],
    ['Lied', 'Stück zum Singen'],
    ['Loch', 'Öffnung im Stoff'],
    ['Luft', 'Was wir atmen'],
    ['Maus', 'Kleiner grauer Nager'],
    ['Meer', 'Salziges Gewässer'],
    ['Mehl', 'Pulver für den Teig'],
    ['Milch', 'Weisses von der Kuh'],
    ['Mond', 'Trabant der Erde'],
    ['Moos', 'Weiches Grün im Wald'],
    ['Mund', 'Öffnung zum Essen'],
    ['Nacht', 'Zeit ohne Sonne'],
    ['Nadel', 'Spitzes Werkzeug zum Nähen'],
    ['Nagel', 'Wird eingeschlagen'],
    ['Nase', 'Organ zum Riechen'],
    ['Nest', 'Heim der Vögel'],
    ['Netz', 'Werkzeug des Fischers'],
    ['Nuss', 'Frucht mit harter Schale'],
    ['Obst', 'Früchte vom Baum'],
    ['Ofen', 'Wärmequelle im Zimmer'],
    ['Pakt', 'Bündnis zweier Staaten'],
    ['Park', 'Grünanlage in der Stadt'],
    ['Pech', 'Widriges Missgeschick'],
    ['Pelz', 'Warmes Fell als Mantel'],
    ['Pilz', 'Wächst nach dem Regen'],
    ['Platz', 'Freie Fläche im Ort'],
    ['Post', 'Bringt die Briefe'],
    ['Qual', 'Grosser Schmerz'],
    ['Rand', 'Äussere Kante'],
    ['Rauch', 'Steigt aus dem Kamin'],
    ['Raum', 'Zimmer im Haus'],
    ['Regen', 'Wasser aus den Wolken'],
    ['Reis', 'Korn aus Asien'],
    ['Riff', 'Klippe unter Wasser'],
    ['Ring', 'Schmuck am Finger'],
    ['Rock', 'Kleidungsstück ohne Beine'],
    ['Rose', 'Blume mit Dornen'],
    ['Rost', 'Braun auf altem Eisen'],
    ['Saal', 'Grosser Raum für Feste'],
    ['Saft', 'Getränk aus Früchten'],
    ['Salz', 'Würze aus dem Meer'],
    ['Sand', 'Feines am Strand'],
    ['Schaf', 'Liefert Wolle'],
    ['Schnee', 'Weiss im Winter'],
    ['Seil', 'Starkes Tau'],
    ['Sieb', 'Trennt Grobes vom Feinen'],
    ['Sohn', 'Männliches Kind'],
    ['Sonne', 'Stern am Tag'],
    ['Spiel', 'Zeitvertreib mit Regeln'],
    ['Stadt', 'Grosse Siedlung'],
    ['Stein', 'Hartes Stück Fels'],
    ['Stern', 'Licht am Nachthimmel'],
    ['Stuhl', 'Möbel zum Sitzen'],
    ['Tanne', 'Baum mit Nadeln'],
    ['Tier', 'Lebewesen im Wald'],
    ['Tisch', 'Möbel mit vier Beinen'],
    ['Topf', 'Gefäss zum Kochen'],
    ['Tuch', 'Stück Stoff'],
    ['Turm', 'Hohes schmales Bauwerk'],
    ['Vase', 'Gefäss für Blumen'],
    ['Vogel', 'Tier mit Federn'],
    ['Wald', 'Viele Bäume beieinander'],
    ['Wand', 'Seite des Zimmers'],
    ['Ware', 'Was verkauft wird'],
    ['Wein', 'Getränk aus Trauben'],
    ['Welt', 'Erde als Ganzes'],
    ['Wind', 'Bewegte Luft'],
    ['Wolf', 'Wilder Verwandter des Hundes'],
    ['Wolke', 'Weiss am Himmel'],
    ['Wort', 'Teil des Satzes'],
    ['Zahl', 'Ziffer zum Rechnen'],
    ['Zahn', 'Beisst im Mund'],
    ['Zelt', 'Unterkunft aus Stoff'],
    ['Ziel', 'Ende der Strecke'],
    ['Zeit', 'Läuft auf der Uhr']
  ]
}
