import type { Category } from './index'

/**
 * Sixth batch. Same job as the earlier ones — the more words the pool holds per
 * length, the more of the searched grid shapes survive the fill test in
 * `scripts/build-muster.mjs`, and the more varied the puzzles get.
 */
export const grundwortschatz6: Category = {
  id: 'grundwortschatz6',
  label: 'Grundwortschatz VI',
  always: true,
  entries: [
    ['Abzug', 'Bild vom Negativ'],
    ['Ahle', 'Werkzeug des Sattlers'],
    ['Amboss', 'Unterlage des Schmieds'],
    ['Ampfer', 'Sauer schmeckendes Wildkraut'],
    ['Angel', 'Rute mit Schnur'],
    ['Antrag', 'Bitte an die Behörde'],
    ['Ärmel', 'Teil der Jacke'],
    ['Asche', 'Bleibt vom Feuer'],
    ['Aufzug', 'Fährt in den Stock'],
    ['Auster', 'Muschel als Delikatesse'],
    ['Bagger', 'Gräbt die Grube'],
    ['Balsam', 'Lindernde Salbe'],
    ['Bandage', 'Binde um das Gelenk'],
    ['Barsch', 'Raubfisch im See'],
    ['Bastel', 'Werkeln zu Hause'],
    ['Batterie', 'Speichert Strom'],
    ['Beule', 'Delle im Blech'],
    ['Beutel', 'Kleiner Sack'],
    ['Bilanz', 'Abschluss der Firma'],
    ['Binse', 'Pflanze am Wasser'],
    ['Blende', 'Öffnung der Kamera'],
    ['Bord', 'Regalbrett'],
    ['Börse', 'Handel mit Aktien'],
    ['Bottich', 'Grosses Fass'],
    ['Brauch', 'Alte Sitte'],
    ['Bremse', 'Hält das Rad an'],
    ['Bühne', 'Wo gespielt wird'],
    ['Bulle', 'Männliches Rind'],
    ['Bunker', 'Schutzraum aus Beton'],
    ['Bürde', 'Schwere Last'],
    ['Chaos', 'Völlige Unordnung'],
    ['Charme', 'Gewinnendes Wesen'],
    ['Damm', 'Wall gegen das Wasser'],
    ['Debatte', 'Streitgespräch'],
    ['Decke', 'Oberer Abschluss des Raums'],
    ['Devise', 'Leitspruch'],
    ['Diele', 'Flur hinter der Tür'],
    ['Distanz', 'Abstand zwischen zweien'],
    ['Dolch', 'Kurze Stichwaffe'],
    ['Dompteur', 'Bändigt Raubtiere'],
    ['Dotter', 'Gelbes im Ei'],
    ['Dünger', 'Nahrung für die Pflanze'],
    ['Eiche', 'Baum der Eicheln trägt'],
    ['Eifer', 'Grosser Fleiss'],
    ['Eiter', 'Gelbes in der Wunde'],
    ['Elite', 'Auslese der Besten'],
    ['Emblem', 'Zeichen des Vereins'],
    ['Enkel', 'Kind der Tochter'],
    ['Erker', 'Ausbau mit Fenster'],
    ['Ernte', 'Einbringen des Getreides'],
    ['Espe', 'Baum mit zitternden Blättern'],
    ['Etage', 'Geschoss im Hochhaus'],
    ['Eule', 'Jagt lautlos in der Nacht'],
    ['Fahne', 'Flattert am Mast'],
    ['Falter', 'Schmetterling'],
    ['Fanfare', 'Signal der Trompete'],
    ['Farn', 'Pflanze ohne Blüte'],
    ['Fasan', 'Vogel mit langem Schwanz'],
    ['Fassade', 'Vorderseite des Hauses'],
    ['Feder', 'Schreibt mit Tinte'],
    ['Fenchel', 'Knolle für den Tee'],
    ['Ferkel', 'Junges Schwein'],
    ['Fessel', 'Kette am Gefangenen'],
    ['Feuer', 'Brennt im Kamin'],
    ['Fibel', 'Erstes Lesebuch'],
    ['Filter', 'Hält Schmutz zurück'],
    ['Firn', 'Alter Schnee im Gebirge'],
    ['Flamme', 'Züngelt aus dem Holz'],
    ['Flaute', 'Windstille auf See'],
    ['Fliese', 'Platte im Bad'],
    ['Flocke', 'Einzelnes Stück Schnee'],
    ['Fluch', 'Böse Verwünschung'],
    ['Föhre', 'Anderer Name der Kiefer'],
    ['Folge', 'Was danach kommt'],
    ['Forke', 'Gabel für das Heu'],
    ['Formel', 'Gleichung der Chemie'],
    ['Freude', 'Gehobene Stimmung'],
    ['Friede', 'Zeit ohne Krieg'],
    ['Frucht', 'Wächst am Baum'],
    ['Fuge', 'Spalt zwischen Steinen'],
    ['Funke', 'Kleines Feuerteilchen'],
    ['Furche', 'Rille im Acker'],
    ['Gabel', 'Neben dem Messer'],
    ['Galerie', 'Räume für Bilder'],
    ['Gamasche', 'Schutz über dem Schuh'],
    ['Garbe', 'Bund aus Getreide'],
    ['Garde', 'Leibwache des Fürsten'],
    ['Gatter', 'Tor aus Latten'],
    ['Gebäck', 'Süsses aus dem Ofen'],
    ['Geflügel', 'Hühner und Enten'],
    ['Gehege', 'Umzäuntes Stück im Zoo'],
    ['Geländer', 'Halt an der Treppe'],
    ['Gemälde', 'Bild mit Farbe'],
    ['Gerste', 'Getreide mit Grannen'],
    ['Gewinn', 'Was übrig bleibt'],
    ['Giebel', 'Dreieck unter dem Dach'],
    ['Gilde', 'Zunft der Kaufleute'],
    ['Glocke', 'Hängt im Kirchturm'],
    ['Grabmal', 'Stein auf dem Friedhof'],
    ['Granne', 'Borste an der Ähre'],
    ['Graupel', 'Körniger Niederschlag'],
    ['Greif', 'Fabelwesen mit Flügeln'],
    ['Grille', 'Zirpt im Sommer'],
    ['Grimm', 'Verhaltene Wut'],
    ['Grotte', 'Kleine Höhle'],
    ['Grube', 'Loch im Boden'],
    ['Gunst', 'Wohlwollen des Fürsten'],
    ['Gurgel', 'Enge im Hals'],
    ['Hafen', 'Schiffe machen fest'],
    ['Halde', 'Aufgeschütteter Hügel'],
    ['Halfter', 'Riemen am Pferdekopf'],
    ['Halm', 'Stiel des Getreides'],
    ['Hamster', 'Nager mit Backentaschen'],
    ['Handel', 'Kaufen und Verkaufen'],
    ['Harnisch', 'Rüstung des Ritters'],
    ['Haspel', 'Winde am Brunnen'],
    ['Hausrat', 'Möbel und Geschirr'],
    ['Heide', 'Weite Landschaft mit Kraut'],
    ['Heizung', 'Wärmt die Wohnung'],
    ['Helm', 'Schutz für den Kopf'],
    ['Hemmnis', 'Was den Weg versperrt'],
    ['Herberge', 'Einfaches Quartier'],
    ['Hobel', 'Nimmt Späne vom Brett'],
    ['Höcker', 'Buckel des Kamels'],
    ['Hocker', 'Sitz ohne Lehne'],
    ['Hüfte', 'Zwischen Rumpf und Bein'],
    ['Hummer', 'Krebs mit Scheren'],
    ['Hürde', 'Hindernis beim Lauf'],
    ['Hütte', 'Kleines Haus aus Holz'],
    ['Imbiss', 'Kleine Mahlzeit'],
    ['Insekt', 'Tier mit sechs Beinen'],
    ['Jauche', 'Flüssiger Dünger'],
    ['Kabel', 'Leitet den Strom'],
    ['Kaffeetasse', 'Gefäss am Morgen'],
    ['Kahn', 'Flaches Boot'],
    ['Kaimauer', 'Wand am Hafenbecken'],
    ['Kalk', 'Weiss im Wasserkocher'],
    ['Kamerad', 'Treuer Gefährte'],
    ['Kamille', 'Heilpflanze für Tee'],
    ['Kanzler', 'Chef der Regierung'],
    ['Kapelle', 'Kleine Kirche'],
    ['Kapuze', 'Haube an der Jacke'],
    ['Karaffe', 'Kanne für Wein'],
    ['Kartoffel', 'Knolle aus der Erde'],
    ['Kaserne', 'Unterkunft der Soldaten'],
    ['Kaution', 'Sicherheit in Geld'],
    ['Kerbe', 'Einschnitt im Holz'],
    ['Kessel', 'Topf für heisses Wasser'],
    ['Kiepe', 'Korb für den Rücken'],
    ['Kissen', 'Weiche Stütze'],
    ['Klammer', 'Hält Papier zusammen'],
    ['Klause', 'Einsame Behausung'],
    ['Klinke', 'Griff an der Tür'],
    ['Kloster', 'Heim der Nonnen'],
    ['Knäuel', 'Kugel aus Wolle'],
    ['Knecht', 'Helfer auf dem Hof'],
    ['Knospe', 'Vor der Blüte'],
    ['Kolonie', 'Siedlung in der Ferne'],
    ['Kompott', 'Gekochtes Obst'],
    ['Konsul', 'Vertreter des Staates'],
    ['Kontor', 'Büro des Kaufmanns'],
    ['Korsett', 'Enges Mieder'],
    ['Kreuzung', 'Wo Strassen sich treffen'],
    ['Krippe', 'Futtertrog im Stall'],
    ['Krücke', 'Stütze beim Gehen'],
    ['Kuppel', 'Rundes Dach'],
    ['Kürass', 'Brustpanzer'],
    ['Kutte', 'Gewand des Mönchs'],
    ['Lager', 'Ort für Vorräte'],
    ['Laterne', 'Leuchte am Weg'],
    ['Laube', 'Häuschen im Schrebergarten'],
    ['Lawine', 'Rutscht den Hang hinab'],
    ['Lehne', 'Rücken des Stuhls'],
    ['Leuchte', 'Gibt Licht'],
    ['Lorbeer', 'Blatt im Kranz'],
    ['Lotse', 'Führt durch die Untiefe'],
    ['Lunte', 'Zündschnur'],
    ['Lyrik', 'Dichtung in Versen'],
    ['Made', 'Larve der Fliege'],
    ['Magnet', 'Zieht Eisen an'],
    ['Malve', 'Blume mit grossen Blüten'],
    ['Manschette', 'Rand am Ärmel'],
    ['Mantel', 'Warm über der Jacke'],
    ['Marsch', 'Zug im Gleichschritt'],
    ['Matte', 'Unterlage beim Turnen'],
    ['Mauer', 'Wand ums Grundstück'],
    ['Meissel', 'Werkzeug am Stein'],
    ['Melder', 'Überbringt Nachrichten'],
    ['Messing', 'Legierung aus Kupfer und Zink'],
    ['Miene', 'Ausdruck des Gesichts'],
    ['Mieder', 'Enges Oberteil'],
    ['Mispel', 'Herbe Wildfrucht'],
    ['Mörser', 'Schale zum Zerstossen'],
    ['Motte', 'Falter im Schrank'],
    ['Mulde', 'Flache Vertiefung'],
    ['Mündung', 'Wo der Fluss endet'],
    ['Muschel', 'Zwei Schalen im Sand'],
    ['Nachbar', 'Wohnt nebenan'],
    ['Nagel', 'Wird eingeschlagen'],
    ['Narde', 'Duftende Salbe der Antike'],
    ['Nautik', 'Kunst der Schifffahrt'],
    ['Nebel', 'Dunst über der Wiese'],
    ['Niete', 'Bolzen im Blech'],
    ['Nische', 'Winkel in der Mauer'],
    ['Nudel', 'Spaghetti zum Beispiel'],
    ['Oblate', 'Dünne Waffel'],
    ['Ochse', 'Zugtier vor dem Pflug'],
    ['Ohrring', 'Schmuck am Ohr'],
    ['Palette', 'Brett des Malers'],
    ['Pantoffel', 'Schuh für zu Hause'],
    ['Parkett', 'Boden aus Holz'],
    ['Pergament', 'Beschriebene Tierhaut'],
    ['Pfeife', 'Raucht der Kapitän'],
    ['Pflaster', 'Klebt auf der Wunde'],
    ['Pflicht', 'Was getan werden muss'],
    ['Pflock', 'Eingeschlagener Pfahl'],
    ['Pilger', 'Wandert zum heiligen Ort'],
    ['Plakat', 'Aushang an der Wand'],
    ['Plombe', 'Füllung im Zahn'],
    ['Polster', 'Weiche Füllung'],
    ['Pranke', 'Tatze des Löwen'],
    ['Predigt', 'Rede von der Kanzel'],
    ['Pumpe', 'Fördert das Wasser'],
    ['Quader', 'Körper mit sechs Flächen'],
    ['Qualle', 'Glibber im Meer'],
    ['Quarz', 'Häufiges Mineral'],
    ['Quaste', 'Troddel am Vorhang'],
    ['Rabatt', 'Nachlass beim Preis'],
    ['Radler', 'Fährt mit dem Velo'],
    ['Rahmen', 'Umfasst das Gemälde'],
    ['Ranke', 'Trieb der Rebe'],
    ['Raspel', 'Grobe Reibe'],
    ['Rebell', 'Steht gegen die Macht auf'],
    ['Rechen', 'Zieht das Laub zusammen'],
    ['Reifen', 'Läuft auf der Strasse'],
    ['Reling', 'Geländer am Schiff'],
    ['Rettung', 'Hilfe in der Not'],
    ['Ricke', 'Weibliches Reh'],
    ['Riegel', 'Sperrt die Tür'],
    ['Rinne', 'Gefälle für das Wasser'],
    ['Rispe', 'Lockerer Blütenstand'],
    ['Ritze', 'Schmaler Spalt'],
    ['Rodel', 'Schlitten für den Hang'],
    ['Rohling', 'Unbearbeitetes Stück'],
    ['Rüde', 'Männlicher Hund'],
    ['Ruine', 'Verfallenes Gemäuer'],
    ['Rutsche', 'Bahn auf dem Spielplatz'],
    ['Salbei', 'Kraut für den Hals'],
    ['Sammler', 'Legt Dinge zusammen'],
    ['Sattel', 'Auf dem Rücken des Pferdes'],
    ['Schacht', 'Senkrechter Gang'],
    ['Schalter', 'Macht Licht an'],
    ['Schaum', 'Blasen auf dem Bier'],
    ['Scherbe', 'Bruchstück aus Glas'],
    ['Schiene', 'Trägt den Waggon'],
    ['Schilf', 'Rohr am Seeufer'],
    ['Schindel', 'Brettchen auf dem Dach'],
    ['Schlitten', 'Fährt über den Schnee'],
    ['Schlucht', 'Enges tiefes Tal'],
    ['Schmuck', 'Ringe und Ketten'],
    ['Schnalle', 'Verschluss am Gürtel'],
    ['Schuppe', 'Plättchen am Fisch'],
    ['Schwelle', 'Balken unter der Schiene'],
    ['Seuche', 'Krankheit vieler'],
    ['Sichel', 'Krummes Messer'],
    ['Sirup', 'Dicker süsser Saft'],
    ['Sockel', 'Unterbau der Statue'],
    ['Spange', 'Klammer im Haar'],
    ['Speiche', 'Verbindet Nabe und Felge'],
    ['Spelze', 'Hülle am Getreidekorn'],
    ['Sperre', 'Riegel gegen Durchgang'],
    ['Spinne', 'Achtbeiner im Netz'],
    ['Sporn', 'Am Stiefel des Reiters'],
    ['Spule', 'Wickel aus Draht'],
    ['Stange', 'Runder langer Stab'],
    ['Statue', 'Figur aus Stein'],
    ['Staude', 'Mehrjährige Pflanze'],
    ['Stiege', 'Schmale Treppe'],
    ['Stollen', 'Gang im Berg'],
    ['Strähne', 'Büschel Haar'],
    ['Streifen', 'Schmaler langer Teil'],
    ['Strudel', 'Wirbel im Wasser'],
    ['Stufe', 'Absatz der Treppe'],
    ['Sülze', 'Fleisch in Gelee'],
    ['Talar', 'Amtstracht des Richters'],
    ['Tapete', 'Papier an der Wand'],
    ['Tenne', 'Boden in der Scheune'],
    ['Tiegel', 'Kleiner Topf'],
    ['Tonne', 'Fass für den Abfall'],
    ['Trense', 'Gebiss im Pferdemaul'],
    ['Tresen', 'Theke im Laden'],
    ['Trichter', 'Kegel zum Einfüllen'],
    ['Trosse', 'Dickes Schiffstau'],
    ['Truhe', 'Kasten mit Deckel'],
    ['Tümpel', 'Kleiner trüber Teich'],
    ['Tunke', 'Sauce zum Fleisch'],
    ['Urne', 'Gefäss für die Asche'],
    ['Ventil', 'Regelt den Durchfluss'],
    ['Vlies', 'Fell des Schafs'],
    ['Wachtel', 'Kleiner Hühnervogel'],
    ['Waffel', 'Gebäck mit Muster'],
    ['Walze', 'Rolle der Strassenbaus'],
    ['Wanne', 'Grosses Becken'],
    ['Warte', 'Turm zum Ausschauen'],
    ['Weiher', 'Stiller kleiner Teich'],
    ['Weisheit', 'Reife Einsicht'],
    ['Werft', 'Wo Schiffe gebaut werden'],
    ['Wicke', 'Kletternde Blume'],
    ['Wiesel', 'Flinker kleiner Räuber'],
    ['Wimpel', 'Kleine schmale Fahne'],
    ['Winde', 'Hebt schwere Lasten'],
    ['Windel', 'Für den Säugling'],
    ['Wippe', 'Brett auf dem Spielplatz'],
    ['Wirbel', 'Dreht sich im Wasser'],
    ['Wolke', 'Weiss oder grau am Himmel'],
    ['Wringen', 'Wasser aus dem Tuch'],
    ['Zaster', 'Umgangssprachlich Geld'],
    ['Zeisig', 'Kleiner Finkenvogel'],
    ['Zelle', 'Raum im Gefängnis'],
    ['Zepter', 'Stab des Königs'],
    ['Zeuge', 'Hat es gesehen'],
    ['Zigarre', 'Rolle aus Tabak'],
    ['Zinne', 'Zacke der Burgmauer'],
    ['Zisterne', 'Behälter für Regenwasser'],
    ['Zither', 'Saiteninstrument der Alpen'],
    ['Zobel', 'Marder mit kostbarem Pelz'],
    ['Zucht', 'Vermehrung von Tieren'],
    ['Zunder', 'Fängt schnell Feuer'],
    ['Zwinger', 'Auslauf für Hunde']
  ]
}
