import type { Category } from './index'

/**
 * Fifth batch — three and four letter words only.
 *
 * These are the pieces a gapless grid runs out of first. Every dark cell needs
 * a word starting beside it, and the short slots are what make that possible,
 * so a grid without empty fields is built out of short words whether the pool
 * has them or not. German has only so many three letter nouns, which is why
 * this batch also reaches for abbreviations and loanwords that a solver still
 * recognises.
 */
export const grundwortschatz5: Category = {
  id: 'grundwortschatz5',
  label: 'Grundwortschatz V',
  always: true,
  entries: [
    // --- drei Buchstaben ---
    ['Bai', 'Bucht an der Küste'],
    ['Dip', 'Sauce zum Eintauchen'],
    ['Ems', 'Fluss in Niedersachsen'],
    ['Fez', 'Mütze mit Quaste'],
    ['Gag', 'Witziger Einfall'],
    ['Jet', 'Schnelles Flugzeug'],
    ['Jux', 'Scherz aus Übermut'],
    ['Koi', 'Zierfisch im Gartenteich'],
    ['Lab', 'Ferment für den Käse'],
    ['Mob', 'Aufgebrachte Menge'],
    ['Mol', 'Einheit der Stoffmenge'],
    ['Mus', 'Brei aus Früchten'],
    ['Pep', 'Schwung und Elan'],
    ['Pin', 'Stift zum Anstecken'],
    ['Pop', 'Musik für die Massen'],
    ['Pub', 'Kneipe auf englisch'],
    ['Ski', 'Brett für den Schnee'],
    ['Sos', 'Ruf in Seenot'],
    ['Spa', 'Bad zur Erholung'],
    ['Top', 'Ärmelloses Oberteil'],
    ['Van', 'Geräumiger Kleinbus'],
    ['Vip', 'Sehr wichtige Person'],
    ['Ton', 'Erde des Töpfers'],
    ['Zug', 'Bewegung beim Schach'],

    // --- vier Buchstaben ---
    ['Acht', 'Zahl vor der neun'],
    ['Adel', 'Stand der Grafen'],
    ['Amok', 'Blinder Wutlauf'],
    ['Atem', 'Luft in der Lunge'],
    ['Bahn', 'Zug auf Schienen'],
    ['Balg', 'Blasebalg der Orgel'],
    ['Bord', 'Seite des Schiffs'],
    ['Byte', 'Acht Bit'],
    ['Clan', 'Grosse Sippe'],
    ['Dock', 'Werft für Schiffe'],
    ['Ehre', 'Ansehen und Würde'],
    ['Elfe', 'Zartes Fabelwesen'],
    ['Etat', 'Plan für die Ausgaben'],
    ['Fach', 'Abteil im Schrank'],
    ['Farm', 'Hof in Übersee'],
    ['Faun', 'Waldgeist der Antike'],
    ['Flop', 'Misslungene Sache'],
    ['Flor', 'Zarter Schleier'],
    ['Gaul', 'Altes Pferd'],
    ['Geiz', 'Übertriebene Sparsamkeit'],
    ['Grat', 'Schmaler Bergkamm'],
    ['Gurt', 'Band zum Sichern'],
    ['Hain', 'Kleines Wäldchen'],
    ['Hanf', 'Faserpflanze für Seile'],
    ['Hast', 'Übertriebene Eile'],
    ['Hieb', 'Schlag mit der Klinge'],
    ['Holm', 'Längsträger der Leiter'],
    ['Jade', 'Grüner Schmuckstein'],
    ['Kitt', 'Masse für die Scheibe'],
    ['Kurs', 'Richtung des Schiffs'],
    ['Lake', 'Salzbrühe zum Einlegen'],
    ['Lein', 'Pflanze für Leinen'],
    ['Pack', 'Bündel zum Tragen'],
    ['Pein', 'Quälender Schmerz'],
    ['Pier', 'Landungsbrücke im Hafen'],
    ['Rain', 'Rand des Ackers'],
    ['Raps', 'Gelbes Feld im Frühling'],
    ['Rate', 'Teilzahlung im Monat'],
    ['Raub', 'Diebstahl mit Gewalt'],
    ['Rebe', 'Ranke mit Trauben'],
    ['Ried', 'Schilf am Ufer'],
    ['Ritt', 'Ausflug auf dem Pferd'],
    ['Russ', 'Schwarz im Schornstein'],
    ['Safe', 'Panzerschrank'],
    ['Sole', 'Salzhaltiges Wasser'],
    ['Span', 'Splitter vom Hobel'],
    ['Spuk', 'Treiben der Geister'],
    ['Stil', 'Art der Gestaltung'],
    ['Teer', 'Schwarze Masse der Strasse'],
    ['Text', 'Folge von Sätzen'],
    ['Tipp', 'Hinweis für den Wetter'],
    ['Trab', 'Gangart des Pferdes'],
    ['Trio', 'Gruppe aus dreien'],
    ['Trog', 'Futterbehälter im Stall'],
    ['Vogt', 'Verwalter im Mittelalter'],
    ['Wahn', 'Falsche feste Vorstellung'],
    ['Wehr', 'Sperre im Fluss'],
    ['Wels', 'Grosser Fisch mit Barteln'],
    ['Woge', 'Hohe Welle'],
    ['Zofe', 'Dienerin der Herrin'],
    ['Zier', 'Schmuck am Bau'],
    ['Beil', 'Werkzeug des Holzfällers'],
    ['Bord', 'Brett an der Wand'],
    ['Dose', 'Konserve aus Blech'],
    ['Fels', 'Harter nackter Stein'],
    ['Fest', 'Feier mit Gästen'],
    ['Flut', 'Steigendes Meer'],
    ['Gicht', 'Schmerz im Gelenk'],
    ['Grus', 'Zerfallenes Gestein'],
    ['Kluft', 'Tiefer Riss'],
    ['Kloss', 'Kugel aus Kartoffelteig'],
    ['Lord', 'Adliger in England'],
    ['Mole', 'Damm im Hafen'],
    ['Moor', 'Nasses Torfland'],
    ['Muff', 'Wärmer für die Hände'],
    ['Naht', 'Wo zwei Teile stossen'],
    ['Nord', 'Gegenteil von Süd'],
    ['Oheim', 'Altes Wort für Onkel'],
    ['Pfad', 'Schmaler Fussweg'],
    ['Rebus', 'Bilderrätsel'],
    ['Reck', 'Turngerät mit Stange'],
    ['Ruck', 'Plötzlicher Zug'],
    ['Saum', 'Umgeschlagene Kante'],
    ['Schar', 'Grössere Gruppe'],
    ['Seim', 'Zäher Saft'],
    ['Sold', 'Lohn des Söldners'],
    ['Spat', 'Mineral im Gestein'],
    ['Stag', 'Tau am Mast'],
    ['Stier', 'Tier in der Arena'],
    ['Sund', 'Meerenge im Norden'],
    ['Torf', 'Brennstoff aus dem Moor'],
    ['Trum', 'Stück eines Seils'],
    ['Wams', 'Alte Jacke'],
    ['Watt', 'Meeresboden bei Ebbe'],
    ['Wisent', 'Europäisches Wildrind'],
    ['Zaum', 'Riemen am Pferdekopf'],
    ['Zeug', 'Sachen ohne Namen'],
    ['Zwist', 'Streit zwischen zweien']
  ]
}
