import type { Category } from './index'

/**
 * Seventh batch, again weighted to the short end.
 *
 * Three letter words decide how many grid shapes survive: a shape needs a short
 * run wherever a dark cell would otherwise have nothing to ask about, and every
 * one of those runs is a crossing constrained from both sides. German runs out
 * of three letter nouns quickly, so this reaches for the ones everybody knows
 * from everyday life — abbreviations and loanwords included.
 */
export const grundwortschatz7: Category = {
  id: 'grundwortschatz7',
  label: 'Grundwortschatz VII',
  always: true,
  entries: [
    // --- drei Buchstaben ---
    ['Aar', 'Adler in der Dichtung'],
    ['Abo', 'Laufender Bezug'],
    ['Alk', 'Seevogel des Nordens'],
    ['Alt', 'Tiefe Frauenstimme'],
    ['App', 'Programm fürs Handy'],
    ['Bit', 'Kleinste Dateneinheit'],
    ['Dau', 'Segelschiff der Araber'],
    ['Deo', 'Mittel gegen Schweiss'],
    ['Ego', 'Das eigene Ich'],
    ['Fax', 'Kopie über die Leitung'],
    ['Fis', 'Ton über dem F'],
    ['Hit', 'Erfolgreiches Lied'],
    ['Ice', 'Schneller Zug der Bahn'],
    ['Jot', 'Buchstabe nach dem I'],
    ['Kat', 'Reinigt das Abgas'],
    ['Klo', 'Stilles Örtchen'],
    ['Log', 'Fahrtenbuch des Schiffs'],
    ['Luv', 'Dem Wind zugewandt'],
    ['Mix', 'Bunte Mischung'],
    ['Psi', 'Griechischer Buchstabe'],
    ['Rah', 'Querstange am Mast'],
    ['Sau', 'Weibliches Schwein'],
    ['Ufo', 'Unbekanntes Flugobjekt'],
    ['Uri', 'Kanton am Vierwaldstättersee'],
    ['Yin', 'Gegenstück zu Yang'],

    // --- vier bis sechs Buchstaben ---
    ['Aroma', 'Angenehmer Geschmack'],
    ['Bahre', 'Trägt den Verletzten'],
    ['Barke', 'Kleines Segelboot'],
    ['Baron', 'Adliger Herr'],
    ['Basis', 'Sichere Grundlage'],
    ['Beleg', 'Bon als Nachweis'],
    ['Bengel', 'Frecher Junge'],
    ['Beton', 'Zement mit Kies'],
    ['Biest', 'Böses Tier'],
    ['Blase', 'Luft im Wasser'],
    ['Blatt', 'Seite im Heft'],
    ['Bogen', 'Gewölbe der Brücke'],
    ['Bolzen', 'Dicker Stift aus Stahl'],
    ['Brand', 'Feuer ausser Kontrolle'],
    ['Brief', 'Nachricht auf Papier'],
    ['Brust', 'Vorderseite des Rumpfes'],
    ['Dachs', 'Gräbt seinen Bau'],
    ['Datum', 'Tag im Kalender'],
    ['Daumen', 'Hält man beim Wünschen'],
    ['Degen', 'Waffe des Fechters'],
    ['Delle', 'Vertiefung im Blech'],
    ['Diener', 'Bedient die Herrschaft'],
    ['Docht', 'Faden in der Kerze'],
    ['Dolde', 'Blütenstand des Holunders'],
    ['Drama', 'Stück fürs Theater'],
    ['Dreck', 'Schmutz am Schuh'],
    ['Dünkel', 'Eingebildeter Stolz'],
    ['Ebene', 'Flache Landschaft'],
    ['Egoist', 'Denkt nur an sich'],
    ['Eifel', 'Mittelgebirge am Rhein'],
    ['Eiche', 'Starker Laubbaum'],
    ['Eimer', 'Trägt das Wasser'],
    ['Elend', 'Bittere Not'],
    ['Elster', 'Vogel mit Hang zum Glänzenden'],
    ['Erker', 'Vorbau mit Fenstern'],
    ['Essenz', 'Kern einer Sache'],
    ['Fährte', 'Spur des Wildes'],
    ['Falke', 'Stösst im Sturzflug'],
    ['Feige', 'Frucht des Südens'],
    ['Feile', 'Werkzeug mit Hieb'],
    ['Ferne', 'Weit entfernter Ort'],
    ['Fetzen', 'Stück vom Stoff'],
    ['Filz', 'Wolle ohne Faden'],
    ['Firma', 'Betrieb mit Namen'],
    ['Flanke', 'Seite der Mannschaft'],
    ['Flaum', 'Zarte erste Federn'],
    ['Fleiss', 'Beharrliche Arbeit'],
    ['Flöte', 'Instrument mit Löchern'],
    ['Fracht', 'Ladung des Schiffs'],
    ['Frevel', 'Böse Tat'],
    ['Frist', 'Zeit bis zum Ende'],
    ['Frost', 'Kälte unter null'],
    ['Fuchs', 'Rotes Tier mit buschigem Schwanz'],
    ['Fugen', 'Zwischen den Fliesen'],
    ['Galle', 'Bitteres aus der Leber'],
    ['Gasse', 'Enger Weg zwischen Häusern'],
    ['Gaumen', 'Dach im Mund'],
    ['Gebiss', 'Alle Zähne zusammen'],
    ['Geduld', 'Ruhiges Abwarten'],
    ['Gefäss', 'Behälter für Flüssiges'],
    ['Gehalt', 'Lohn im Monat'],
    ['Geiger', 'Spielt die Violine'],
    ['Geist', 'Wesen ohne Körper'],
    ['Genick', 'Hinterer Teil des Halses'],
    ['Gerste', 'Getreide auf dem Feld'],
    ['Gesetz', 'Regel des Staates'],
    ['Gewehr', 'Waffe mit Lauf'],
    ['Gipfel', 'Höchster Punkt'],
    ['Glatze', 'Kopf ohne Haar'],
    ['Gleis', 'Zwei Schienen'],
    ['Grenze', 'Ende des Landes'],
    ['Griff', 'Henkel am Koffer'],
    ['Groll', 'Alter Zorn'],
    ['Grotte', 'Höhle am Meer'],
    ['Gulasch', 'Scharfes Fleischgericht'],
    ['Gurke', 'Grün im Salat'],
    ['Hafer', 'Korn im Müsli'],
    ['Hammel', 'Kastrierter Schafbock'],
    ['Handel', 'Geschäft mit Waren'],
    ['Harke', 'Zieht das Laub'],
    ['Hecht', 'Räuber im Süsswasser'],
    ['Hefe', 'Lässt den Teig gehen'],
    ['Heizer', 'Schaufelt die Kohle'],
    ['Hexe', 'Frau mit Zauberkraft'],
    ['Hirse', 'Kleines rundes Korn'],
    ['Hitze', 'Drückende Wärme'],
    ['Hobel', 'Werkzeug des Schreiners'],
    ['Höhle', 'Wohnung des Bären'],
    ['Honig', 'Süss von der Biene'],
    ['Horde', 'Wilde Schar'],
    ['Hügel', 'Kleiner Berg'],
    ['Hummel', 'Brummt über der Wiese'],
    ['Hunger', 'Verlangen nach Essen'],
    ['Hütte', 'Einfaches Haus'],
    ['Jubel', 'Lauter Freudenschrei'],
    ['Kabel', 'Strang aus Draht'],
    ['Käfer', 'Insekt mit Flügeldecken'],
    ['Kahn', 'Boot ohne Motor'],
    ['Kamin', 'Zug für den Rauch'],
    ['Kanne', 'Giesst den Kaffee'],
    ['Kante', 'Kante am Tisch'],
    ['Kapsel', 'Hülle der Arznei'],
    ['Karren', 'Wagen mit zwei Rädern'],
    ['Kastanie', 'Baum mit Kerzen'],
    ['Kater', 'Männliche Katze'],
    ['Kehle', 'Gang im Hals'],
    ['Keller', 'Raum für den Wein'],
    ['Kerbe', 'Einschnitt in der Rinde'],
    ['Kerze', 'Licht aus Wachs'],
    ['Kiefer', 'Baum mit langen Nadeln'],
    ['Klinge', 'Schneide des Messers'],
    ['Klippe', 'Steiler Fels am Meer'],
    ['Knabe', 'Junger Mann'],
    ['Knopf', 'Am Hemd zum Schliessen'],
    ['Kohle', 'Brennstoff aus dem Berg'],
    ['Kolben', 'Im Zylinder des Motors'],
    ['Koralle', 'Baut das Riff'],
    ['Kragen', 'Am Hals des Hemds'],
    ['Kralle', 'Scharf an der Pfote'],
    ['Kranich', 'Vogel mit langem Hals'],
    ['Kranz', 'Gebunden aus Zweigen'],
    ['Krater', 'Loch im Vulkan'],
    ['Kreide', 'Weich und weiss'],
    ['Kresse', 'Scharfes Grün aufs Brot'],
    ['Krippe', 'Trog für das Vieh'],
    ['Kruste', 'Aussen am Brot'],
    ['Kübel', 'Grosser Eimer'],
    ['Kunde', 'Käufer im Geschäft'],
    ['Küste', 'Grenze zum Meer'],
    ['Lampe', 'Hängt an der Decke'],
    ['Lanze', 'Lange Stichwaffe'],
    ['Latte', 'Schmales Brett am Zaun'],
    ['Laube', 'Schattiger Sitzplatz'],
    ['Leiter', 'Sprossen zum Steigen'],
    ['Lende', 'Fleisch vom Rücken'],
    ['Lerche', 'Singt hoch über dem Feld'],
    ['Leuchte', 'Lampe an der Wand'],
    ['Liebe', 'Starke Zuneigung'],
    ['Linde', 'Baum am Dorfplatz'],
    ['Lippe', 'Rand des Mundes'],
    ['Locke', 'Gekringeltes Haar'],
    ['Löffel', 'Isst die Suppe'],
    ['Lunge', 'Nimmt die Luft auf'],
    ['Mähne', 'Haar des Löwen'],
    ['Makel', 'Kleiner Schandfleck'],
    ['Mandel', 'Kern im Marzipan'],
    ['Marder', 'Beisst gern Kabel durch'],
    ['Marsch', 'Feuchtes Land an der Küste'],
    ['Meissel', 'Treibt in den Stein'],
    ['Melone', 'Grosse Frucht mit Kernen'],
    ['Möhre', 'Wurzel für den Hasen'],
    ['Mörser', 'Zerstösst die Körner'],
    ['Mühle', 'Dreht sich im Wind'],
    ['Mulde', 'Senke im Gelände'],
    ['Nabel', 'Mitte des Bauches'],
    ['Nadel', 'Am Zweig der Tanne'],
    ['Narbe', 'Zeichen der alten Wunde'],
    ['Nelke', 'Blume oder Gewürz'],
    ['Nessel', 'Brennt beim Anfassen'],
    ['Niere', 'Filtert das Blut'],
    ['Nudel', 'Aus Mehl und Ei'],
    ['Ochse', 'Zieht den Wagen'],
    ['Olive', 'Grün oder schwarz im Öl'],
    ['Orgel', 'Pfeifen in der Kirche'],
    ['Otter', 'Schlange oder Schwimmer'],
    ['Palme', 'Wächst am Strand'],
    ['Pappel', 'Hoher schmaler Baum'],
    ['Pfeife', 'Für den Tabak'],
    ['Pfote', 'Fuss der Katze'],
    ['Pflug', 'Wendet die Erde'],
    ['Pilger', 'Zieht nach Rom'],
    ['Pinsel', 'Streicht die Farbe'],
    ['Planke', 'Dickes Brett'],
    ['Pudel', 'Hund mit gelocktem Fell'],
    ['Quelle', 'Wo der Bach beginnt'],
    ['Rabe', 'Schwarzer kluger Vogel'],
    ['Raspel', 'Reibt das Holz'],
    ['Ratte', 'Grosser Nager'],
    ['Raupe', 'Frisst das Blatt'],
    ['Rebe', 'Wächst am Spalier'],
    ['Rechen', 'Harke des Gärtners'],
    ['Regal', 'Trägt die Bücher'],
    ['Riegel', 'Schliesst das Tor'],
    ['Rinde', 'Haut des Baumes'],
    ['Rippe', 'Bogen im Brustkorb'],
    ['Robbe', 'Liegt auf dem Fels'],
    ['Rolle', 'Zum Auf- und Abwickeln'],
    ['Rüde', 'Männlicher Hund'],
    ['Rudel', 'Schar von Hirschen'],
    ['Ruder', 'Treibt den Kahn'],
    ['Säge', 'Zähne aus Stahl'],
    ['Salbe', 'Streicht man auf die Haut'],
    ['Samen', 'Beginn der Pflanze'],
    ['Schale', 'Hülle der Nuss'],
    ['Schere', 'Zwei Klingen im Gelenk'],
    ['Schilf', 'Rohr im Sumpf'],
    ['Schnee', 'Weiss auf dem Feld'],
    ['Schuppen', 'Haus für das Werkzeug'],
    ['Segel', 'Treibt das Boot'],
    ['Seife', 'Wäscht die Hände'],
    ['Sichel', 'Schneidet das Gras'],
    ['Socke', 'Sitzt am Fuss'],
    ['Spatz', 'Vogel auf dem Dach'],
    ['Spinne', 'Sitzt im Netz'],
    ['Stange', 'Zum Festhalten im Bus'],
    ['Staude', 'Pflanze im Beet'],
    ['Stiefel', 'Reicht bis zur Wade'],
    ['Storch', 'Steht auf einem Bein'],
    ['Strauch', 'Kleiner Busch'],
    ['Stufe', 'Eine von vielen zur Tür'],
    ['Taube', 'Gurrt auf dem Dach'],
    ['Tiegel', 'Gefäss zum Schmelzen'],
    ['Tulpe', 'Blüht im April'],
    ['Ulme', 'Baum mit rauen Blättern'],
    ['Viper', 'Schlange mit Zickzack'],
    ['Waage', 'Wiegt das Gemüse'],
    ['Wachtel', 'Ruft im Getreidefeld'],
    ['Waffel', 'Gebäck im Eisen'],
    ['Weide', 'Baum mit hängenden Zweigen'],
    ['Welle', 'Läuft über den See'],
    ['Wespe', 'Sticht am Kuchen'],
    ['Wiesel', 'Klein, flink und braun'],
    ['Zange', 'Kneift und hält'],
    ['Zecke', 'Beisst sich im Fell fest'],
    ['Zeder', 'Baum im Süden'],
    ['Ziege', 'Frisst am Strauch'],
    ['Zwerg', 'Kleines Wesen im Berg']
  ]
}
