import type { Category } from './index'

/**
 * Fourth batch of filling words.
 *
 * A gapless grid is filled the way a word square is: nearly every letter is
 * constrained by two words at once, so what decides whether a grid can be
 * filled is not how many words the pool holds but how many it holds *per
 * length* — the search needs alternatives at every crossing. This batch is
 * therefore all short: four to six letters, the lengths the grid is made of.
 */
export const grundwortschatz4: Category = {
  id: 'grundwortschatz4',
  label: 'Grundwortschatz IV',
  always: true,
  entries: [
    ['Abfall', 'Was in die Tonne kommt'],
    ['Abgas', 'Kommt aus dem Auspuff'],
    ['Abtei', 'Kloster unter einem Abt'],
    ['Adler', 'Wappenvogel'],
    ['Ahorn', 'Baum mit geflügelten Samen'],
    ['Aktie', 'Anteil an einer Firma'],
    ['Alarm', 'Signal bei Gefahr'],
    ['Album', 'Buch für Fotos'],
    ['Algen', 'Grün im Wasser'],
    ['Almhütte', 'Unterkunft auf der Weide'],
    ['Alpen', 'Gebirge in der Schweiz'],
    ['Ampel', 'Rot, Gelb, Grün'],
    ['Anker', 'Hält das Schiff'],
    ['Anzug', 'Feine Kleidung des Herrn'],
    ['Apfel', 'Frucht am Baum'],
    ['Arbeit', 'Tätigkeit für Lohn'],
    ['Armut', 'Mangel an Geld'],
    ['Atlas', 'Buch mit Landkarten'],
    ['Bahre', 'Trägt den Kranken'],
    ['Balken', 'Träger aus Holz'],
    ['Banane', 'Krumme gelbe Frucht'],
    ['Basar', 'Markt im Orient'],
    ['Bauch', 'Zwischen Brust und Becken'],
    ['Becher', 'Gefäss ohne Henkel'],
    ['Becken', 'Knochen an der Hüfte'],
    ['Beere', 'Kleine weiche Frucht'],
    ['Befehl', 'Strenge Anweisung'],
    ['Beruf', 'Erlernte Tätigkeit'],
    ['Besen', 'Kehrt den Boden'],
    ['Besuch', 'Gast im Haus'],
    ['Beute', 'Fang des Räubers'],
    ['Bezirk', 'Teil einer Stadt'],
    ['Biene', 'Sammelt Nektar'],
    ['Birke', 'Baum mit weisser Rinde'],
    ['Birne', 'Frucht neben dem Apfel'],
    ['Bison', 'Wildrind der Prärie'],
    ['Blase', 'Luft unter der Haut'],
    ['Blatt', 'Grün am Zweig'],
    ['Blitz', 'Zuckt im Gewitter'],
    ['Blume', 'Bunte Pflanze im Beet'],
    ['Bluse', 'Oberteil der Frau'],
    ['Boden', 'Grund unter den Füssen'],
    ['Bogen', 'Waffe mit Sehne'],
    ['Bohne', 'Hülsenfrucht im Beet'],
    ['Bohrer', 'Macht das Loch'],
    ['Bombe', 'Sprengkörper'],
    ['Borke', 'Rinde des Baums'],
    ['Bote', 'Bringt die Nachricht'],
    ['Braten', 'Fleisch aus dem Ofen'],
    ['Braut', 'Frau am Hochzeitstag'],
    ['Brett', 'Flaches Stück Holz'],
    ['Brezel', 'Gebäck mit Schlaufe'],
    ['Brief', 'Post im Umschlag'],
    ['Brise', 'Leichter Wind'],
    ['Bruch', 'Zahl mit Nenner'],
    ['Brunnen', 'Schöpft Wasser'],
    ['Buche', 'Laubbaum mit glatter Rinde'],
    ['Bucht', 'Einschnitt der Küste'],
    ['Bügel', 'Hält das Hemd im Schrank'],
    ['Bürste', 'Hat viele Borsten'],
    ['Dachs', 'Nachttier im Bau'],
    ['Dampf', 'Heisser Nebel im Topf'],
    ['Daumen', 'Dicker Finger'],
    ['Degen', 'Klinge zum Fechten'],
    ['Delfin', 'Kluger Meeressäuger'],
    ['Denkmal', 'Erinnert an Personen'],
    ['Dichte', 'Masse pro Volumen'],
    ['Docht', 'Brennt in der Kerze'],
    ['Dohle', 'Kleiner Rabenvogel'],
    ['Donner', 'Folgt dem Blitz'],
    ['Dorsch', 'Fisch der Ostsee'],
    ['Draht', 'Dünner Metallfaden'],
    ['Dreieck', 'Figur mit drei Ecken'],
    ['Droge', 'Suchtmittel'],
    ['Düne', 'Sandhügel am Meer'],
    ['Dunkel', 'Ohne jedes Licht'],
    ['Ebene', 'Flaches Land'],
    ['Echse', 'Kriechtier mit Schuppen'],
    ['Eiche', 'Baum mit Eicheln'],
    ['Eimer', 'Gefäss mit Henkel'],
    ['Eisen', 'Metall, das rostet'],
    ['Elend', 'Grosses Unglück'],
    ['Engel', 'Bote des Himmels'],
    ['Enkel', 'Kind des Sohnes'],
    ['Ente', 'Schwimmvogel im Teich'],
    ['Erbse', 'Grüne Hülsenfrucht'],
    ['Erker', 'Vorbau am Haus'],
    ['Ernte', 'Was das Feld bringt'],
    ['Espe', 'Zitterpappel'],
    ['Essig', 'Saure Würze im Salat'],
    ['Etage', 'Stockwerk im Haus'],
    ['Fabel', 'Geschichte mit Tieren'],
    ['Faden', 'Zwirn für die Nadel'],
    ['Fähre', 'Bringt Autos über den Fluss'],
    ['Falke', 'Schneller Greifvogel'],
    ['Farbe', 'Kommt aus dem Topf des Malers'],
    ['Fasan', 'Bunter Hühnervogel'],
    ['Faust', 'Geballte Hand'],
    ['Feige', 'Süsse Frucht des Südens'],
    ['Feile', 'Glättet das Metall'],
    ['Ferse', 'Hinten am Fuss'],
    ['Fessel', 'Bindet den Gefangenen'],
    ['Fichte', 'Nadelbaum im Forst'],
    ['Fjord', 'Meeresarm in Norwegen'],
    ['Flanke', 'Seite des Körpers'],
    ['Fleck', 'Schmutz auf dem Hemd'],
    ['Flegel', 'Ungehobelter Kerl'],
    ['Fliege', 'Summt am Fenster'],
    ['Flosse', 'Steuert den Fisch'],
    ['Flügel', 'Trägt den Vogel'],
    ['Forst', 'Bewirtschafteter Wald'],
    ['Frage', 'Endet mit Fragezeichen'],
    ['Frist', 'Zeit bis zum Termin'],
    ['Fuchs', 'Schlauer Waldbewohner'],
    ['Funke', 'Springt vom Feuer'],
    ['Gabel', 'Besteck mit Zinken'],
    ['Galgen', 'Werkzeug der Hinrichtung'],
    ['Galle', 'Bitterer Saft der Leber'],
    ['Gasse', 'Enge Strasse'],
    ['Gebiet', 'Abgegrenzter Raum'],
    ['Gefahr', 'Drohendes Unheil'],
    ['Geige', 'Instrument mit Bogen'],
    ['Geier', 'Frisst Aas'],
    ['Gemüse', 'Karotten und Kohl'],
    ['Genie', 'Aussergewöhnlicher Kopf'],
    ['Gerät', 'Werkzeug oder Maschine'],
    ['Gerbe', 'Behandlung von Leder'],
    ['Gerüst', 'Steht am Bau'],
    ['Geste', 'Zeichen mit der Hand'],
    ['Gipfel', 'Spitze des Berges'],
    ['Glanz', 'Heller Schein'],
    ['Glaube', 'Vertrauen ohne Beweis'],
    ['Gleis', 'Weg des Zuges'],
    ['Glück', 'Gegenteil von Pech'],
    ['Grenze', 'Trennt zwei Länder'],
    ['Griffel', 'Stift auf der Tafel'],
    ['Grippe', 'Krankheit mit Fieber'],
    ['Groschen', 'Alte kleine Münze'],
    ['Gurke', 'Grünes Gemüse im Glas'],
    ['Gürtel', 'Hält die Hose'],
    ['Hafen', 'Liegeplatz der Schiffe'],
    ['Hafer', 'Getreide für Pferde'],
    ['Hagel', 'Eiskörner vom Himmel'],
    ['Halle', 'Grosser Raum'],
    ['Halter', 'Hält etwas fest'],
    ['Hantel', 'Gewicht im Sport'],
    ['Harfe', 'Instrument mit Saiten'],
    ['Harke', 'Rechen im Garten'],
    ['Hase', 'Tier mit Löffeln'],
    ['Haufen', 'Menge übereinander'],
    ['Hebel', 'Verstärkt die Kraft'],
    ['Hecht', 'Raubfisch im See'],
    ['Heide', 'Landschaft mit Erika'],
    ['Herde', 'Gruppe von Rindern'],
    ['Hering', 'Fisch im Fass'],
    ['Hirsch', 'Trägt ein Geweih'],
    ['Hitze', 'Grosse Wärme'],
    ['Höhle', 'Loch im Berg'],
    ['Holunder', 'Strauch mit schwarzen Beeren'],
    ['Hummel', 'Dicke pelzige Biene'],
    ['Humor', 'Sinn für Späse'],
    ['Hyäne', 'Aasfresser in Afrika'],
    ['Insel', 'Land im Meer'],
    ['Jäger', 'Geht auf die Pirsch'],
    ['Jubel', 'Lauter Freudenruf'],
    ['Jugend', 'Junge Jahre'],
    ['Kachel', 'Fliese an der Wand'],
    ['Käfer', 'Insekt mit Panzer'],
    ['Käfig', 'Gitterbehälter für Tiere'],
    ['Kamel', 'Wüstentier mit Höcker'],
    ['Kamin', 'Feuerstelle im Zimmer'],
    ['Kanal', 'Künstliche Wasserstrasse'],
    ['Kanne', 'Gefäss zum Giessen'],
    ['Kante', 'Scharfer Rand'],
    ['Kapsel', 'Kleine Hülle für Medizin'],
    ['Karpfen', 'Fisch im Teich'],
    ['Kasse', 'Zahlstelle im Laden'],
    ['Kastanie', 'Braune Frucht im Herbst'],
    ['Kegel', 'Fällt durch die Kugel'],
    ['Kehle', 'Innen im Hals'],
    ['Keller', 'Unter dem Erdgeschoss'],
    ['Kerze', 'Brennt mit Docht'],
    ['Kiefer', 'Nadelbaum oder Knochen'],
    ['Kieme', 'Atemorgan des Fisches'],
    ['Kittel', 'Arbeitsmantel'],
    ['Klasse', 'Gruppe in der Schule'],
    ['Klaue', 'Kralle des Tiers'],
    ['Klinge', 'Schneidender Teil'],
    ['Klippe', 'Fels an der Küste'],
    ['Knabe', 'Junger Bursche'],
    ['Knebel', 'Verschliesst den Mund'],
    ['Knopf', 'Verschluss am Hemd'],
    ['Kobra', 'Giftschlange mit Haube'],
    ['Kohle', 'Schwarzer Brennstoff'],
    ['Kolben', 'Bewegt sich im Zylinder'],
    ['Komet', 'Stern mit Schweif'],
    ['König', 'Herrscher mit Krone'],
    ['Konto', 'Geld bei der Bank'],
    ['Kopie', 'Genaues Abbild'],
    ['Korb', 'Geflochtenes Behältnis'],
    ['Kragen', 'Rand am Hemd'],
    ['Kralle', 'Nagel der Katze'],
    ['Krampf', 'Verhärteter Muskel'],
    ['Kranz', 'Ring aus Blumen'],
    ['Krater', 'Öffnung des Vulkans'],
    ['Kraut', 'Würzt die Suppe'],
    ['Krebs', 'Tier mit Scheren'],
    ['Kreis', 'Runde Fläche'],
    ['Kruste', 'Harte Rinde am Brot'],
    ['Kugel', 'Runder Körper'],
    ['Kummer', 'Stiller Schmerz'],
    ['Kürbis', 'Grosse orange Frucht'],
    ['Küste', 'Wo Land aufs Meer trifft'],
    ['Lachs', 'Fisch mit rotem Fleisch'],
    ['Lampe', 'Spendet Licht'],
    ['Lanze', 'Waffe des Reiters'],
    ['Lärche', 'Nadelbaum, der Nadeln verliert'],
    ['Laster', 'Schlechte Gewohnheit'],
    ['Laune', 'Stimmung des Tages'],
    ['Leber', 'Organ im Bauch'],
    ['Leder', 'Gegerbte Tierhaut'],
    ['Legende', 'Alte Erzählung'],
    ['Lehrer', 'Steht vor der Klasse'],
    ['Leiste', 'Schmales Brett'],
    ['Lilie', 'Blume mit Trichter'],
    ['Linse', 'Im Fernrohr oder im Topf'],
    ['Lippe', 'Rand des Mundes'],
    ['Liter', 'Mass für Flüssigkeit'],
    ['Lohn', 'Geld für die Arbeit'],
    ['Löwe', 'König der Tiere'],
    ['Luchs', 'Katze mit Pinselohren'],
    ['Lüge', 'Bewusst Unwahres'],
    ['Magen', 'Verdaut das Essen'],
    ['Makel', 'Kleiner Fehler'],
    ['Mandel', 'Nuss im Marzipan'],
    ['Mangel', 'Zu wenig von etwas'],
    ['Marder', 'Räuber unter der Motorhaube'],
    ['Marke', 'Klebt auf dem Brief'],
    ['Markt', 'Stände auf dem Platz'],
    ['Marmor', 'Edler Stein des Bildhauers'],
    ['Maske', 'Verbirgt das Gesicht'],
    ['Masse', 'Gewicht in Kilogramm'],
    ['Meise', 'Kleiner Gartenvogel'],
    ['Melone', 'Grosse saftige Frucht'],
    ['Menge', 'Grosse Anzahl'],
    ['Messe', 'Gottesdienst oder Ausstellung'],
    ['Meter', 'Hundert Zentimeter'],
    ['Miete', 'Zahlt der Mieter'],
    ['Mitte', 'Gleich weit von den Rändern'],
    ['Möbel', 'Tisch, Stuhl, Schrank'],
    ['Molch', 'Lurch im Teich'],
    ['Monat', 'Januar zum Beispiel'],
    ['Motor', 'Treibt das Auto an'],
    ['Motte', 'Frisst Löcher in Wolle'],
    ['Möwe', 'Vogel über dem Hafen'],
    ['Mücke', 'Sticht in der Nacht'],
    ['Mumie', 'Einbalsamierter Leichnam'],
    ['Münze', 'Geld aus Metall'],
    ['Muster', 'Sich wiederholende Form'],
    ['Mütze', 'Kopfbedeckung ohne Krempe'],
    ['Nabe', 'Mitte des Rades'],
    ['Nacken', 'Hinten am Hals'],
    ['Nadel', 'Spitz mit Öhr'],
    ['Narbe', 'Bleibt nach der Wunde'],
    ['Nebel', 'Wolke am Boden'],
    ['Neffe', 'Sohn der Schwester'],
    ['Nelke', 'Blume oder Gewürz'],
    ['Nerv', 'Leitet den Reiz'],
    ['Niere', 'Reinigt das Blut'],
    ['Nixe', 'Wesen im Wasser'],
    ['Nonne', 'Frau im Kloster'],
    ['Norden', 'Wo der Polarstern steht'],
    ['Notar', 'Beglaubigt Verträge'],
    ['Oase', 'Grün in der Wüste'],
    ['Obhut', 'Fürsorgliche Aufsicht'],
    ['Olive', 'Frucht am Mittelmeer'],
    ['Onkel', 'Bruder des Vaters'],
    ['Opfer', 'Wer Schaden erleidet'],
    ['Orgel', 'Instrument in der Kirche'],
    ['Orkan', 'Stärkster Sturm'],
    ['Otter', 'Schwimmt im Fluss'],
    ['Paket', 'Sendung im Karton'],
    ['Palme', 'Baum mit Wedeln'],
    ['Pappel', 'Schlanker Baum an der Allee'],
    ['Pause', 'Unterbrechung der Arbeit'],
    ['Pfarrer', 'Hält die Predigt'],
    ['Pfote', 'Fuss von Hund und Katze'],
    ['Pforte', 'Kleines Tor'],
    ['Pfosten', 'Senkrechter Balken'],
    ['Pfütze', 'Wasser nach dem Regen'],
    ['Pinguin', 'Vogel, der nicht fliegt'],
    ['Planet', 'Kreist um die Sonne'],
    ['Pokal', 'Preis für den Sieger'],
    ['Porzellan', 'Feines weisses Geschirr'],
    ['Presse', 'Zeitungen insgesamt'],
    ['Priester', 'Diener der Kirche'],
    ['Prinz', 'Sohn des Königs'],
    ['Pulver', 'Feiner Staub'],
    ['Punkt', 'Ende des Satzes'],
    ['Quelle', 'Ursprung des Baches'],
    ['Rahmen', 'Umgibt das Bild'],
    ['Rakete', 'Steigt zum Mond'],
    ['Ranke', 'Trieb der Kletterpflanze'],
    ['Raspel', 'Grobe Feile'],
    ['Ratte', 'Nager in der Kanalisation'],
    ['Raupe', 'Wird zum Schmetterling'],
    ['Regal', 'Bretter für Bücher'],
    ['Regel', 'Vorschrift im Spiel'],
    ['Reifen', 'Rund am Auto'],
    ['Reihe', 'Eines hinter dem anderen'],
    ['Reise', 'Fahrt in die Ferne'],
    ['Rettich', 'Scharfe weisse Wurzel'],
    ['Riese', 'Sehr grosser Kerl'],
    ['Rinde', 'Aussen am Stamm'],
    ['Rippe', 'Knochen am Brustkorb'],
    ['Robbe', 'Säuger auf dem Eis'],
    ['Roggen', 'Getreide für dunkles Brot'],
    ['Rolle', 'Zylinder zum Abwickeln'],
    ['Roman', 'Langes Erzählwerk'],
    ['Rudel', 'Gruppe von Wölfen'],
    ['Ruder', 'Bewegt das Boot'],
    ['Rüssel', 'Lange Nase'],
    ['Sabel', 'Krumme Klinge'],
    ['Säge', 'Zerteilt das Brett'],
    ['Sahne', 'Schlägt man steif'],
    ['Salat', 'Grünes in der Schüssel'],
    ['Salbe', 'Creme für die Wunde'],
    ['Samen', 'Aus ihm wächst die Pflanze'],
    ['Schale', 'Aussen um die Frucht'],
    ['Schatten', 'Dunkel hinter dem Körper'],
    ['Schatz', 'Gold in der Truhe'],
    ['Scheune', 'Lager für das Heu'],
    ['Schiff', 'Fährt über das Meer'],
    ['Schirm', 'Schützt vor Regen'],
    ['Schlamm', 'Nasse weiche Erde'],
    ['Schleuse', 'Hebt Schiffe im Kanal'],
    ['Schloss', 'Am Tor oder auf dem Berg'],
    ['Schluck', 'Menge auf einmal'],
    ['Schlüssel', 'Öffnet die Tür'],
    ['Schmerz', 'Tut weh'],
    ['Schmied', 'Arbeitet am Amboss'],
    ['Schnee', 'Fällt weiss vom Himmel'],
    ['Schnitt', 'Trennung mit der Klinge'],
    ['Schnur', 'Dünnes Band'],
    ['Scholle', 'Platter Fisch'],
    ['Schrank', 'Möbel mit Türen'],
    ['Schraube', 'Dreht sich ins Holz'],
    ['Schrift', 'Geschriebene Zeichen'],
    ['Schritt', 'Bewegung beim Gehen'],
    ['Schuld', 'Was man zurückzahlt'],
    ['Schulter', 'Zwischen Arm und Hals'],
    ['Schwan', 'Weisser Vogel auf dem See'],
    ['Schwamm', 'Saugt Wasser auf'],
    ['Schwanz', 'Hinten am Tier'],
    ['Segel', 'Fängt den Wind'],
    ['Segen', 'Wunsch des Priesters'],
    ['Sehne', 'Verbindet Muskel und Knochen'],
    ['Seife', 'Macht Schaum'],
    ['Seite', 'Blatt im Buch'],
    ['Sekunde', 'Sechzigstel Minute'],
    ['Silbe', 'Teil des Wortes'],
    ['Skizze', 'Schnelle Zeichnung'],
    ['Socke', 'Am Fuss im Schuh'],
    ['Spange', 'Schmuck im Haar'],
    ['Spanne', 'Abstand dazwischen'],
    ['Spatz', 'Frecher kleiner Vogel'],
    ['Speck', 'Fett vom Schwein'],
    ['Spende', 'Gabe für einen Zweck'],
    ['Spitze', 'Oberstes Ende'],
    ['Sporn', 'Am Stiefel des Reiters'],
    ['Sprung', 'Satz in die Höhe'],
    ['Spule', 'Trägt den Draht'],
    ['Staat', 'Land mit Regierung'],
    ['Stahl', 'Harter Werkstoff'],
    ['Stamm', 'Trägt die Krone'],
    ['Stapel', 'Bücher übereinander'],
    ['Stelze', 'Lange Gehhilfe'],
    ['Stempel', 'Drückt den Abdruck'],
    ['Stiefel', 'Hoher Schuh'],
    ['Stiel', 'Griff der Pfanne'],
    ['Stift', 'Womit man schreibt'],
    ['Stirn', 'Über den Augen'],
    ['Storch', 'Bringt angeblich die Kinder'],
    ['Strahl', 'Linie des Lichts'],
    ['Strauch', 'Busch im Garten'],
    ['Strauss', 'Grösster Vogel'],
    ['Streit', 'Heftige Auseinandersetzung'],
    ['Strom', 'Aus der Steckdose'],
    ['Stube', 'Wohnraum'],
    ['Stuhl', 'Sitz mit Lehne'],
    ['Sturm', 'Sehr starker Wind'],
    ['Suppe', 'Löffelt man aus dem Teller'],
    ['Szene', 'Auftritt im Stück'],
    ['Tafel', 'Grün im Klassenzimmer'],
    ['Tante', 'Schwester der Mutter'],
    ['Tasche', 'Trägt man am Arm'],
    ['Tasse', 'Gefäss für Kaffee'],
    ['Taube', 'Vogel des Friedens'],
    ['Taufe', 'Erstes Sakrament'],
    ['Teich', 'Kleines Gewässer'],
    ['Terrasse', 'Platz vor dem Haus'],
    ['Theke', 'Tresen im Lokal'],
    ['Tiger', 'Gestreifte Grosskatze'],
    ['Tonne', 'Tausend Kilogramm'],
    ['Torte', 'Kuchen mit Sahne'],
    ['Träne', 'Rollt über die Wange'],
    ['Traum', 'Bilder im Schlaf'],
    ['Trommel', 'Schlaginstrument'],
    ['Trotz', 'Widerstand aus Sturheit'],
    ['Tulpe', 'Frühlingsblume aus Holland'],
    ['Tunnel', 'Röhre durch den Berg'],
    ['Ufer', 'Rand des Sees'],
    ['Uhrzeit', 'Wie spät es ist'],
    ['Vater', 'Männlicher Elternteil'],
    ['Veilchen', 'Kleine violette Blume'],
    ['Ventil', 'Lässt Luft ab'],
    ['Verlust', 'Gegenteil von Gewinn'],
    ['Viper', 'Giftige Schlange'],
    ['Vogel', 'Legt Eier ins Nest'],
    ['Waage', 'Zeigt das Gewicht'],
    ['Wache', 'Passt auf'],
    ['Wange', 'Seite des Gesichts'],
    ['Watte', 'Weiche Baumwolle'],
    ['Weber', 'Macht Stoff am Webstuhl'],
    ['Weide', 'Baum am Bach'],
    ['Weizen', 'Getreide für helles Brot'],
    ['Welle', 'Bewegung im Wasser'],
    ['Welpe', 'Junger Hund'],
    ['Wespe', 'Gelbschwarzes Insekt'],
    ['Wiege', 'Schaukelbett'],
    ['Wiese', 'Grün mit Blumen'],
    ['Winter', 'Kalte Jahreszeit'],
    ['Wirbel', 'Knochen der Wirbelsäule'],
    ['Woche', 'Sieben Tage'],
    ['Wolke', 'Zieht am Himmel'],
    ['Wunder', 'Unerklärliches Ereignis'],
    ['Würfel', 'Hat sechs Seiten'],
    ['Wüste', 'Sand ohne Wasser'],
    ['Zange', 'Greift und hält'],
    ['Zebra', 'Pferd mit Streifen'],
    ['Zecke', 'Saugt Blut im Wald'],
    ['Zeder', 'Baum im Libanon'],
    ['Zeile', 'Reihe im Text'],
    ['Zelle', 'Kleinste Einheit des Lebens'],
    ['Zettel', 'Notiz auf Papier'],
    ['Zeuge', 'Sagt vor Gericht aus'],
    ['Ziegel', 'Gebrannter Lehmstein'],
    ['Zitat', 'Wörtlich übernommen'],
    ['Zunge', 'Schmeckt im Mund'],
    ['Zweig', 'Kleiner Ast']
  ]
}
