import type { Category } from './index'

/**
 * More filling words — same job as `grundwortschatz`, kept in its own file so
 * the batches stay reviewable. Written against the words already in the pool,
 * so the overlap is small; `scripts/check-woerter.mjs` reports what still slips
 * through as a duplicate.
 */
export const grundwortschatz2: Category = {
  id: 'grundwortschatz2',
  label: 'Grundwortschatz II',
  always: true,
  entries: [
    // --- kurz: drei und vier Buchstaben ---
    ['Akte', 'Sammlung von Papieren'],
    ['Anis', 'Gewürz für Weihnachtsgebäck'],
    ['Arie', 'Gesangsstück in der Oper'],
    ['Aula', 'Festsaal der Schule'],
    ['Ball', 'Rundes Spielgerät'],
    ['Band', 'Schmaler Streifen Stoff'],
    ['Bass', 'Tiefe Männerstimme'],
    ['Beet', 'Bepflanztes Stück Garten'],
    ['Bock', 'Männliche Ziege'],
    ['Bund', 'Zusammenschluss von Staaten'],
    ['Cent', 'Kleinste Münze im Euro'],
    ['Club', 'Verein mit Mitgliedern'],
    ['Deck', 'Boden auf dem Schiff'],
    ['Dieb', 'Wer heimlich nimmt'],
    ['Dill', 'Kraut zu Gurken'],
    ['Eile', 'Grosse Hast'],
    ['Eins', 'Kleinste natürliche Zahl'],
    ['Elan', 'Kraftvoller Schwung'],
    ['Epos', 'Langes Heldengedicht'],
    ['Erbe', 'Nachlass der Eltern'],
    ['Fall', 'Sturz nach unten'],
    ['Fang', 'Beute des Fischers'],
    ['Fern', 'Weit entfernt'],
    ['Filz', 'Verdichtete Wolle'],
    ['Flug', 'Reise durch die Luft'],
    ['Flut', 'Hoher Wasserstand'],
    ['Form', 'Äussere Gestalt'],
    ['Fuge', 'Spalt zwischen Fliesen'],
    ['Funk', 'Übertragung ohne Kabel'],
    ['Gabe', 'Freundliches Geschenk'],
    ['Gage', 'Lohn des Künstlers'],
    ['Gang', 'Flur im Haus'],
    ['Gier', 'Masslose Begierde'],
    ['Gift', 'Tödlicher Stoff'],
    ['Gips', 'Weisse Masse für Verbände'],
    ['Glut', 'Rest im Kaminfeuer'],
    ['Grad', 'Einheit der Temperatur'],
    ['Haft', 'Aufenthalt im Gefängnis'],
    ['Hals', 'Zwischen Kopf und Rumpf'],
    ['Heck', 'Hinterteil des Autos'],
    ['Heer', 'Truppe des Landes'],
    ['Heim', 'Eigenes Zuhause'],
    ['Herr', 'Höfliche Anrede für Männer'],
    ['Hirn', 'Denkorgan im Kopf'],
    ['Hirt', 'Hüter der Schafe'],
    ['Hupe', 'Warnt im Verkehr'],
    ['Iglu', 'Haus aus Schneeblöcken'],
    ['Info', 'Kurze Auskunft'],
    ['Iris', 'Farbiger Ring im Auge'],
    ['Jagd', 'Verfolgung des Wildes'],
    ['Joch', 'Geschirr für Ochsen'],
    ['Kahn', 'Flacher Nachen'],
    ['Kanu', 'Boot mit Stechpaddel'],
    ['Keil', 'Spitzes Stück zum Spalten'],
    ['Kerl', 'Rauer Bursche'],
    ['Kiez', 'Viertel in Berlin'],
    ['Kopf', 'Sitz des Gehirns'],
    ['Kork', 'Verschluss der Weinflasche'],
    ['Kram', 'Wertloses Zeug'],
    ['Lage', 'Ort auf der Karte'],
    ['Laib', 'Ganzes Brot'],
    ['Lauf', 'Strecke des Läufers'],
    ['Leim', 'Klebstoff für Holz'],
    ['Leib', 'Körper des Menschen'],
    ['List', 'Schlauer Trick'],
    ['Lupe', 'Glas zum Vergrössern'],
    ['Lust', 'Starkes Verlangen'],
    ['Magd', 'Helferin auf dem Hof'],
    ['Mahl', 'Feierliches Essen'],
    ['Malz', 'Gekeimtes Getreide fürs Bier'],
    ['Mark', 'Inneres im Knochen'],
    ['Mass', 'Einheit beim Messen'],
    ['Mast', 'Stange für das Segel'],
    ['Mist', 'Dünger vom Hof'],
    ['Naht', 'Verbindung zweier Stoffe'],
    ['Napf', 'Schale für den Hund'],
    ['Nord', 'Richtung zum Polarstern'],
    ['Ober', 'Kellner im Lokal'],
    ['Pfad', 'Schmaler Weg'],
    ['Plan', 'Vorhaben mit Ablauf'],
    ['Pult', 'Schreibmöbel des Lehrers'],
    ['Rahm', 'Fett auf der Milch'],
    ['Rang', 'Stufe in der Ordnung'],
    ['Rast', 'Pause auf der Wanderung'],
    ['Rohr', 'Leitung für Wasser'],
    ['Ruhe', 'Vollkommene Stille'],
    ['Ruhm', 'Grosses Ansehen'],
    ['Saat', 'Was gesät wurde'],
    ['Sack', 'Beutel aus Jute'],
    ['Saum', 'Rand am Kleid'],
    ['Sinn', 'Bedeutung eines Wortes'],
    ['Sitz', 'Platz zum Setzen'],
    ['Spur', 'Abdruck im Schnee'],
    ['Stab', 'Langer dünner Stock'],
    ['Steg', 'Schmale Brücke'],
    ['Tube', 'Behälter für Zahnpasta'],
    ['Volk', 'Bewohner eines Landes'],
    ['Werk', 'Schöpfung des Künstlers'],
    ['Wert', 'Preis einer Sache'],
    ['Wild', 'Tiere des Jägers'],
    ['Wirt', 'Chef der Gaststätte'],
    ['Wurm', 'Kriecher im Boden'],
    ['Zaun', 'Grenze um den Garten'],
    ['Zopf', 'Geflochtenes Haar'],

    // --- fünf Buchstaben ---
    ['Blech', 'Dünne Platte aus Metall'],
    ['Block', 'Papier zum Notieren'],
    ['Busch', 'Strauch im Garten'],
    ['Duell', 'Kampf zweier Gegner'],
    ['Dunst', 'Feiner Nebel'],
    ['Ernst', 'Gegenteil von Scherz'],
    ['Essen', 'Mahlzeit am Tisch'],
    ['Fahne', 'Tuch am Mast'],
    ['Feuer', 'Flamme im Kamin'],
    ['Föhn', 'Warmer Fallwind'],
    ['Geist', 'Gespenst im Schloss'],
    ['Griff', 'Henkel zum Anfassen'],
    ['Groll', 'Verhaltener Zorn'],
    ['Gruft', 'Grabkammer der Kirche'],
    ['Hauch', 'Leichter Windzug'],
    ['Imker', 'Hält Bienenvölker'],
    ['Juwel', 'Kostbarer Edelstein'],
    ['Katze', 'Schnurrt auf dem Sofa'],
    ['Kelch', 'Becher mit Fuss'],
    ['Kluft', 'Tiefer Spalt im Fels'],
    ['Kraut', 'Würzige Pflanze'],
    ['Krone', 'Schmuck des Königs'],
    ['Kunde', 'Wer im Laden kauft'],
    ['Latte', 'Schmales langes Brett'],
    ['Lotse', 'Führt Schiffe in den Hafen'],
    ['Meile', 'Längenmass der Angelsachsen'],
    ['Miene', 'Ausdruck im Gesicht'],
    ['Miete', 'Zahlung für die Wohnung'],
    ['Milbe', 'Winziges Spinnentier'],
    ['Nabel', 'Narbe auf dem Bauch'],
    ['Narbe', 'Spur einer Wunde'],
    ['Niete', 'Los ohne Gewinn'],
    ['Nudel', 'Teigware aus Italien'],
    ['Ochse', 'Kastrierter Stier'],
    ['Orden', 'Auszeichnung an der Brust'],
    ['Papst', 'Oberhaupt der Katholiken'],
    ['Pfahl', 'Eingerammter Pfosten'],
    ['Pfeil', 'Geschoss vom Bogen'],
    ['Pferd', 'Reittier mit Mähne'],
    ['Pflug', 'Gerät zum Ackern'],
    ['Pilot', 'Führer des Flugzeugs'],
    ['Probe', 'Versuch vor der Aufführung'],
    ['Puppe', 'Spielzeug im Kinderzimmer'],
    ['Rasen', 'Kurzes Gras im Garten'],
    ['Ruine', 'Rest einer alten Burg'],
    ['Seele', 'Inneres des Menschen'],
    ['Sense', 'Gerät zum Mähen'],
    ['Sorge', 'Drückende Angst'],
    ['Spalt', 'Schmale Öffnung'],
    ['Stall', 'Haus für das Vieh'],
    ['Stier', 'Männliches Rind'],
    ['Stoff', 'Material für Kleider'],
    ['Stroh', 'Trockene Halme'],
    ['Stufe', 'Tritt der Treppe'],
    ['Sucht', 'Krankhaftes Verlangen'],
    ['Taste', 'Knopf am Klavier'],
    ['Teich', 'Kleines stehendes Gewässer'],
    ['Tempo', 'Geschwindigkeit'],
    ['Tenor', 'Hohe Männerstimme'],
    ['Thron', 'Sitz des Herrschers'],
    ['Tiefe', 'Abstand nach unten'],
    ['Tinte', 'Flüssigkeit im Füller'],
    ['Toast', 'Geröstetes Brot'],
    ['Truhe', 'Kiste mit Deckel'],
    ['Wachs', 'Stoff der Bienen'],
    ['Waffe', 'Gerät zum Kämpfen'],
    ['Wagen', 'Fahrzeug mit Rädern'],
    ['Wanne', 'Gefäss zum Baden'],
    ['Wanze', 'Lästiges Ungeziefer'],
    ['Wesen', 'Art eines Menschen'],
    ['Wiese', 'Grüne Fläche mit Gras'],
    ['Wolle', 'Haar des Schafs'],
    ['Wunde', 'Verletzung der Haut'],
    ['Ziege', 'Meckert im Stall'],

    // --- sechs Buchstaben ---
    ['Ameise', 'Fleissiges Krabbeltier'],
    ['Anfang', 'Beginn einer Sache'],
    ['Balkon', 'Vorbau an der Wohnung'],
    ['Bericht', 'Schriftliche Darstellung'],
    ['Blume', 'Blüht im Beet'],
    ['Brille', 'Sehhilfe auf der Nase'],
    ['Bruder', 'Sohn derselben Eltern'],
    ['Decke', 'Wärmt im Bett'],
    ['Dichter', 'Verfasser von Versen'],
    ['Distel', 'Stachlige Wildpflanze'],
    ['Drache', 'Feuerspeiendes Untier'],
    ['Feder', 'Kleid des Vogels'],
    ['Fenster', 'Öffnung mit Glas'],
    ['Ferien', 'Freie Zeit im Sommer'],
    ['Fieber', 'Erhöhte Temperatur'],
    ['Flasche', 'Gefäss mit Hals'],
    ['Forelle', 'Fisch im klaren Bach'],
    ['Fussball', 'Sport mit elf pro Team'],
    ['Garten', 'Grün hinter dem Haus'],
    ['Gebirge', 'Kette hoher Berge'],
    ['Gedicht', 'Text in Versen'],
    ['Gewitter', 'Blitz und Donner'],
    ['Hammer', 'Werkzeug für Nägel'],
    ['Hering', 'Fisch aus der Nordsee'],
    ['Himmel', 'Blau über uns'],
    ['Hobel', 'Glättet das Holz'],
    ['Hügel', 'Kleine Erhebung'],
    ['Kabine', 'Kleiner Raum im Schiff'],
    ['Kaffee', 'Muntermacher am Morgen'],
    ['Kanone', 'Grobes Geschütz'],
    ['Kapitän', 'Chef auf dem Schiff'],
    ['Karotte', 'Orangefarbenes Wurzelgemüse'],
    ['Kissen', 'Weich unter dem Kopf'],
    ['Knochen', 'Teil des Skeletts'],
    ['Knoten', 'Verschlungenes Seilstück'],
    ['Koffer', 'Gepäck für die Reise'],
    ['Kompass', 'Zeigt nach Norden'],
    ['Kreide', 'Schreibt auf der Tafel'],
    ['Küche', 'Raum zum Kochen'],
    ['Kupfer', 'Rötliches Metall'],
    ['Lawine', 'Schneemassen zu Tal'],
    ['Laterne', 'Licht an der Strasse'],
    ['Leiter', 'Hilfe zum Hinaufsteigen'],
    ['Löffel', 'Besteck für die Suppe'],
    ['Mantel', 'Warmes Kleidungsstück'],
    ['Meister', 'Sieger der Saison'],
    ['Messer', 'Klinge zum Schneiden'],
    ['Möbel', 'Einrichtung der Wohnung'],
    ['Muschel', 'Schale am Strand'],
    ['Muskel', 'Bewegt die Knochen'],
    ['Mutter', 'Weiblicher Elternteil'],
    ['Nacken', 'Rückseite des Halses'],
    ['Nebel', 'Trübt die Sicht'],
    ['Papier', 'Beschreibbares Blatt'],
    ['Pfanne', 'Flaches Kochgeschirr'],
    ['Pfeffer', 'Scharfes Gewürz'],
    ['Pflanze', 'Wächst im Boden'],
    ['Rätsel', 'Aufgabe zum Knobeln'],
    ['Reifen', 'Gummi auf der Felge'],
    ['Reiter', 'Sitzt auf dem Pferd'],
    ['Ritter', 'Kämpfer im Harnisch'],
    ['Rücken', 'Hinterseite des Rumpfes'],
    ['Sattel', 'Sitz auf dem Pferd'],
    ['Schacht', 'Tiefer Gang im Bergwerk'],
    ['Schere', 'Schneidet Papier'],
    ['Schlange', 'Kriecht ohne Beine'],
    ['Schnabel', 'Mund des Vogels'],
    ['Schwester', 'Tochter derselben Eltern'],
    ['Sichel', 'Krummes Erntegerät'],
    ['Silber', 'Weisses Edelmetall'],
    ['Spiegel', 'Wirft das Bild zurück'],
    ['Spinne', 'Webt ein Netz'],
    ['Strand', 'Sand am Meer'],
    ['Strasse', 'Weg für Autos'],
    ['Stunde', 'Sechzig Minuten'],
    ['Teller', 'Geschirr für das Essen'],
    ['Teppich', 'Belag auf dem Boden'],
    ['Traube', 'Frucht für den Wein'],
    ['Treppe', 'Führt in den ersten Stock'],
    ['Tugend', 'Gute Eigenschaft'],
    ['Urlaub', 'Freie Tage zum Reisen'],
    ['Vulkan', 'Berg, der Lava speit'],
    ['Wecker', 'Klingelt am Morgen'],
    ['Weiher', 'Kleiner Teich'],
    ['Winkel', 'Ecke im Raum'],
    ['Wipfel', 'Spitze des Baumes'],
    ['Wurzel', 'Teil der Pflanze im Boden'],
    ['Zeiger', 'Läuft über das Zifferblatt'],
    ['Zirkus', 'Zelt mit Manege'],
    ['Zitrone', 'Saure gelbe Frucht'],
    ['Zucker', 'Süsst den Tee'],
    ['Zwiebel', 'Treibt Tränen ins Auge']
  ]
}
