import type { Category } from './index'

/**
 * Third batch of filling words, weighted towards the shortest entries.
 *
 * Three letter words are what a dense grid runs out of first — they are the
 * pieces that close a gap between two crossing words, and German simply has
 * few of them. Everything here was written against the words already in the
 * pool; `scripts/check-woerter.mjs` shows what the batch actually added.
 */
export const grundwortschatz3: Category = {
  id: 'grundwortschatz3',
  label: 'Grundwortschatz III',
  always: true,
  entries: [
    // --- drei Buchstaben ---
    ['Ara', 'Bunter Papagei'],
    ['Alb', 'Höhenzug in Schwaben'],
    ['Böe', 'Plötzlicher Windstoss'],
    ['Bon', 'Beleg an der Kasse'],
    ['Box', 'Stall für ein Pferd'],
    ['Cup', 'Pokal im Sport'],
    ['Dur', 'Helles Tongeschlecht'],
    ['Eid', 'Feierlicher Schwur'],
    ['Ekg', 'Kurve vom Herzen'],
    ['Fön', 'Gerät für nasses Haar'],
    ['Gig', 'Auftritt der Band'],
    ['Hag', 'Hecke um den Garten'],
    ['Ion', 'Geladenes Teilchen'],
    ['Lee', 'Windabgewandte Seite'],
    ['Lot', 'Senkblei des Maurers'],
    ['Mal', 'Zeitpunkt in einer Reihe'],
    ['Met', 'Wein aus Honig'],
    ['Ode', 'Feierliches Gedicht'],
    ['Ohm', 'Einheit des Widerstands'],
    ['Pkw', 'Wagen für Personen'],
    ['Rap', 'Gereimter Sprechgesang'],
    ['Sud', 'Brühe vom Kochen'],
    ['Wok', 'Pfanne aus Asien'],
    ['Yak', 'Rind aus Tibet'],
    ['Zen', 'Richtung im Buddhismus'],
    ['Zip', 'Format für Archive'],

    // --- vier Buchstaben ---
    ['Öse', 'Ring für die Schnur'],
    ['Abbé', 'Geistlicher in Frankreich'],
    ['Ahle', 'Pfriem des Schusters'],
    ['Amme', 'Stillt fremde Kinder'],
    ['Arche', 'Rettungsschiff des Noah'],
    ['Baum', 'Stamm mit Krone'],
    ['Beize', 'Mittel zum Färben von Holz'],
    ['Bube', 'Karte über der Zehn'],
    ['Bühne', 'Brett für Schauspieler'],
    ['Datei', 'Gespeicherter Inhalt'],
    ['Daune', 'Weiche Feder der Gans'],
    ['Diele', 'Brett auf dem Boden'],
    ['Eber', 'Männliches Schwein'],
    ['Egge', 'Gerät hinter dem Traktor'],
    ['Elle', 'Altes Mass für Stoff'],
    ['Erle', 'Baum am feuchten Ufer'],
    ['Ernte', 'Ertrag des Feldes'],
    ['Esse', 'Feuerstelle des Schmieds'],
    ['Falte', 'Knick im Stoff'],
    ['Farbe', 'Rot, Gelb oder Blau'],
    ['Firma', 'Betrieb mit Angestellten'],
    ['Flöte', 'Instrument zum Blasen'],
    ['Frost', 'Kälte unter null Grad'],
    ['Gerste', 'Getreide fürs Bier'],
    ['Gitter', 'Stäbe vor dem Fenster'],
    ['Glocke', 'Läutet im Turm'],
    ['Grille', 'Zirpt in der Wiese'],
    ['Grotte', 'Höhle im Fels'],
    ['Hacke', 'Werkzeug im Gemüsebeet'],
    ['Hälfte', 'Einer von zwei Teilen'],
    ['Haube', 'Deckel über dem Motor'],
    ['Hecke', 'Grüne Grenze im Garten'],
    ['Hütte', 'Kleines Haus im Gebirge'],
    ['Jacke', 'Kurzer Mantel'],
    ['Kachel', 'Platte an der Wand'],
    ['Kaktus', 'Pflanze mit Stacheln'],
    ['Kamera', 'Gerät für Aufnahmen'],
    ['Kanzel', 'Platz des Predigers'],
    ['Karren', 'Wagen zum Ziehen'],
    ['Kater', 'Männliche Katze'],
    ['Keller', 'Raum unter dem Haus'],
    ['Kette', 'Schmuck um den Hals'],
    ['Klaue', 'Kralle des Raubtiers'],
    ['Kloster', 'Haus der Mönche'],
    ['Krähe', 'Schwarzer Rabenvogel'],
    ['Kran', 'Hebt Lasten am Bau'],
    ['Kutsche', 'Wagen mit Pferden'],
    ['Laden', 'Geschäft an der Ecke'],
    ['Leine', 'Führt den Hund'],
    ['Lende', 'Stück Fleisch vom Rücken'],
    ['Linde', 'Baum mit herzförmigen Blättern'],
    ['Locke', 'Gedrehte Haarsträhne'],
    ['Lunge', 'Organ zum Atmen'],
    ['Mähne', 'Haar am Pferdehals'],
    ['Mauer', 'Wand aus Steinen'],
    ['Möhre', 'Gelbe Rübe'],
    ['Mörtel', 'Bindet die Ziegel'],
    ['Mühle', 'Mahlt das Korn'],
    ['Nessel', 'Pflanze, die brennt'],
    ['Nische', 'Vertiefung in der Wand'],
    ['Notiz', 'Kurze Aufzeichnung'],
    ['Ordner', 'Mappe für Papiere'],
    ['Palme', 'Baum am Südstrand'],
    ['Panne', 'Schaden am Auto'],
    ['Pinsel', 'Werkzeug des Malers'],
    ['Pistole', 'Kleine Handfeuerwaffe'],
    ['Planke', 'Dickes Brett am Schiff'],
    ['Portal', 'Grosses Tor am Bau'],
    ['Prise', 'Kleine Menge Salz'],
    ['Pudel', 'Hund mit Locken'],
    ['Quaste', 'Büschel an der Schnur'],
    ['Rakete', 'Fliegt ins Weltall'],
    ['Rebe', 'Pflanze mit Trauben'],
    ['Riegel', 'Verschluss an der Tür'],
    ['Rinne', 'Führt das Regenwasser'],
    ['Rispe', 'Form des Blütenstands'],
    ['Robe', 'Feierliches Gewand'],
    ['Rüssel', 'Nase des Elefanten'],
    ['Säule', 'Tragender Pfeiler'],
    ['Schaufel', 'Gerät zum Graben'],
    ['Scheibe', 'Glas im Fenster'],
    ['Schiene', 'Führt den Zug'],
    ['Schuppen', 'Häuschen für Geräte'],
    ['Seide', 'Feiner Stoff der Raupe'],
    ['Sessel', 'Bequemer Sitz'],
    ['Sohle', 'Unterseite des Schuhs'],
    ['Spaten', 'Grabwerkzeug im Garten'],
    ['Speiche', 'Stab im Rad'],
    ['Spule', 'Rolle für den Faden'],
    ['Stange', 'Langer runder Stab'],
    ['Stengel', 'Stiel der Blume'],
    ['Strumpf', 'Kleidung für den Fuss'],
    ['Taucher', 'Geht unter Wasser'],
    ['Tresor', 'Schrank für Wertsachen'],
    ['Trichter', 'Hilft beim Umfüllen'],
    ['Tunnel', 'Weg durch den Berg'],
    ['Ufer', 'Rand des Flusses'],
    ['Verband', 'Binde um die Wunde'],
    ['Wagen', 'Fährt auf vier Rädern'],
    ['Weste', 'Jacke ohne Ärmel'],
    ['Wiege', 'Bett für den Säugling'],
    ['Zange', 'Werkzeug zum Greifen'],
    ['Zettel', 'Kleines Blatt Papier'],
    ['Ziegel', 'Stein für die Mauer'],
    ['Zwerg', 'Kleiner Kerl im Märchen']
  ]
}
