import type { Category } from './index'

export const menschSprache: Category = {
  id: 'menschSprache',
  label: 'Mensch & Sprache',
  entries: [
    ['Freude', 'Gefühl des Glücks'],
    ['Trauer', 'Gefühl nach einem Verlust'],
    ['Angst', 'Gefühl bei Gefahr'],
    ['Wut', 'Heftiger Zorn'],
    ['Zorn', 'Starker Ärger'],
    ['Neid', 'Missgunst gegenüber anderen'],
    ['Stolz', 'Gefühl über eigene Leistung'],
    ['Scham', 'Peinliches Gefühl'],
    ['Reue', 'Bedauern über eine Tat'],
    ['Hoffnung', 'Zuversicht auf Besseres'],
    ['Sehnsucht', 'Starkes Verlangen nach etwas Fernem'],
    ['Liebe', 'Tiefe Zuneigung'],
    ['Hass', 'Gegenteil der Liebe'],
    ['Mitleid', 'Anteilnahme am Leid anderer'],
    ['Dankbarkeit', 'Gefühl nach einer Wohltat'],
    ['Langeweile', 'Gefühl bei fehlender Beschäftigung'],
    ['Neugier', 'Drang, Neues zu erfahren'],
    ['Ueberraschung', 'Unerwartetes Ereignis'],
    ['Erleichterung', 'Gefühl nach überstandener Sorge'],
    ['Gelassenheit', 'Innere Ruhe'],
    ['Mut', 'Tapferkeit vor der Gefahr'],
    ['Geduld', 'Fähigkeit zu warten'],
    ['Ehrgeiz', 'Starkes Streben nach Erfolg'],
    ['Fleiss', 'Beharrliches Arbeiten'],
    ['Faulheit', 'Abneigung gegen Arbeit'],
    ['Ehrlichkeit', 'Aufrichtigkeit'],
    ['Treue', 'Beständigkeit in der Bindung'],
    ['Grosszuegigkeit', 'Bereitschaft zu geben'],
    ['Bescheidenheit', 'Zurückhaltung im Auftreten'],
    ['Hoeflichkeit', 'Gutes Benehmen'],
    ['Ruecksicht', 'Achtung auf andere'],
    ['Vertrauen', 'Glaube an die Verlässlichkeit'],
    ['Respekt', 'Achtung vor jemandem'],
    ['Toleranz', 'Duldsamkeit gegenüber anderem'],
    ['Vorurteil', 'Urteil ohne Prüfung'],
    ['Gewissen', 'Innere moralische Instanz'],
    ['Charakter', 'Wesensart eines Menschen'],
    ['Talent', 'Angeborene Begabung'],
    ['Erfahrung', 'Durch Erleben erworbenes Wissen'],
    ['Erinnerung', 'Bild aus der Vergangenheit'],
    ['Gedanke', 'Produkt des Denkens'],
    ['Traum', 'Bilder im Schlaf'],
    ['Wunsch', 'Was man sich erhofft'],
    ['Ziel', 'Was man erreichen will'],
    ['Entscheidung', 'Wahl zwischen Möglichkeiten'],
    ['Zweifel', 'Ungewissheit über etwas'],
    ['Meinung', 'Persönliche Ansicht'],
    ['Ueberzeugung', 'Feste innere Haltung'],
    ['Idee', 'Plötzlicher guter Einfall'],
    ['Fantasie', 'Vorstellungskraft'],
    ['Humor', 'Sinn für das Komische'],
    ['Witz', 'Kurze lustige Geschichte'],
    ['Laecheln', 'Freundlicher Gesichtsausdruck'],
    ['Traene', 'Tropfen beim Weinen'],

    ['Familie', 'Engste Verwandtschaft'],
    ['Eltern', 'Mutter und Vater'],
    ['Mutter', 'Weiblicher Elternteil'],
    ['Vater', 'Männlicher Elternteil'],
    ['Kind', 'Junger Mensch'],
    ['Sohn', 'Männliches Kind'],
    ['Tochter', 'Weibliches Kind'],
    ['Bruder', 'Männliches Geschwister'],
    ['Schwester', 'Weibliches Geschwister'],
    ['Grossvater', 'Vater des Vaters'],
    ['Grossmutter', 'Mutter der Mutter'],
    ['Enkel', 'Kind des eigenen Kindes'],
    ['Onkel', 'Bruder eines Elternteils'],
    ['Tante', 'Schwester eines Elternteils'],
    ['Cousin', 'Kind von Onkel oder Tante'],
    ['Neffe', 'Sohn des Geschwisters'],
    ['Nichte', 'Tochter des Geschwisters'],
    ['Zwilling', 'Gleichzeitig geborenes Geschwister'],
    ['Pate', 'Taufzeuge eines Kindes'],
    ['Ehepaar', 'Verheiratete zwei Menschen'],
    ['Braut', 'Frau bei der Hochzeit'],
    ['Witwe', 'Frau nach dem Tod des Mannes'],
    ['Freund', 'Nahestehender Mensch'],
    ['Nachbar', 'Wer nebenan wohnt'],
    ['Gast', 'Wer eingeladen ist'],
    ['Fremder', 'Unbekannter Mensch'],
    ['Jugend', 'Lebensalter nach der Kindheit'],
    ['Kindheit', 'Erste Lebensjahre'],
    ['Alter', 'Späte Lebensphase'],
    ['Generation', 'Altersgruppe einer Zeit'],
    ['Geburt', 'Beginn des Lebens'],
    ['Taufe', 'Kirchliche Aufnahme'],
    ['Ehe', 'Rechtliche Verbindung zweier Menschen'],
    ['Scheidung', 'Auflösung der Ehe'],
    ['Beerdigung', 'Bestattung eines Verstorbenen'],

    ['Sprache', 'Mittel der Verständigung'],
    ['Wort', 'Kleinste selbstständige Spracheinheit'],
    ['Satz', 'Abgeschlossene sprachliche Einheit'],
    ['Silbe', 'Teil eines Wortes'],
    ['Buchstabe', 'Zeichen des Alphabets'],
    ['Alphabet', 'Geordnete Reihe der Buchstaben'],
    ['Vokal', 'Selbstlaut'],
    ['Konsonant', 'Mitlaut'],
    ['Grammatik', 'Regelwerk der Sprache'],
    ['Verb', 'Tunwort'],
    ['Substantiv', 'Hauptwort'],
    ['Adjektiv', 'Eigenschaftswort'],
    ['Pronomen', 'Fürwort'],
    ['Artikel', 'Begleiter des Hauptworts'],
    ['Praeposition', 'Verhältniswort'],
    ['Endung', 'Letzter Teil eines gebeugten Worts'],
    ['Mehrzahl', 'Plural'],
    ['Einzahl', 'Singular'],
    ['Zeitform', 'Tempus des Verbs'],
    ['Komma', 'Satzzeichen zum Trennen'],
    ['Punkt', 'Satzzeichen am Ende'],
    ['Fragezeichen', 'Zeichen nach einer Frage'],
    ['Klammer', 'Zeichen für Einschübe'],
    ['Akzent', 'Betonung, auch Tonfall'],
    ['Dialekt', 'Regionale Sprachform'],
    ['Mundart', 'Andere Bezeichnung für Dialekt'],
    ['Fremdwort', 'Aus einer anderen Sprache entlehnt'],
    ['Uebersetzung', 'Übertragung in eine andere Sprache'],
    ['Dolmetscher', 'Mündlicher Übersetzer'],
    ['Woerterbuch', 'Nachschlagewerk für Wörter'],
    ['Synonym', 'Wort gleicher Bedeutung'],
    ['Gegenteil', 'Wort entgegengesetzter Bedeutung'],
    ['Sprichwort', 'Feststehende Lebensweisheit'],
    ['Redensart', 'Feste bildhafte Wendung'],
    ['Zitat', 'Wörtlich übernommene Stelle'],
    ['Rede', 'Vortrag vor Publikum'],
    ['Gespraech', 'Austausch zwischen Menschen'],
    ['Diskussion', 'Erörterung mit Argumenten'],
    ['Streit', 'Heftige Auseinandersetzung'],
    ['Argument', 'Begründung im Gespräch'],
    ['Antwort', 'Reaktion auf eine Frage'],
    ['Frage', 'Bitte um Auskunft'],
    ['Erklaerung', 'Verständlich machende Darlegung'],
    ['Ausrede', 'Vorgeschobener Grund'],
    ['Luege', 'Bewusst falsche Aussage'],
    ['Wahrheit', 'Was den Tatsachen entspricht'],
    ['Geheimnis', 'Was verborgen bleibt'],
    ['Geruecht', 'Unbestätigte Nachricht'],
    ['Nachricht', 'Übermittelte Information'],
    ['Botschaft', 'Wichtige Mitteilung'],
    ['Gruss', 'Worte beim Begegnen'],
    ['Abschied', 'Worte beim Trennen'],
    ['Versprechen', 'Feste Zusage'],
    ['Rat', 'Hilfreicher Vorschlag'],
    ['Warnung', 'Hinweis auf Gefahr'],
    ['Lob', 'Anerkennende Worte'],
    ['Tadel', 'Rüge für ein Fehlverhalten'],
    ['Kritik', 'Beurteilung, oft negativ'],
    ['Dank', 'Ausdruck der Erkenntlichkeit'],
    ['Bitte', 'Höflicher Wunsch'],
    ['Befehl', 'Bindende Anweisung'],
    ['Verbot', 'Untersagung'],
    ['Erlaubnis', 'Genehmigung'],

    ['Staat', 'Politisch organisiertes Gemeinwesen'],
    ['Regierung', 'Führung eines Staates'],
    ['Parlament', 'Volksvertretung'],
    ['Gesetz', 'Verbindliche Rechtsnorm'],
    ['Verfassung', 'Grundordnung des Staates'],
    ['Recht', 'Gesamtheit der Normen'],
    ['Gericht', 'Institution der Rechtsprechung'],
    ['Richter', 'Wer Recht spricht'],
    ['Anwalt', 'Rechtlicher Beistand'],
    ['Zeuge', 'Wer etwas beobachtet hat'],
    ['Urteil', 'Entscheidung des Gerichts'],
    ['Strafe', 'Folge einer Tat'],
    ['Gefaengnis', 'Ort des Freiheitsentzugs'],
    ['Polizei', 'Ordnungsmacht'],
    ['Feuerwehr', 'Wer Brände löscht'],
    ['Rettungsdienst', 'Wer bei Notfällen hilft'],
    ['Notruf', 'Anruf in der Gefahr'],
    ['Buerger', 'Angehöriger eines Staates'],
    ['Wahl', 'Bestimmung von Vertretern'],
    ['Stimme', 'Was man bei der Wahl abgibt'],
    ['Partei', 'Politische Vereinigung'],
    ['Minister', 'Mitglied der Regierung'],
    ['Kanzler', 'Regierungschef in Deutschland'],
    ['Praesident', 'Staatsoberhaupt vieler Länder'],
    ['Buergermeister', 'Chef der Gemeinde'],
    ['Gemeinde', 'Kleinste Verwaltungseinheit'],
    ['Rathaus', 'Sitz der Stadtverwaltung'],
    ['Behoerde', 'Amtliche Stelle'],
    ['Formular', 'Vordruck zum Ausfüllen'],
    ['Antrag', 'Formelles Gesuch'],
    ['Ausweis', 'Amtliches Dokument zur Person'],
    ['Pass', 'Dokument für die Auslandsreise'],
    ['Steuer', 'Abgabe an den Staat'],
    ['Zoll', 'Abgabe an der Grenze'],
    ['Rente', 'Einkommen im Alter'],
    ['Versicherung', 'Schutz gegen Schäden'],
    ['Gewerkschaft', 'Vertretung der Arbeitnehmer'],
    ['Streik', 'Arbeitsniederlegung'],
    ['Demonstration', 'Öffentlicher Protestzug'],
    ['Freiheit', 'Zustand ohne Zwang'],
    ['Gerechtigkeit', 'Faire Behandlung aller'],
    ['Gleichheit', 'Gleiche Rechte für alle'],
    ['Frieden', 'Zustand ohne Krieg'],
    ['Krieg', 'Bewaffneter Konflikt'],
    ['Vertrag', 'Bindende Übereinkunft'],
    ['Buendnis', 'Zusammenschluss zum Schutz'],
    ['Botschafter', 'Vertreter im Ausland'],
    ['Grenze', 'Trennlinie zwischen Gebieten'],
    ['Flucht', 'Verlassen aus Not'],
    ['Asyl', 'Zuflucht für Verfolgte'],
    ['Integration', 'Eingliederung in die Gesellschaft'],
    ['Gesellschaft', 'Gemeinschaft der Menschen'],
    ['Kultur', 'Geistige Hervorbringungen'],
    ['Tradition', 'Überliefertes Brauchtum'],
    ['Brauch', 'Überlieferte Sitte'],
    ['Religion', 'Glaubensgemeinschaft'],
    ['Glaube', 'Innere Überzeugung'],
    ['Gebet', 'Zwiesprache mit Gott'],
    ['Segen', 'Zuspruch von Gutem'],
    ['Predigt', 'Rede im Gottesdienst'],
    ['Pfarrer', 'Geistlicher der Gemeinde'],
    ['Priester', 'Geistlicher Amtsträger'],
    ['Moench', 'Mann im Kloster'],
    ['Nonne', 'Frau im Kloster'],
    ['Bibel', 'Heilige Schrift der Christen'],
    ['Koran', 'Heilige Schrift des Islam'],
    ['Engel', 'Himmlischer Bote'],
    ['Heiliger', 'Von der Kirche Verehrter'],
    ['Wunder', 'Unerklärliches Ereignis'],
    ['Schicksal', 'Vorbestimmter Lauf des Lebens'],
    ['Aberglaube', 'Glaube an übernatürliche Zeichen'],
    ['Glueck', 'Günstige Fügung'],
    ['Pech', 'Ungünstige Fügung'],
    ['Zufall', 'Unvorhergesehenes Zusammentreffen'],

    ['Anfang', 'Erster Teil von etwas'],
    ['Ende', 'Letzter Teil von etwas'],
    ['Mitte', 'Gleich weit von beiden Seiten'],
    ['Seite', 'Linke oder rechte Fläche'],
    ['Rand', 'Äussere Begrenzung'],
    ['Kante', 'Scharfe Begrenzungslinie'],
    ['Ecke', 'Wo zwei Kanten treffen'],
    ['Spitze', 'Oberstes oder schärfstes Ende'],
    ['Grund', 'Ursache, auch Boden'],
    ['Ursache', 'Auslöser einer Wirkung'],
    ['Wirkung', 'Folge einer Ursache'],
    ['Folge', 'Was sich daraus ergibt'],
    ['Zweck', 'Wozu etwas dient'],
    ['Nutzen', 'Vorteil aus einer Sache'],
    ['Schaden', 'Nachteil oder Verlust'],
    ['Gefahr', 'Drohendes Unheil'],
    ['Sicherheit', 'Zustand ohne Gefahr'],
    ['Risiko', 'Mögliche Gefahr'],
    ['Chance', 'Günstige Gelegenheit'],
    ['Problem', 'Zu lösende Schwierigkeit'],
    ['Loesungsweg', 'Weg zum Ergebnis'],
    ['Fehler', 'Abweichung vom Richtigen'],
    ['Irrtum', 'Falsche Annahme'],
    ['Ordnung', 'Geregelter Zustand'],
    ['Unordnung', 'Fehlende Ordnung'],
    ['Regel', 'Verbindliche Vorschrift'],
    ['Ausnahme', 'Abweichung von der Regel'],
    ['Muster', 'Vorlage oder Wiederholung'],
    ['Vorbild', 'Beispiel zum Nacheifern'],
    ['Beispiel', 'Einzelfall zur Erläuterung'],
    ['Vergleich', 'Gegenüberstellung'],
    ['Unterschied', 'Was nicht gleich ist'],
    ['Aehnlichkeit', 'Teilweise Übereinstimmung'],
    ['Gegensatz', 'Vollständiger Unterschied'],
    ['Menge', 'Anzahl oder Masse'],
    ['Anzahl', 'Wie viele'],
    ['Haelfte', 'Einer von zwei gleichen Teilen'],
    ['Drittel', 'Einer von drei gleichen Teilen'],
    ['Viertel', 'Einer von vier gleichen Teilen'],
    ['Rest', 'Was übrig bleibt'],
    ['Paar', 'Zwei zusammengehörige'],
    ['Dutzend', 'Zwölf Stück'],
    ['Reihe', 'Geordnete Folge'],
    ['Gruppe', 'Mehrere zusammen'],
    ['Stapel', 'Aufeinandergelegte Dinge'],
    ['Haufen', 'Ungeordnete Menge'],
    ['Stueck', 'Einzelnes Exemplar'],
    ['Teil', 'Abschnitt eines Ganzen'],
    ['Ganzes', 'Alle Teile zusammen'],

    ['Meter', 'Einheit der Länge'],
    ['Kilometer', 'Tausend Meter'],
    ['Zentimeter', 'Hundertstel Meter'],
    ['Gramm', 'Einheit der Masse'],
    ['Kilogramm', 'Tausend Gramm'],
    ['Tonne', 'Tausend Kilogramm'],
    ['Liter', 'Einheit des Volumens'],
    ['Sekunde', 'Kleine Zeiteinheit'],
    ['Minute', 'Sechzig Sekunden'],
    ['Stunde', 'Sechzig Minuten'],
    ['Woche', 'Sieben Tage'],
    ['Monat', 'Etwa dreissig Tage'],
    ['Jahr', 'Zwölf Monate'],
    ['Jahrzehnt', 'Zehn Jahre'],
    ['Jahrhundert', 'Hundert Jahre'],
    ['Datum', 'Angabe des Tages'],
    ['Montag', 'Erster Tag der Woche'],
    ['Dienstag', 'Zweiter Tag der Woche'],
    ['Mittwoch', 'Mitte der Woche'],
    ['Donnerstag', 'Vierter Tag der Woche'],
    ['Freitag', 'Letzter Arbeitstag der Woche'],
    ['Samstag', 'Tag vor dem Sonntag'],
    ['Sonntag', 'Tag der Ruhe'],
    ['Januar', 'Erster Monat'],
    ['Februar', 'Kürzester Monat'],
    ['Maerz', 'Monat des Frühlingsanfangs'],
    ['April', 'Monat der Scherze'],
    ['Juni', 'Monat des Sommeranfangs'],
    ['Juli', 'Hochsommermonat'],
    ['August', 'Monat der Ferien'],
    ['September', 'Monat des Herbstanfangs'],
    ['Oktober', 'Monat des Oktoberfests'],
    ['November', 'Trüber Herbstmonat'],
    ['Dezember', 'Monat der Weihnacht'],
    ['Morgen', 'Beginn des Tages'],
    ['Mittag', 'Mitte des Tages'],
    ['Abend', 'Ende des Tages'],
    ['Nacht', 'Dunkle Tageszeit'],
    ['Dammerung', 'Übergang zwischen Tag und Nacht'],
    ['Gegenwart', 'Das Jetzt'],
    ['Vergangenheit', 'Was gewesen ist'],
    ['Zukunft', 'Was kommen wird'],
    ['Ewigkeit', 'Zeit ohne Ende'],
    ['Augenblick', 'Sehr kurze Zeitspanne'],
    ['Pause', 'Unterbrechung'],
    ['Verspaetung', 'Zu spätes Eintreffen'],
    ['Frist', 'Festgelegter Zeitraum'],

    ['Rot', 'Farbe des Blutes'],
    ['Blau', 'Farbe des Himmels'],
    ['Gelb', 'Farbe der Sonne'],
    ['Gruen', 'Farbe der Blätter'],
    ['Schwarz', 'Farbe der Nacht'],
    ['Weiss', 'Farbe des Schnees'],
    ['Grau', 'Farbe zwischen Schwarz und Weiss'],
    ['Braun', 'Farbe der Erde'],
    ['Orange', 'Farbe zwischen Rot und Gelb'],
    ['Violett', 'Farbe zwischen Blau und Rot'],
    ['Rosa', 'Helles Rot'],
    ['Tuerkis', 'Farbe zwischen Blau und Grün'],
    ['Beige', 'Helles Sandbraun'],
    ['Gross', 'Von beträchtlicher Ausdehnung'],
    ['Klein', 'Von geringer Ausdehnung'],
    ['Lang', 'Von grosser Länge'],
    ['Kurz', 'Von geringer Länge'],
    ['Breit', 'Von grosser Weite'],
    ['Schmal', 'Von geringer Breite'],
    ['Hoch', 'Weit nach oben reichend'],
    ['Tief', 'Weit nach unten reichend'],
    ['Dick', 'Von grossem Umfang'],
    ['Duenn', 'Von geringem Umfang'],
    ['Schwer', 'Von grossem Gewicht'],
    ['Leicht', 'Von geringem Gewicht'],
    ['Warm', 'Angenehm erwärmt'],
    ['Kalt', 'Von niedriger Temperatur'],
    ['Heiss', 'Sehr warm'],
    ['Nass', 'Von Wasser durchdrungen'],
    ['Trocken', 'Ohne Feuchtigkeit'],
    ['Hart', 'Nicht nachgebend'],
    ['Weich', 'Leicht nachgebend'],
    ['Glatt', 'Ohne Unebenheit'],
    ['Rau', 'Mit unebener Oberfläche'],
    ['Scharf', 'Gut schneidend, auch stark gewürzt'],
    ['Stumpf', 'Nicht scharf'],
    ['Hell', 'Viel Licht abgebend'],
    ['Dunkel', 'Wenig Licht'],
    ['Laut', 'Von grosser Lautstärke'],
    ['Leise', 'Kaum hörbar'],
    ['Schnell', 'Mit hohem Tempo'],
    ['Langsam', 'Mit geringem Tempo'],
    ['Frueh', 'Vor der üblichen Zeit'],
    ['Spaet', 'Nach der üblichen Zeit'],
    ['Neu', 'Erst kurz vorhanden'],
    ['Alt', 'Seit langem vorhanden'],
    ['Jung', 'Von geringem Alter'],
    ['Reich', 'Mit viel Besitz'],
    ['Arm', 'Ohne Besitz'],
    ['Stark', 'Mit viel Kraft'],
    ['Schwach', 'Ohne viel Kraft'],
    ['Suess', 'Wie Zucker schmeckend'],
    ['Sauer', 'Wie Zitrone schmeckend'],
    ['Bitter', 'Herb im Geschmack'],
    ['Salzig', 'Nach Salz schmeckend'],
    ['Voll', 'Bis zum Rand gefüllt'],
    ['Leer', 'Ohne Inhalt'],
    ['Offen', 'Nicht verschlossen'],
    ['Geschlossen', 'Nicht offen'],
    ['Frei', 'Ohne Beschränkung'],
    ['Gerade', 'Ohne Krümmung'],
    ['Krumm', 'Nicht gerade'],
    ['Rund', 'Von kreisförmiger Gestalt'],
    ['Eckig', 'Mit Ecken versehen'],
    ['Sauber', 'Ohne Schmutz'],
    ['Schmutzig', 'Mit Schmutz behaftet'],
    ['Fleissig', 'Eifrig arbeitend'],
    ['Muede', 'Nach Schlaf verlangend'],
    ['Wach', 'Nicht schlafend'],
    ['Gesund', 'Ohne Krankheit'],
    ['Krank', 'Nicht gesund'],
    ['Klug', 'Von guter Auffassungsgabe'],
    ['Dumm', 'Ohne Verstand'],
    ['Lustig', 'Zum Lachen bringend'],
    ['Traurig', 'Von Kummer erfüllt'],
    ['Freundlich', 'Von netter Art'],
    ['Boese', 'Von schlechter Gesinnung'],
    ['Ruhig', 'Ohne Aufregung'],
    ['Nervoes', 'Innerlich unruhig'],
    ['Wichtig', 'Von grosser Bedeutung'],
    ['Einfach', 'Ohne Schwierigkeit'],
    ['Schwierig', 'Nicht leicht zu bewältigen'],
    ['Moeglich', 'Machbar'],
    ['Noetig', 'Erforderlich'],
    ['Fertig', 'Zu Ende gebracht'],
    ['Bereit', 'Zum Handeln gerüstet']
  ]
}
